Airflow vs Oozie update
astronomer/airflow-guides pull request #141
Opened 2020-09-22 13:08 UTC by sunkickr

Updated Airflow vs Oozie guide. Removed chippy/aggressive language. Researched tools and updated guide to reflect current competitive landscape. Added section about compatibility.

2020-09-23 14:06 UTC, petedejoy requested changes

2020-09-23 14:06 UTC, petedejoy commented on guides/airflow-vs-oozie.md
> +# Summary
@sunkickr - I know this is how it was before, but we've changed our website such that all inline headers should be H2s (ie. `##`) instead of H1s (ie. `#`). Mind going through this and just adding an extra # to each title section? Same goes for all tities ie H2s should now be H3s.

2020-09-23 14:06 UTC, petedejoy commented on guides/airflow-vs-oozie.md
>  ![airflow](https://assets.astronomer.io/website/img/guides/Screen+Shot+2018-07-10+at+4.26.28+PM.png)
Gonna redeploy these images now, will check your branch out and push up the new URL to the asset.

2020-09-23 14:12 UTC, sunkickr commented on guides/airflow-vs-oozie.md
> +# Summary
@petedejoy I will run through the guide and make this change.

2020-09-23 22:28 UTC, paolaperaza approved these changes
Left a few minor copy suggestions, @petedejoy @sunkickr ! Looks good to me content wise 😊  Thank you both for taking the charge on cleaning this up.

2020-09-23 22:28 UTC, paolaperaza commented on guides/airflow-vs-oozie.md
> +We often get questions regarding the differences between [Airflow](https://airflow.apache.org/) and [Oozie](http://oozie.apache.org/). While we at Astronomer may be a bit biased in our knowledge, we’
I personally wouldn't refer to "we at Astronomer" here and have the reader think twice about our bias in writing this. Maybe stay neutral/objective and say something like:

"As tools within the data engineering industry continue to expand their footprint, it's common for product offerings in the space to be directly compared against each other for a variety of use cases.

For those evaluating Apache Airflow and Oozie, we've put together a summary of the key differences between the two open-source frameworks."

2020-09-23 22:28 UTC, paolaperaza commented on guides/airflow-vs-oozie.md
> +At a high level, Airflow leverages the increasingly standardized use of Python to allow you to create extremely complex workflows via a commonly understood programming language, while Oozie is optimi
Maybe change:

- increasingly standardized use of Python > "industry standard use of Python"
- to to allow you to > "to allow users to"
- take out "extremely" in "extremely complex workflows"

2020-09-23 22:28 UTC, paolaperaza commented on guides/airflow-vs-oozie.md
> +Created by [Airbnb Data Engineer Maxime Beauchemin](https://www.linkedin.com/in/maximebeauchemin), Airflow is an open-source workflow management system designed for authoring, scheduling, and monitor
- "workflows are written in Python" instead of "designed"? 
- "which allows them to be flexible" > "which makes for flexible interaction with third-party APIs..."

On the last sentence, could consider changing order to end strong:

"Measured by Github stars and number of contributors, Apache Airflow is the most popular open-source workflow management tool on the market today."

2020-09-23 22:28 UTC, paolaperaza commented on guides/airflow-vs-oozie.md
> +As mentioned above, Airflow allows you to write your DAGs in Python while Oozie uses Java or XML. Per the [PYPL popularity index](http://pypl.github.io/PYPL.html), which is created by analyzing how o
Belt may work here lol but the "under your belt" expression isn't complete, so I might just say "stack"? repertoire?

2020-09-23 22:28 UTC, paolaperaza commented on guides/airflow-vs-oozie.md
> +Community contributions are significant in that they're reflective of the community's faith in the future of the project and indicate that the community is actively developing features. Oozie will wo
Run-on sentence at the end here. I'd say:

"If your existing tools are embedded in the Hadoop ecosystem, Oozie will be an easy orchestration tool to adopt. If you want to future proof your data infrastructure and instead adopt a framework with an active community that will continue to add features, support and extensions that accommodate more robust use cases and integrate more widely with the modern data stack, go with Apache Airflow."

2020-09-24 15:54 UTC, sunkickr commented on guides/airflow-vs-oozie.md
> +We often get questions regarding the differences between [Airflow](https://airflow.apache.org/) and [Oozie](http://oozie.apache.org/). While we at Astronomer may be a bit biased in our knowledge, we’
I like this phrasing. @petedejoy WDYT?

2020-09-24 15:56 UTC, sunkickr commented on guides/airflow-vs-oozie.md
> +At a high level, Airflow leverages the increasingly standardized use of Python to allow you to create extremely complex workflows via a commonly understood programming language, while Oozie is optimi
I'll make these changes

2020-09-24 16:07 UTC, sunkickr commented on guides/airflow-vs-oozie.md
> +As mentioned above, Airflow allows you to write your DAGs in Python while Oozie uses Java or XML. Per the [PYPL popularity index](http://pypl.github.io/PYPL.html), which is created by analyzing how o
"stack" should work

2020-09-25 14:21 UTC, paolaperaza approved these changes
Sweet - saw your changes, @sunkickr ! Looks great 😊

2020-09-25 14:23 UTC, petedejoy approved these changes
Bombs away- thanks @sunkickr!

2020-09-25 14:24 UTC, merged