Airflow vs Glue
astronomer/airflow-guides pull request #142
Opened 2020-09-24 21:47 UTC by sunkickr

Added note indicating when guide was last updated. Removed aggressive language and product endorsements. Updated outdated information, quotes, links, and airflow use cases. Added information on Glue crawlers. Added a conclusion section.

2020-09-28 13:38 UTC, paolaperaza reviewed
@sunkickr Thank you again for this! Made some copy suggestions - you are free to take what you like/leave whatever you think doesn't fit.

2020-09-28 13:38 UTC, paolaperaza commented on guides/airflow-vs-aws-glue.md
> +Airflow is designed to be a flexible workflow orchestrator; there really are no limits to how it can be used. Often, it is used to perform ETL jobs, but it can easily be used to [train ML models](htt
> Airflow is designed to be a flexible workflow orchestrator with no limits to how it can be used. While ETL is its most common use case, Airflow is also widely used to train ML models...

2020-09-28 13:38 UTC, paolaperaza commented on guides/airflow-vs-aws-glue.md
>  Because of this, it can be advantageous to still use Airflow to handle the data pipeline for all things OUTSIDE of AWS (e.g. pulling in records from an API and storing in s3) as this is not be a capa
I think you need a clearer connection here between the Glue quote and what you're trying to get at! I think if you cite users doing something it's more powerful than just telling the user it "can be done", you know what I mean?

I'd say:

> Precisely because of Glue's dependency on the AWS ecosystem, dozens of users choose to leverage both by using Airflow to handle data pipelines that interact with data _outside_ of AWS (e.g. pulling records from an API and storing it in S3), as AWS Glue isn't able to handle those jobs.

2020-09-28 13:38 UTC, paolaperaza commented on guides/airflow-vs-aws-glue.md
> +Airflow is an independent framework that executes native Python code without any other dependencies. This can then be extended to use other services, such as [Apache Spark](https://github.com/apache/
I'd make this sentence a bit more direct/actionable here:

> These operators make for flexible interaction with third-party APIs, databases, infrastructure layers, and data systems (including AWS).

2020-09-28 13:38 UTC, paolaperaza commented on guides/airflow-vs-aws-glue.md
> +Airflow is an independent framework that executes native Python code without any other dependencies. This can then be extended to use other services, such as [Apache Spark](https://github.com/apache/
What is the "this" in the second sentence? Airflow? If so -

> Given its extensibility, Airflow easily integrates with other powerful data tools, such as Apache Spark, via a robust library of officially supported and community contributed operators. These operators...

2020-09-28 13:38 UTC, paolaperaza commented on guides/airflow-vs-aws-glue.md
> +Glue uses Apache Spark as the foundation for it's ETL logic. There are some notable differences, however, that differentiate it from traditional Spark. The biggest of these differences include the us
*typo: it's > its

2020-09-28 13:38 UTC, paolaperaza commented on guides/airflow-vs-aws-glue.md
> +Glue uses Apache Spark as the foundation for it's ETL logic. There are some notable differences, however, that differentiate it from traditional Spark. The biggest of these differences include the us
Traditional > Vanilla?

> One of the biggest difference between the two is the use of a "dynamic frame" vs. the "data frame" in Spark that adds a number... (I think you can remove parentheses here!)

> By contract, Glue ETL scripts can be written in either PySpark or Scala

2020-09-28 13:38 UTC, paolaperaza commented on guides/airflow-vs-aws-glue.md
> +Airflow can use a number of different [executors](https://github.com/apache/incubator-airflow/tree/master/airflow/executors) to run tasks. These executors allow Airflow to use resources flexibly in r
> One of Airflow's biggest strengths is its built-in choice between 3 Executors, each built to execute tasks for a distinct use case. These Executors allow Airflow to consume resources in a way that's optimized to the needs of your workflows and extends its framework to support serverless task execution via the Kubernetes Executor, for exampele.

2020-09-28 13:38 UTC, paolaperaza commented on guides/airflow-vs-aws-glue.md
> +AWS Glue is notably serverless, meaning that it requires no specific resources to manage.
Would clarify a bit what "specific resources to manage" means -

> AWS Glue is notably serverless by default and does not require the user to decide how many resources need to be allocated at any given time.

2020-09-28 13:38 UTC, paolaperaza commented on guides/airflow-vs-aws-glue.md
> +Glue uses [crawlers](https://docs.aws.amazon.com/glue/latest/dg/add-crawler.html) to crawl through your AWS data stores(S3, DynamoDB, etc…) and populate the AWS Glue Data Catalog by looking for a par
> For the crawlers to work correctly, data often needs to be in a particular format. Given that limitation, it's common to leverage Apache Airflow to organize or transform data as needed in order for it to be efficiently crawled by Glue.

2020-09-28 13:38 UTC, paolaperaza commented on guides/airflow-vs-aws-glue.md
> + Airflow is an open-source project that's completely free to use if you’d like to spin it up and maintain the deployment. If you would like some help managing infrastructure,  efficiently scaling Air
> Airflow's status as a widely used open-source project makes it free to use as long as you're willing to manage your Airflow Deployment's resources. If you'd like help managing infrastructure at scale or are interested in Airflow training, send us a note and we'd be happy to give you a tour of our product features.

2020-09-29 12:28 UTC, sunkickr commented
Made suggested changes with a few tweaks.

2020-12-04 14:24 UTC, petedejoy requested changes

2020-12-07 13:31 UTC, sunkickr commented on guides/airflow-vs-aws-glue.md
>  ## Pricing
I agree that a pricing section isn't needed

2020-12-08 02:07 UTC, petedejoy approved these changes

2020-12-08 02:07 UTC, merged