Add talend integration guide
astronomer/airflow-guides pull request #150
Opened 2020-11-18 21:59 UTC by petedejoy

Converting the doc from notion to a markdown file compatible with our guides site.

2020-11-18 22:55 UTC, kentdanas reviewed
Added a couple of small comments but other than that looks great to me!

2020-11-19 17:37 UTC, petedejoy commented on guides/airflow-talend-integration.md
> +email_to = ["kenten@astronomer.io"]
Of course- good catch.

2020-11-19 17:37 UTC, petedejoy commented on guides/airflow-talend-integration.md
> +|Requirements|- Talend Studio license - Docker registry (can use Dockerhub if public is okay) - Kubernetes
Hmm, will push up a fix shortly.

2020-11-19 17:58 UTC, kentdanas approved these changes

2020-11-19 19:55 UTC, vparekh94 requested changes

2020-11-19 19:55 UTC, vparekh94 commented on guides/airflow-talend-integration.md
> +                image="davidkoenitzer/talendjob:random",
lets change this image name to be less specific

2020-11-19 19:55 UTC, vparekh94 commented on guides/airflow-talend-integration.md
> +## Executing Talend Jobs Using the Cloud API
Small thing, but can we move the CloudAPI piece to be first? I think more users would want to do things this way

2020-11-19 21:53 UTC, kentdanas commented on guides/airflow-talend-integration.md
> +![Executing%20Talend%20Jobs%20with%20Airflow%202a2beb0aae414e13b1fcf6db0c53e173/Screen_Shot_2020-10-28_at_3.37.35_PM.png](Executing%20Talend%20Jobs%20with%20Airflow%202a2beb0aae414e13b1fcf6db0c53e173
One more comment - the link for this screenshot is showing up as broken for me, but I wasn't sure how to fix it.

2020-11-20 01:40 UTC, merged

2020-11-20 09:05 UTC, mik-laj commented on guides/airflow-talend-integration.md
> +- Combining Talend and Airflow allows you to use both tools for what they're good for. If Talend works particularly well for one use case and python for another, you can do both and still have a one-
I think Python should be capitalized.

```diff
-- Combining Talend and Airflow allows you to use both tools for what they're good for. If Talend works particularly well for one use case and python for another, you can do both and still have a one-stop-shop for orchestration, monitoring, logs, etc. with Airflow and Astronomer
+- Combining Talend and Airflow allows you to use both tools for what they're good for. If Talend works particularly well for one use case and Python for another, you can do both and still have a one-stop-shop for orchestration, monitoring, logs, etc. with Airflow and Astronomer
```

2020-11-20 18:01 UTC, petedejoy commented on guides/airflow-talend-integration.md
> +- Combining Talend and Airflow allows you to use both tools for what they're good for. If Talend works particularly well for one use case and python for another, you can do both and still have a one-
Thanks Kamil- working on getting that change in here. Appreciate you helping out! https://github.com/astronomer/airflow-guides/pull/151