Airflow + SQL tutorial
astronomer/airflow-guides pull request #157
Opened 2020-12-08 00:50 UTC by kentdanas

2020-12-08 02:33 UTC, petedejoy requested changes
This looks really great @kentdanas! Just a few small things and then we can get this merged.

2020-12-08 02:33 UTC, petedejoy commented on guides/airflow-sql-tutorial.md
> +description: "Executing queries, loading data, and more, from your Apache Airflow DAGs."
These descriptions are what render on the actual webpage cards at astronomer.io/guides, so let's try to make them as descriptive as possible. In this case, let's change `and more` to be a bit more specific.

2020-12-08 02:33 UTC, petedejoy commented on guides/airflow-sql-tutorial.md
> +> Note: All code in this guide can be found in [this Github repo](https://github.com/astronomer/airflow-sql-tutorial).
Let's put this above the `Overview` section so it displays at the top of the guide page.

2020-12-08 02:33 UTC, petedejoy commented on guides/airflow-sql-tutorial.md
> +Executing SQL queries is one of the most common use cases for data pipelines. Whether you're extracting and loading data, calling a stored procedure, or executing a complex query for a report, Airflo
`relatively simple code`->`just a few lines of boilerplate code`. Want to highlight the simplicity of experience here.

2020-12-08 02:33 UTC, petedejoy commented on guides/airflow-sql-tutorial.md
> +Remember that Airflow is primarily an orchestrator, not a transformation framework. While you have the full power of Python in your DAG, best practice is to offload as much of your transformation log
`source and destination systems`-->`third party transformation frameworks` because dbt etc.

2020-12-08 02:33 UTC, petedejoy commented on guides/airflow-sql-tutorial.md
> +In this first example, we use a DAG to execute two simple queries which are dependent on each other other. To do so we use the SnowflakeOperator, which is documented [here](https://airflow.apache.org
`two simple interdependent queries`

2020-12-08 02:33 UTC, petedejoy commented on guides/airflow-sql-tutorial.md
> +In this first example, we use a DAG to execute two simple queries which are dependent on each other other. To do so we use the SnowflakeOperator, which is documented [here](https://airflow.apache.org
Also, would just link the `SnowflakeOperator` text instead of appending the extra `which is documented [here]`

2020-12-08 02:33 UTC, petedejoy commented on guides/airflow-sql-tutorial.md
> +With those basic concepts in mind, we'll show a few examples of common SQL use cases. For this tutorial we will use Snowflake, but note that the concepts shown can be adapted for other databases.
Link to [Snowflake]

2020-12-08 02:33 UTC, petedejoy commented on guides/airflow-sql-tutorial.md
> +Finally, we need to set up a connection to Snowflake. There are a few ways to manage connections using Astronomer, including [IAM roles](https://www.astronomer.io/docs/enterprise/v0.16/customize-airf
You can link to `/docs/enterprise/stable/doc-name` here; we have some magic baked into the website that automatically redirects `stable` to the latest stable release available to enterprise customers.

2020-12-08 02:33 UTC, petedejoy commented on guides/airflow-sql-tutorial.md
> +We use the S3toSnowflakeTransferOperator to limit the code we have to write. You can find the code for this operator [here](https://github.com/apache/airflow/blob/master/airflow/providers/snowflake/t
Just link [S3toSnowflakeTransferOperator] directly instead of adding the `You can find the code...`

2020-12-08 02:33 UTC, petedejoy commented on guides/airflow-sql-tutorial.md
> +First, we create a DAG that pulls COVID data from an API endpoint for California, Colorado, Washington, and Oregon, saves the data to comma-separated values (CSVs) on S3, and loads each of those CSVs
Can link https://covidtracking.com/data/api here. Both pumped and sad that this DAG is still relevant since its inception in June @vparekh94

2020-12-08 17:03 UTC, kentdanas commented
@petedejoy thanks for your review! I think I got all of your requested changes. Let me know if you see anything else!

2020-12-09 03:23 UTC, petedejoy approved these changes

2020-12-09 03:24 UTC, merged