Azure Container Instances + Airflow guide
astronomer/airflow-guides pull request #177
Opened 2020-12-21 22:18 UTC by kentdanas

Added guide on using the AzureContainerInstances Operator to do container stuff on Azure with Airflow. Adding @jwitz for tech writing review.

2020-12-22 21:34 UTC, jwitz requested changes
Overall looks really good @kentdanas ! Only uncommitable suggestions I made were to:

* Link out to more Microsoft docs when possible
* Standardize use of "ACI" to refer to the service, "Azure container instance" to refer to the actual instances
* Moving the note from the beginning of the document

2020-12-22 21:34 UTC, jwitz commented on guides/airflow-azure-container-instances.md
> +There are multiple ways to work with containers with Airflow on Azure, each of which could be the right fit from your use case. The most flexible and scalable method would be to the [KubernetesPodOpe
```suggestion
There are multiple ways to manage containers with Airflow on Azure. The most flexible and scalable method is to use the [KubernetesPodOperator](https://airflow.apache.org/docs/apache-airflow/stable/kubernetes.html). This lets you run any container as a Kubernetes pod, which means you can pass in resource requests and other native Kubernetes parameters. Using this operator requires an [AKS](https://azure.microsoft.com/en-us/services/kubernetes-service/) cluster (or a hand-rolled Kubernetes cluster).
```

2020-12-22 21:34 UTC, jwitz commented on guides/airflow-azure-container-instances.md
> +There are multiple ways to work with containers with Airflow on Azure, each of which could be the right fit from your use case. The most flexible and scalable method would be to the [KubernetesPodOpe
`you can pass in resource requests and other native Kubernetes parameters.` To where? The DAG?

2020-12-22 21:34 UTC, jwitz commented on guides/airflow-azure-container-instances.md
> +- It allows you to run containers in different regions
```suggestion
- You can run containers in different regions
```

2020-12-22 21:34 UTC, jwitz commented on guides/airflow-azure-container-instances.md
> +- It requires very little setup, and is easy to use
```suggestion
- It's easy to use and requires little setup
```

2020-12-22 21:34 UTC, jwitz commented on guides/airflow-azure-container-instances.md
> +- It is typically the cheapest; since no virtual machines or higher-level services are required, **you only pay for the memory and CPU used by your container group while it is active.**
```suggestion
- It's typically the cheapest; since no virtual machines or higher-level services are required, **you only pay for the memory and CPU used by your container group while it is active**
```

2020-12-22 21:34 UTC, jwitz commented on guides/airflow-azure-container-instances.md
> +With this in mind, we would recommend using ACI with the AzureContainerInstancesOperator for testing or for light weight tasks that don't require scaling. For heavy production workloads, we would rec
```suggestion
With these points in mind, we recommend using ACI with the AzureContainerInstancesOperator for testing or lightweight tasks that don't require scaling. For heavy production workloads, we recommend sticking with AKS and the KubernetesPodOperator.
```

2020-12-22 21:34 UTC, jwitz commented on guides/airflow-azure-container-instances.md
> +Using Airflow to create and run an ACI is straight forward. First, identify the Azure resource group you want to create the ACI in (or create a new one); then ensure your Azure instance has a service
```suggestion
Using Airflow to create and run an ACI is straightforward: You first identify the Azure resource group you want to create the ACI in (or create a new one), then ensure your Azure instance has a service principle with write access over that resource group. For more information on setting this up, refer to the [Azure documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal).
```

2020-12-22 21:34 UTC, jwitz commented on guides/airflow-azure-container-instances.md
> +Using Airflow to create and run an ACI is straight forward. First, identify the Azure resource group you want to create the ACI in (or create a new one); then ensure your Azure instance has a service
We introduce "ACI" as meaning a singular "Azure Container Instances" service, but then refer to it here as "an ACI". Should we be saying "run an Azure container instance" instead of "Run an ACI"? This is how Microsoft refers to it themselves: https://docs.microsoft.com/en-us/azure/container-instances/container-instances-quickstart

2020-12-22 21:34 UTC, jwitz commented on guides/airflow-azure-container-instances.md
> +Next, create an Airflow connection with the type `Azure Container Instance`, and fill it out with your Client ID as the login, Client Secret as the password, and Tenant ID and Subscription ID in the
```suggestion
Next, create an Airflow connection with the type `Azure Container Instance`. Specify your Client ID in the Login field, Client Secret in the Password field, and Tenant and Subscription IDs in the Extras field as json. It should look something like this:
```

2020-12-22 21:34 UTC, jwitz commented on guides/airflow-azure-container-instances.md
> +Next, create an Airflow connection with the type `Azure Container Instance`, and fill it out with your Client ID as the login, Client Secret as the password, and Tenant ID and Subscription ID in the
Assuming these are all fields, feel free to ignore this if they're not!

2020-12-22 21:34 UTC, jwitz commented on guides/airflow-azure-container-instances.md
> +Next, define a DAG using the AzureContainerInstancesOperator:
```suggestion
Lastly, define a DAG using the AzureContainerInstancesOperator:
```

2020-12-22 21:34 UTC, jwitz commented on guides/airflow-azure-container-instances.md
> +- **ci_conn_id:** the connection ID for the connection we created above
```suggestion
- **ci_conn_id:** The connection ID for the Airflow connection we created above
```

2020-12-22 21:34 UTC, jwitz commented on guides/airflow-azure-container-instances.md
> +- **registry_conn_id:** the connection ID to connect to a registry. In this case we used DockerHub, which is public and does not require credentials, so we pass in `None`
```suggestion
- **registry_conn_id:** The connection ID to connect to a registry. In this case we use DockerHub, which is public and does not require credentials, so we pass in `None`
```

2020-12-22 21:34 UTC, jwitz commented on guides/airflow-azure-container-instances.md
> +- **resource_group:** our Azure resource group
```suggestion
- **resource_group:** Our Azure resource group
```

2020-12-22 21:34 UTC, jwitz commented on guides/airflow-azure-container-instances.md
> +- **name:** the name we want to give our ACI. Note that this must be unique within the resource group
```suggestion
- **name:** The name we want to give our ACI. Note that this must be unique within the resource group
```

2020-12-22 21:34 UTC, jwitz commented on guides/airflow-azure-container-instances.md
> +- **image:** the docker image we want to use for the container. In this case we use a simple Hello World example from Docker
```suggestion
- **image:** The Docker image we want to use for the container. In this case we use a simple Hello World example from Docker
```

2020-12-22 21:34 UTC, jwitz commented on guides/airflow-azure-container-instances.md
> +- **region:** the Azure region we want our ACI deployed to
```suggestion
- **region:** The Azure region we want our ACI deployed to
```
"Azure container instace" instead of "ACI"?

2020-12-22 21:34 UTC, jwitz commented on guides/airflow-azure-container-instances.md
> +- **CPU:** the number of CPUs to allocate to the container. In this case we have used the default minimum for example. For more information on allocating CPU and memory, see this [link](https://docs.
```suggestion
- **CPU:** The number of CPUs to allocate to the container. In this example we use the default minimum. For more information on allocating CPUs and memory, refer to the [Azure documentation](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-faq).
```

2020-12-22 21:34 UTC, jwitz commented on guides/airflow-azure-container-instances.md
> +- **memory_in_gb**: the amount of memory to allocate to the container. In this case we have used the default minimum for example.
```suggestion
- **memory_in_gb**: The amount of memory to allocate to the container. In example we use the default minimum.
```

2020-12-22 21:34 UTC, jwitz commented on guides/airflow-azure-container-instances.md
> +- **fail_if_exists:** whether we want the the operator to raise an exception if the container group already exists (defaults to True). If set to False and the container group name already exists with
```suggestion
- **fail_if_exists:** Whether we want the the operator to raise an exception if the container group already exists (default value is True). If it's set to False and the container group name already exists within the given resource group, the operator will attempt to update the container group based on the other parameters before running and terminating upon completion
```

2020-12-22 21:34 UTC, jwitz commented on guides/airflow-azure-container-instances.md
> +Note that you can also provide the operator with other parameters such as environment variables, volumes, and a command as needed to run the container.
```suggestion
Note that you can also provide the operator with other parameters, such as environment variables or volumes, to run the container as needed.
```
Sorry the "a command" was bugging me - feel free to keep it in if it truly is only one command you can add!

2020-12-22 21:34 UTC, jwitz commented on guides/airflow-azure-container-instances.md
> +Now if we run this DAG, an ACI will spin up, run the container with the Hello World image, and then spin down. If we look at the Airflow task log, we see the printout from the container has propagate
```suggestion
If we run this DAG, an ACI will spin up, run the container with the Hello World image, and spin down. If we look at the Airflow task log, we see the printout from the container has propagated to the logs:
```

2020-12-23 17:48 UTC, kentdanas commented on guides/airflow-azure-container-instances.md
> +> Note: All code in this guide can be found in [this Github repo](https://github.com/astronomer/azure-operator-tutorials).
I'll defer to @petedejoy on that one since we have this as a pattern in some of our other guides. In some ways I think it's helpful to point out the code right up front, but I do understand your point.

2020-12-23 17:50 UTC, kentdanas commented on guides/airflow-azure-container-instances.md
> +- An Azure account with a resource group created
I would expect them to be familiar with these concepts since the assumption is that this would be used by people who are already using Azure. But, definitely can't hurt to have more msft docs linked; I'll add some.

2020-12-23 17:50 UTC, kentdanas commented on guides/airflow-azure-container-instances.md
> +There are multiple ways to work with containers with Airflow on Azure, each of which could be the right fit from your use case. The most flexible and scalable method would be to the [KubernetesPodOpe
To the operator

2020-12-23 17:52 UTC, kentdanas commented on guides/airflow-azure-container-instances.md
> +Using Airflow to create and run an ACI is straight forward. First, identify the Azure resource group you want to create the ACI in (or create a new one); then ensure your Azure instance has a service
Yep good call, I'll update

2020-12-23 17:57 UTC, kentdanas commented on guides/airflow-azure-container-instances.md
> +Note that you can also provide the operator with other parameters such as environment variables, volumes, and a command as needed to run the container.
The param you pass in is actually called "command". Agree it sounds weird, I just couldn't think of a different way to phrase it. Running a container with a command is a pretty common use case so thought it was worth calling out.

2020-12-24 00:14 UTC, jwitz approved these changes
Looks good, thanks for writing this @kentdanas ! Excited to read it once it's published.

2021-01-15 14:32 UTC, merged