Dynamic dags update
astronomer/airflow-guides pull request #202
Opened 2021-04-30 15:47 UTC by kentdanas

@jwitz @vparekh94 would love your review on this one. For context, this is an existing guide that was due for an update. I made quite a few changes to the existing content (added an overview, supporting github repo, more context around the examples, pros and cons of the methods presented), and also added a few new methods, plus a section on scalability. Let me know if your thoughts :)

2021-05-03 21:01 UTC, jwitz requested changes
Great updates here @kentdanas, mostly minor wording changes and some small questions throughout. I'll take another pass after you get a chance to read through my suggestions.

2021-05-03 22:35 UTC, kentdanas commented on guides/dynamically-generating-dags.md
> +- Since a DAG file isn't actually being created, your visibility into the code behind any specific DAG is limited.
The `Code` tab in Airflow will only show you the code that was parsed to create that DAG, so in this case, only the script that dynamically created it. With this method you aren't actually creating the DAG code anywhere that is persisted.

2021-05-03 22:37 UTC, kentdanas commented on guides/dynamically-generating-dags.md
> +### Create_DAG Method
Yeah I struggled with how to present this. Essentially this section defines the function that dynamically generates DAGs, and the sections below show different examples of how to call that function based on different input parameters. I'm fine adding `Example` to the title, but also open to other ideas if you have any.

2021-05-03 22:38 UTC, kentdanas commented on guides/dynamically-generating-dags.md
> +With the code above, the input parameters can come from any source that the Python script can access. For this first example, we set a simple loop (`range(1, 4)`) to generate these unique parameters
Yes

2021-05-03 22:38 UTC, kentdanas commented on guides/dynamically-generating-dags.md
>  ![title](https://assets.astronomer.io/website/img/guides/hello_world_1_thru_10.png)
Oh thanks, I didn't even notice that!

2021-05-03 22:42 UTC, kentdanas commented
> Great updates here @kentdanas, mostly minor wording changes and some small questions throughout. I'll take another pass after you get a chance to read through my suggestions.

Thanks @jwitz! I accepted your suggestions and I think answered all your questions. Let me know if you want to discuss anything else.

2021-05-04 19:39 UTC, jwitz approved these changes
Found one minor typo, but otherwise looks good to me!

2021-05-04 19:39 UTC, jwitz commented on guides/dynamically-generating-dags.md
> +If we look at the scheduler logs, we can see this variable was pulled into the DAG and, and 15 DAGs were added to the DagBag based on the its value.
```suggestion
If we look at the scheduler logs, we can see this variable was pulled into the DAG and, and 15 DAGs were added to the DagBag based on its value.
```

2021-05-05 15:36 UTC, vparekh94 approved these changes

2021-05-05 15:36 UTC, merged