Task groups guide
astronomer/airflow-guides pull request #205
Opened 2021-05-07 16:25 UTC by mag3141592

2021-05-10 21:55 UTC, kaxil commented on guides/task-groups.md
> +    from airflow.utils.task_group import TaskGroup
```suggestion
from airflow.utils.task_group import TaskGroup
```

2021-05-10 21:56 UTC, kaxil commented on guides/task-groups.md
> +**Note:** When your task is within a task group, your callable task_id will be the task_id prefixed with the group_id (i.e. group_id.task_id). This ensures the uniqueness of the task_id across the DA
```suggestion
**Note:** When your task is within a task group, your callable `task_id` will be the `task_id` prefixed with the `group_id` (i.e. `group_id.task_id`). This ensures the uniqueness of the task_id across the DAG. This is important to remember when calling specific tasks like for XCOM passing or branching operator decisions. 
```

2021-05-10 21:57 UTC, kaxil approved these changes

2021-05-11 15:14 UTC, jwitz requested changes
Congrats on your first Airflow guide @mag3141592 ! I left some high level questions and suggestions for you throughout the doc. Most of my comments pertain to capturing the style, voice, and cadence of our other Airflow Guides. I'd recommend looking at some more recent ones for inspiration on where to take this.

Once you work through that feedback, I'll do a more thorough edit for grammar, wording, and formatting.

2021-05-11 15:14 UTC, jwitz commented on guides/task-groups.md
> +By default using a loop to generate your tasks groups, will put them in parallel. In cases where your tasks groups are dependent on elements of another task group then you'll want to run them sequent
I would add another paragraph explaining how the code below achieves this. Be explicit: "In the example below, we have a table with foreign keys, and we'd like to use task groups to process that table. (etc etc)"

2021-05-11 15:14 UTC, jwitz commented on guides/task-groups.md
> +SubDAGs are DAGs embedded in DAGs whereas Task Groups exist in your original DAG. Tasks Groups allow you to group and organize your tasks within your DAG's graph view, without the added complexity an
It's common in Overview sections to include a paragraph explaining what the guide will provide to the reader. You can see an example of it in [this guide](https://www.astronomer.io/guides/airflow-passing-data-between-tasks):

>There are a few methods you can use to implement data sharing between your Airflow tasks. In this guide, we'll walk through the two most commonly used methods, discuss when to use each, and show some example DAGs to demonstrate the implementation.

It would be great to have something similar here, just so readers know what to expect when diving in.

2021-05-14 21:31 UTC, mag3141592 commented on guides/task-groups.md
> +#### Dynamically Generating Task Groups
I was thinking of it as Creating Task Groups && Overview as one level, and the rest as ways of creating or manipulating them. But, I think it also makes sense for them all to be the same level.

2021-05-18 08:28 UTC, mag3141592 commented on guides/task-groups.md
> +![Nested Task Groups](https://assets2.astronomer.io/main/guides/task-groups/nested_task_groups.png)
I don't know of any at the moment.

2021-05-19 00:39 UTC, jwitz approved these changes
This is a great improvement from when I last looked @mag3141592! I love all of the new examples and context you provided for the code, especially for the more complex examples. 

Most of my suggestions are straightforward wording changes, so I'm preemptively approving this. But if you find that some of my suggestions (especially for describing what's going on in the code the code) were technically inaccurate or otherwise need improvement, let's workshop those together before merging this.

2021-05-19 00:39 UTC, jwitz commented on guides/task-groups.md
> +> **Note:** When your task is within a task group, your callable `task_id` will be the `task_id` prefixed with the `group_id` (i.e. `group_id.task_id`). This ensures the uniqueness of the task_id acr
```suggestion
> **Note:** When your task is within a task group, your callable `task_id` will be the `task_id` prefixed with the `group_id` (i.e. `group_id.task_id`). This ensures the uniqueness of the task_id across the DAG. This is important to remember when calling specific tasks with XCOM passing or branching operator decisions.
```

2021-05-19 00:39 UTC, jwitz commented on guides/task-groups.md
> +Like tasks and [DAGs](https://www.astronomer.io/guides/dynamically-generating-dags), tasks groups can be dynamically generated to make use of patterns within your code. In an ETL DAG, you may call di
```suggestion
[Just like with DAGs](https://www.astronomer.io/guides/dynamically-generating-dags), Task Groups can be dynamically generated to make use of patterns within your code. In an ETL DAG, you might have have similar downstream tasks that can be processed independently, such as when you need to call different API endpoints for data that ends up in the same table. For this use case, we can dynamically generate Task Groups by API endpoint. Just like manually written Task Groups, generated Task Groups can be drilled into from the Airflow UI to see specific tasks. 

In the code below, we use iteration to create multiple Task Groups. While the tasks and dependencies remain the same across Task Groups, we can change which parameters are passed in to each Task Group by iterating the `group_id`:
```
Tried to reword this to make it more clear based on what my understanding is here, feel free to modify as needed if I got any details wrong!

2021-05-19 00:39 UTC, jwitz commented on guides/task-groups.md
> +This shows the expanded view of the task groups we generated above.
```suggestion
This image shows the expanded view of the task groups we generated above:
```

2021-05-19 00:39 UTC, jwitz commented on guides/task-groups.md
> +By default, using a loop to generate your task groups will put them in parallel. If your tasks groups are dependent on elements of another task group, you'll want to run them sequentially. For exampl
```suggestion
By default, using a loop to generate your task groups will put them in parallel. If your tasks groups are dependent on elements of another task group, you'll want to run them sequentially. For example, when loading tables with foreign keys, your primary table records need to exist before you can load your foreign table.
```

2021-05-19 00:39 UTC, jwitz commented on guides/task-groups.md
> +In the example below, our group 3 that we're dynamically generating has foreign keys to both group 1 and group 2 so we'll want to process it last. We create an empty list and append our task group ai
```suggestion
In the example below, our third dynamically generated Task Group requires foreign keys from both our first and second dynamically generated Task Groups, so we'll want to process it last. To do this, we'll create an empty list and append our Task Group objects as they are generated. Using this list, we can reference the Task Groups and define their dependencies to each other:
```

2021-05-19 00:39 UTC, jwitz commented on guides/task-groups.md
> +This shows the task group dependencies.
```suggestion
The following screenshot shows how these Task Groups appear in the Airflow UI:
```

2021-05-19 00:39 UTC, jwitz commented on guides/task-groups.md
> +In the above example, we added an additional task to group 1 based on our `group_id`. This was to demonstrate that even though we're dynamically creating task groups and tasks to take advantage of pa
```suggestion
In the above example, we added an additional task to `group1` based on our `group_id`. This was to demonstrate that even though we're dynamically creating Task Groups to take advantage of patterns, we can still introduce variations to the pattern while avoiding code redundancies from building each task group definition manually.
```

2021-05-19 00:39 UTC, jwitz commented on guides/task-groups.md
> +## Conditioning on Task Groups
```suggestion
### Conditioning on Task Groups
```
Sorry, I know I said to make these all `h2` but I didn't realize this was dependent on the previous example 😬

2021-05-19 00:39 UTC, jwitz commented on guides/task-groups.md
> +This shows the expanded view of the nested task groups we generated above.
```suggestion
The following screenshot shows the expanded view of the nested Task Groups in the Airflow UI:
```

2021-05-19 00:39 UTC, jwitz commented on guides/task-groups.md
> +For additional complexity, you can nest task groups. Building on our previous ETL example, when calling API endpoints we may need to process new records for each endpoint before we can process update
```suggestion
For additional complexity, you can nest Task Groups. Building on our previous ETL example, when calling API endpoints we may need to process new records for each endpoint before we can process updates to them.
```

2021-05-19 00:39 UTC, jwitz commented on guides/task-groups.md
> +In the code below, our top level task groups represents our new and updated record processing, while the nested task group represents our API endpoint processing.
```suggestion
In the following code, our top-level Task Groups represent our new and updated record processing, while the nested Task Groups represent our API endpoint processing:
```

2021-05-19 00:39 UTC, jwitz commented on guides/task-groups.md
> +Task groups are a dynamic and scalable UI grouping concept that solve for the functional and performance issues of SubDAGs.
```suggestion
Task Groups are a dynamic and scalable UI grouping concept that eliminate the functional and performance issues of SubDAGs. 
```

2021-05-19 00:39 UTC, jwitz commented on guides/task-groups.md
> +Ultimately task groups give you the flexibility to group and organize your tasks in a number of ways, to help guide your usage of them think about:
```suggestion
Ultimately, Task Groups give you the flexibility to group and organize your tasks in a number of ways. To help guide your implementation of Task Groups, think about:
```

2021-05-19 00:39 UTC, jwitz commented on guides/task-groups.md
> +- What patterns exist in your DAG?
```suggestion
- What patterns exist in your DAGs?
```

2021-05-19 00:39 UTC, jwitz commented on guides/task-groups.md
> +Unlike SubDAGs, [Task Groups](https://airflow.apache.org/docs/apache-airflow/stable/concepts.html#taskgroup) are just a UI grouping concept; allowing you to group and organize your tasks within your
It seems like the current usage of this term in the Airflow community uses capitalization, so I'm going to be consistent and capitalize Task Groups throughout the guide.

2021-05-19 05:41 UTC, mag3141592 commented on guides/task-groups.md
> +## Conditioning on Task Groups
That makes sense, yeah I added in this section after the last review when I realized I did a thing in my example without ever addressing it.

2021-05-19 17:28 UTC, jwitz commented on guides/task-groups.md
> +[Just like with DAGs](https://www.astronomer.io/guides/dynamically-generating-dags), Task Groups can be dynamically generated to make use of patterns within your code. In an ETL DAG, you might have h
```suggestion
[Just like with DAGs](https://www.astronomer.io/guides/dynamically-generating-dags), Task Groups can be dynamically generated to make use of patterns within your code. In an ETL DAG, you might have similar downstream tasks that can be processed independently, such as when you call different API endpoints for data that needs to be processed and stored in the same way. For this use case, we can dynamically generate Task Groups by API endpoint. Just like with manually written Task Groups, generated Task Groups can be drilled into from the Airflow UI to see specific tasks. 
```

2021-05-19 19:15 UTC, merged