Update DAG writing best practices guide
astronomer/airflow-guides pull request #207
Opened 2021-05-13 17:11 UTC by kentdanas

Hey @jwitz! Did a pretty major overhaul of this guide (one of our more popular ones). Would love if you could work your magic on it. Thank you as always!!!

2021-05-18 19:50 UTC, jwitz requested changes
Sorry this took a minute @kentdanas but hopefully some of the suggestions I make here are useful! I'll admit that some of my questions stem from a lack of actual Python/ DAG authorship, but my guess is that others reading this guide will be coming from a similar place.

2021-05-18 19:50 UTC, jwitz commented on guides/dag-best-practices.md
> +Instead, you would want to keep that SQL code in a separate file (`covid_state_query.sql` below), and call it into your DAG like this:
```suggestion
To avoid that SQL code running on every Scheduler heartbeat, you would want to keep it in a separate file and call it into your DAG. In the following example, we call in a file named `covid_state_query.sql` into our PostgresOperator instantiation, which embodies the best practice:
```

2021-05-18 19:50 UTC, jwitz commented on guides/dag-best-practices.md
> +Try to treat your DAG file like a config file and leave all the heavy lifting for hooks and operators. If your DAGs need to access additional code such as a SQL script or a Python function, keep that
In general, I was confused in this section when trying to understand the difference between the DAG, the DAG instantiation, the DAG file, and the DAG run. I think the instantiation is the most useful way to understand this best practice, so maybe focus on it by saying something like "All of the heavy lifting should occur only within your DAG and Operator instantiations."

2021-05-18 19:50 UTC, jwitz commented on guides/dag-best-practices.md
> +In Airflow, task dependencies can be set multiple ways. You can use `set_upstream()` and `set_downstream()` functions, or use `<<` or `>>` operators. Which method you use is a matter of personal pref
```suggestion
In Airflow, task dependencies can be set multiple ways. You can use `set_upstream()` and `set_downstream()` functions, or you can use `<<` and `>>` operators. Which method you use is a matter of personal preference, but for readability it's best practice to choose one method and stick with it.
```

2021-05-18 19:50 UTC, jwitz commented on guides/dag-best-practices.md
> +The next category of best practices is to use Airflow as an orchestrator; this will allow you to make the most of Airflow as it was designed, and ensure it can scale to meet your needs. Sticking to t
```suggestion
The next category of best practices relates to using Airflow as what it was originally designed to be: an orchestrator. Using Airflow as an orchestrator makes it easier to scale and pull in the right tools based on your needs.
```
I wasn't sure what the second sentence originally meant, so I tried to frame it using positive verbs. As it was before, there was too many double-negatives.

2021-05-18 19:50 UTC, jwitz commented on guides/dag-best-practices.md
> +A good way to ensure you're using Airflow as it was designed is to make use of [provider packages](https://airflow.apache.org/docs/apache-airflow-providers/) to orchestrate jobs with other tools. One
```suggestion
One way you can use Airflow as an orchestrator is by making use of existing [provider packages](https://airflow.apache.org/docs/apache-airflow-providers/), which orchestrate jobs using third party tools. One of the best aspects of Airflow is its robust and active community, which has resulted in many integrations between Airflow and other tools in the data ecosystem. Wherever possible, it's best practice to make use of these integrations. This makes it easier for teams using existing tools to adopt Airflow, and it means you get to write less code since many existing hooks and operators have taken care of that for you.
```

2021-05-18 19:50 UTC, jwitz commented on guides/dag-best-practices.md
> +Airflow was not designed to be a processing framework. Since DAGs are written in Python, you have the power of Python behind you and it can be tempting to make use of data processing libraries like P
```suggestion
Conversely, Airflow was _not_ designed to be a processing framework. Since DAGs are written in Python, it can be tempting to make use of data processing libraries like Pandas. However, processing large amounts of data within your Airflow tasks does not scale and should only be used in cases where the data are limited in size. A better option for scalability is to offload any heavy duty processing to a framework like [Apache Spark](https://spark.apache.org/), then use Airflow to orchestrate those jobs.
```

2021-05-18 19:50 UTC, jwitz commented on guides/dag-best-practices.md
> +It can be tempting to write your DAGs so that they move data directly from your source to destination. It usually makes for less code and involves fewer pieces, but doing so removes your ability to r
```suggestion
Because it requires less code and fewer pieces, it can be tempting to write your DAGs to move data directly from your source to destination. However, this means you can't individually rerun the extract or load portions of the pipeline. By putting an intermediary storage layer such as S3 or SQL Staging tables in between your source and destination, you can separate the testing and rerunning of the extract and load.
```

2021-05-18 19:50 UTC, jwitz commented on guides/dag-best-practices.md
> +Depending on your data retention policy, you could modify the load logic and re-run the entire historical pipeline without having to re-run the extracts. This is also useful in situations where you n
```suggestion
Depending on your data retention policy, you could modify the load logic and rerun the entire historical pipeline without having to rerun the extracts. This is also useful in situations where you no longer have access to the source system (e.g. you hit an API limit).
```

2021-05-18 19:50 UTC, jwitz commented on guides/dag-best-practices.md
> +Whenever possible, look to implement an ELT (extract, load, transform) data pipeline pattern with your DAGs. This means that you should look to offload as much of the transformation logic to the sour
```suggestion
Whenever possible, look to implement an ELT (extract, load, transform) data pipeline pattern with your DAGs. This means that you should look to offload as much of the transformation logic to the source systems or the destinations systems as possible, which avoids using Airflow as a processing framework. Many modern data warehouse tools, such as [Snowflake](https://www.snowflake.com/), give you easy to access to compute to support the ELT framework, and are easily used in conjunction with Airflow.
```

2021-05-18 19:50 UTC, jwitz commented on guides/dag-best-practices.md
> +Having a consistent file structure for Airflow projects can help keep things organized and easy to adopt when working with Airflow both within teams and across teams. At Astronomer, we use:
```suggestion
Having a consistent file structure for Airflow projects keeps things organized and easy to adopt. At Astronomer, we use:
```

2021-05-18 19:50 UTC, jwitz commented on guides/dag-best-practices.md
> +Even if your code is perfect, failures happen. In a distributed environment where task containers are executed on shared hosts, it's possible for tasks to be killed off unexpectedly. When this happen
```suggestion
Even if your code is perfect, failures happen. In a distributed environment where task containers are executed on shared hosts, it's possible for tasks to be killed off unexpectedly. When this happens, you might see Airflow's logs mention a [zombie process](https://en.wikipedia.org/wiki/Zombie_process).
```

2021-05-18 19:50 UTC, jwitz commented on guides/dag-best-practices.md
> +Issues like this can be resolved by using task retries. Best practice is to set retries as a `default_arg` so they are applied at the DAG level, and get more granular for specific tasks only where ne
```suggestion
Issues like this can be resolved by using task retries. Best practice is to set retries as a `default_arg` so they are applied at the DAG level and get more granular for specific tasks only where necessary. A good range to try is ~2–4 retries.
```

2021-05-18 19:50 UTC, jwitz commented on guides/dag-best-practices.md
> +You should always use a static `start_date` with your DAGs. A dynamic start_date is misleading, and can cause failures when clearing out failed task instances and missing DAG runs.
This kind of sound like an idempotence issue?

2021-05-19 01:49 UTC, kentdanas commented on guides/dag-best-practices.md
> +[Idempotency](https://en.wikipedia.org/wiki/Idempotence) is the concept whereby an operation can be repeated multiple times without changing the result. A common example is a crosswalk button; no mat
Yep, you're right, it's at the DAG Run level. The DAG itself won't always produce the same results, because the data, time, etc. can change, but each **DAG Run** should always be idempotent. e.g. DAG Run A should always process data set A for date x/x/xxxx, and DAG Run B should always process data for data set b and date y/y/yyyy. Changed the wording a little bit, does that make more sense?

2021-05-19 01:50 UTC, kentdanas commented on guides/dag-best-practices.md
> +[Idempotency](https://en.wikipedia.org/wiki/Idempotence) is the concept whereby an operation can be repeated multiple times without changing the result. A common example is a crosswalk button; no mat
```suggestion
In the context of Airflow, a DAG is considered idempotent if every DAG Run generates the same results even when run multiple times. Designing idempotent DAGs decreases recovery time from failures and prevents data loss.
```

2021-05-19 02:02 UTC, kentdanas commented on guides/dag-best-practices.md
> +When breaking up your pipeline into individual tasks, ideally each task should be atomic. This means each task should be responsible for one operation that can be re-run independently of the others,
For your own info, you can re-run just part of a DAG in Airflow....BUT, that's not what we're talking about here (sorry if this is more confusing :) ). Atomicity is referring to the content of each task, not the content of the DAG or how all the tasks fit together. Another way of saying it is that a task is atomic when if one part of the task fails, the entire task fails, or if one part succeeds, the entire task succeeds. As a more practical example, say I have a DAG that grabs data from an API endpoint and then loads it into a database. If I designed this DAG as one task that did everything, it would not be atomic; if the API request was successful but the database load failed, one "part" of the task succeeded, but the task as a whole did not succeed. If I split the DAG into two tasks, then it would be atomic. In vague terms, I usually think of it as each task does a "single thing" as opposed to multiple things. Sometimes atomicity isn't possible, but it's good to strive for it. 

Does that help? I'll think about ways to re-word this better to make it more clear, I definitely struggle with articulating this one in a couple of sentences without just talking through an example.

2021-05-19 02:04 UTC, kentdanas commented on guides/dag-best-practices.md
> +The example above creates date variables that can be used by tasks by calling `datetime` package functions. If this code is in the DAG file, these functions will be executed on every scheduler heartb
Yep, it should be the same result for a particular DAG Run, not necessarily every time you "run" the DAG. (confusing talking about running the DAG and a DAG Run as two different things, but that is the Airflow terminology....). Tried to clarify that above.

2021-05-19 02:10 UTC, kentdanas commented on guides/dag-best-practices.md
> +Try to treat your DAG file like a config file and leave all the heavy lifting for hooks and operators. If your DAGs need to access additional code such as a SQL script or a Python function, keep that
The main point of the "heavy lifting" comment is that you should be using hooks and operators (even if you define them yourself) as the "meat" of the code, as opposed to writing a bunch of python in the DAG file. The hook and operator code would live in separate files, that are then referenced in the DAG file. So the DAG and operator instantiations (which are just calling Airflow's `DAG` function, and whatever operator functions) need to happen in the DAG file, but that's ideally _all_ you want happening in the DAG file.

2021-05-19 02:12 UTC, kentdanas commented on guides/dag-best-practices.md
> +The next category of best practices is to use Airflow as an orchestrator; this will allow you to make the most of Airflow as it was designed, and ensure it can scale to meet your needs. Sticking to t
Your re-write is perfect, thank you for fixing my nonsense :)

2021-05-19 02:15 UTC, kentdanas commented on guides/dag-best-practices.md
> +You should always use a static `start_date` with your DAGs. A dynamic start_date is misleading, and can cause failures when clearing out failed task instances and missing DAG runs.
It could be!n If any tasks in your DAG were based on the start date, or if you had DAG runs that were older than a new changed start date.

2021-05-19 02:17 UTC, kentdanas commented
All good, thanks @jwitz! Tried to answer your questions and clarify a few things. Let me know if that helps!

2021-05-19 15:05 UTC, jwitz commented on guides/dag-best-practices.md
> +[Idempotency](https://en.wikipedia.org/wiki/Idempotence) is the concept whereby an operation can be repeated multiple times without changing the result. A common example is a crosswalk button; no mat
New wording clears this up!

2021-05-19 15:13 UTC, jwitz commented on guides/dag-best-practices.md
> +When breaking up your pipeline into individual tasks, ideally each task should be atomic. This means each task should be responsible for one operation that can be re-run independently of the others,
I think an ETL pipeline is a useful example here. Maybe just a single sentence like "For example, in an ETL pipeline you would want your Extract, Transform, and Load operations covered by three separate tasks. Atomizing these tasks allows you to rerun each operation in the ETL independently, which supports idempotence."

2021-05-19 15:19 UTC, jwitz commented on guides/dag-best-practices.md
> +The example above creates date variables that can be used by tasks by calling `datetime` package functions. If this code is in the DAG file, these functions will be executed on every scheduler heartb
I see your clarification above, but I'm not seeing seeing the changes in this suggestion, were those committed?

2021-05-19 15:20 UTC, jwitz approved these changes
Left one minor suggestion with regards to atomized tasks and another comment about an existing suggestions, but otherwise looks great to me @kentdanas ! Quite the improvement on the original guide 🔥

2021-05-19 15:24 UTC, kentdanas commented on guides/dag-best-practices.md
> +The example above creates date variables that can be used by tasks by calling `datetime` package functions. If this code is in the DAG file, these functions will be executed on every scheduler heartb
Oh sorry, might have confused things here. When I said clarified above, I meant in the section above where we initially talked about idempotence. For this section was just going to commit your suggested changes, unless there was something else you think I should add?

2021-05-19 15:35 UTC, kentdanas commented on .spelling
>  _
```suggestion
default_airflow.cfg file
```

2021-05-19 15:36 UTC, kentdanas commented on .spelling
> +default_airflow.cfg file
```suggestion
default_airflow.cfg
```

2021-05-19 15:43 UTC, merged