Update Great Expectations Guide
astronomer/airflow-guides pull request #253
Opened 2021-08-24 19:57 UTC by denimalpaca

Restructure and begin rewrite on guide to make it in the new imperative, use-case-based style.

https://www.astronomer.io/guides/airflow-great-expectations

2021-09-02 22:33 UTC, jwitz requested changes
Just dropped some comments and suggestions here @denimalpaca, requesting changes on a few spots like the "Great Expectations Operator" section. Great to see some more use cases and DAGs in here!

2021-09-02 22:33 UTC, jwitz commented on guides/airflow-great-expectations.md
> +First, a user creates test suites, or “Expectation Suites”, using [Great Expectations methods](https://docs.greatexpectations.io/docs/reference/expectations/expectations/). These suites are usually s
Removed the new line because it doesn't feel like the right place to introduce this information. If this is important, I would move the explanation of the demo contents closer to the use case.

2021-09-02 22:33 UTC, jwitz commented on guides/airflow-great-expectations.md
> +The `GreatExpectationsOperator` provides a convenient method for loading an existing Expectation Suite and using it to validate a batch of data. You can point the operator to any location by setting
```suggestion
The `GreatExpectationsOperator` provides a convenient method for loading an existing Expectation Suite and using it to validate a batch of data. You can point the operator to any location by setting the `data_context_root_dir` parameter (more on that to follow). Our [demo repository](https://github.com/astronomer/airflow-data-quality-demo/) uses the following configuration:
```

2021-09-02 22:33 UTC, jwitz commented on guides/airflow-great-expectations.md
> +1. The `great_expectations` directory is accessible by your DAG, as it is loaded into Docker as part of the `include` directory. Ideally the `great_expectations` directory should be located in the sa
```suggestion
- The `great_expectations` directory is accessible by your DAG, as it is loaded into Docker as part of the `include` directory. Ideally, the `great_expectations` directory should be located in the same project as your DAG, but you can point the environment variable at any location.
```

2021-09-02 22:33 UTC, jwitz commented on guides/airflow-great-expectations.md
> +2. The Great Expectations provider is installed when you run `astro dev start`, as it is part of `requirements.txt`. Otherwise, install Great Expectations and the Great Expectations provider in your
```suggestion
- The Great Expectations provider is installed when you run `astro dev start`, as it is part of `requirements.txt`. Otherwise, install Great Expectations and the Great Expectations provider in your environment manually:
```

2021-09-02 22:33 UTC, jwitz commented on guides/airflow-great-expectations.md
>      pip install great_expectations airflow-provider-great-expectations
We start this list off as if it's a collection of configurations, but then we seemingly switch to telling the user how to start implementing the project. Can you announce one section for configuration and another section for user steps while making it clear which one is which?

2021-09-02 22:33 UTC, jwitz commented on guides/airflow-great-expectations.md
> +This means that the parameters you pass to the operator depend on how you would like to invoke Great Expectations validation. The example DAG below shows several different cases of using the operator
```suggestion
The method you use for invoking validation determines which parameters you should pass to the operator. The following example DAG shows how you would implement each of these methods in your code:
```

2021-09-02 22:33 UTC, jwitz commented on guides/airflow-great-expectations.md
> +For more information about possible parameters and examples, see the [README in the provider repository](https://github.com/great-expectations/airflow-provider-great-expectations), and the [example D
```suggestion
For more information about possible parameters and examples, see the [README in the provider repository](https://github.com/great-expectations/airflow-provider-great-expectations) and the [example DAG in the provider package](https://registry.astronomer.io/dags/example-great-expectations-dag).
```

2021-09-02 22:33 UTC, jwitz commented on guides/airflow-great-expectations.md
> +The [`GreatExpectationsBigQueryOperator`](https://registry.astronomer.io/providers/great-expectations/modules/greatexpectationsbigqueryoperator) allows you to run Great Expectation suites directly on
```suggestion
The [`GreatExpectationsBigQueryOperator`](https://registry.astronomer.io/providers/great-expectations/modules/greatexpectationsbigqueryoperator) allows you to run Great Expectation suites directly on tables in BigQuery or on a subset of data chosen by an SQL query. The test suites are stored in Google Cloud Storage, so the entire process can run in the cloud.
```

2021-09-02 22:33 UTC, jwitz commented on guides/airflow-great-expectations.md
> +Assuming you already have Airflow running in an Astronomer deployment in this directory, follow these steps to get the DAG working:
```suggestion
Assuming you already have Airflow running in an Astronomer deployment, follow these steps to run the example DAG:
```

2021-09-02 22:33 UTC, jwitz commented on guides/airflow-great-expectations.md
> +1. Under `Admin -> Connections` in the Airflow UI, add a new connection with `Conn ID` as `google_cloud_default`.
```suggestion
1. In the Airflow UI, go to **Admin** > **Connections** and add a new connection with `Conn ID` set to `google_cloud_default`.
```

2021-09-02 22:33 UTC, jwitz commented on guides/airflow-great-expectations.md
> +2. Set the connection type to `Google Cloud`; this connection comes with the Astronomer Airflow distribution.
```suggestion
2. Set the connection type to `Google Cloud`. This connection type comes with the Astronomer Airflow distribution.
```

2021-09-02 22:33 UTC, jwitz commented on guides/airflow-great-expectations.md
> +2. Set the connection type to `Google Cloud`; this connection comes with the Astronomer Airflow distribution.
I this Astronomer Core? Maybe worth it to link out to our downloads page for AC here.

2021-09-02 22:33 UTC, jwitz commented on guides/airflow-great-expectations.md
> +3. A GCP key associated with a service account that has access to BigQuery and Google Cloud Storage is needed. For more information generating a key, [follow the instructions in this guide](https://c
Let's create a new "Prerequisites" section to start with that includes:

- GCP key
- Astronomer Core Airflow distribution 

Then we can focus solely on adding the GCP key in this step.

It also doesn't seem like having an Airflow Deployment on Astronomer is necessary for these steps? We can include information on what to do if you have one, but I'd remove "Assuming you already have Airflow running in an Astronomer deployment"

2021-09-02 22:33 UTC, jwitz commented on guides/airflow-great-expectations.md
> +5. Scopes should be left blank, and filling the field in can result in token errors with Google Auth.
I would cut this step unless this is unexpected behavior. Even if it is, this is probably better off in a note

2021-09-02 22:33 UTC, jwitz commented on guides/airflow-great-expectations.md
> +![GCP Connection](https://assets2.astronomer.io/main/guides/great-expectations/gcp_connection.png)
Move this to before step 6? So they can confirm their setup before closing the UI and moving on to the env vars.

2021-09-02 22:33 UTC, jwitz commented on guides/airflow-great-expectations.md
> +With the connection to GCP set, the next step is creating and running the DAG. In the example below, the DAG performs all of the following:
```suggestion
With the connection to GCP set, the next step is creating and running the DAG. In the example below, the DAG:
```

2021-09-02 22:33 UTC, jwitz commented on guides/airflow-great-expectations.md
> +The above example DAG shows how Airflow can be used to orchestrate in-depth data quality checks with Great Expectations as part of a full ELT pipeline. A next step is to configure the Great Expectati
How does it show that? Can we get a line that's like "When we run this DAG, we'll see that X happens." or "If we try to run this DAG with faulty data, Y happens".

2021-09-02 22:33 UTC, jwitz commented on guides/airflow-great-expectations.md
> +The above example DAG shows how Airflow can be used to orchestrate in-depth data quality checks with Great Expectations as part of a full ELT pipeline. A next step is to configure the Great Expectati
Love the concluding sentence!

2021-09-07 17:17 UTC, denimalpaca commented on guides/airflow-great-expectations.md
> +First, a user creates test suites, or “Expectation Suites”, using [Great Expectations methods](https://docs.greatexpectations.io/docs/reference/expectations/expectations/). These suites are usually s
Makes sense. There is actually a line at the end of the section mentioning where the whole Great Expectations project can be found, anyway.

2021-09-07 17:21 UTC, denimalpaca commented on guides/airflow-great-expectations.md
> +2. The Great Expectations provider is installed when you run `astro dev start`, as it is part of `requirements.txt`. Otherwise, install Great Expectations and the Great Expectations provider in your
Are there specific times where we use a numbered list versus an unordered list?

2021-09-07 17:24 UTC, denimalpaca commented on guides/airflow-great-expectations.md
> +The [`GreatExpectationsBigQueryOperator`](https://registry.astronomer.io/providers/great-expectations/modules/greatexpectationsbigqueryoperator) allows you to run Great Expectation suites directly on
Ha! Guess you read it as "es-que-el" and I read it as "sequel".

2021-09-07 17:41 UTC, denimalpaca commented on guides/airflow-great-expectations.md
> +2. Set the connection type to `Google Cloud`; this connection comes with the Astronomer Airflow distribution.
I think it's just in the distribution that the Dockerfile uses. So not exactly sure what would be linked to here.

2021-09-07 17:43 UTC, denimalpaca commented on guides/airflow-great-expectations.md
> +3. A GCP key associated with a service account that has access to BigQuery and Google Cloud Storage is needed. For more information generating a key, [follow the instructions in this guide](https://c
Sounds good. Yes I think I got the "Airflow running in an Astronomer deployment" confused with just "Running an Astronomer distribution of Airflow with the CLI".

2021-09-07 17:43 UTC, denimalpaca commented on guides/airflow-great-expectations.md
> +5. Scopes should be left blank, and filling the field in can result in token errors with Google Auth.
I'd rather keep it as a note, because it can be a tricky issue to debug.

2021-09-14 15:25 UTC, jwitz approved these changes
Approving for after my last comments get addressed @denimalpaca ! They are higher level but I have full trust that you will implement them excellently. Feel free to tag me again for any last minute review.

2021-09-14 15:25 UTC, jwitz commented on guides/airflow-great-expectations.md
> +> Note: If you are running Airflow 2.0 and beyond, you will need to also change the value of `enable_xcom_pickling` to `true` in your airflow.cfg. If you are using an Astronomer project structure, ad
```suggestion
> Note: If you are running Airflow 2.0 and beyond, you will need to also change the value of `enable_xcom_pickling` to `true` in your airflow.cfg. If you are using an Astronomer project structure, add `ENV AIRFLOW__CORE__ENABLE_XCOM_PICKLING=True` to your Dockerfile. If you are working from the demo repository, this step has already been completed for you.
```

2021-09-14 15:25 UTC, jwitz commented on guides/airflow-great-expectations.md
> +## Use Case: Great Expectations Operator
Headers with no content in can look a bit awkward on our site, can we add a short introduction here like:

"Now that we've set up our system to work with Great Expectations, we can start exploring how to use it in our DAGs. In this first use case, we'll use the `GreatExpectationsOperator` to run an Expectation Suite."

2021-09-14 20:17 UTC, merged