Update templating guide
astronomer/airflow-guides pull request #256
Opened 2021-08-31 09:27 UTC by BasPH

Updated templating guide to include everything about templating. Also included content from https://github.com/astronomer/airflow-guides/pull/255, which can be closed if we merge this.

2021-08-31 19:30 UTC, kentdanas commented
@BasPH thanks for taking this on! I did a quick review for content and it looks great. Much more comprehensive than it was before, and no longer badly out of date :) 

My only comment content-wise would be I think it would be helpful to expand a bit on the first section (we usually have an #Overview) to give a preview of what is coming in the guide. Just a few sentences on what will be covered and why it would be helpful. You can check out some of our other recent guides for examples.

I also included @jwitz as a reviewer - he usually does a copy edit before we publish.

2021-08-31 20:58 UTC, BasPH commented
@kentdanas Added overview section

2021-09-01 02:15 UTC, kentdanas commented
> @kentdanas Added overview section

Looks great, thanks for adding that! Will let Jake do a copy edit and then should be good to go.

2021-09-02 17:38 UTC, jwitz requested changes
Awesome guide improvement here @BasPH, all of your examples and explanations were super clear and informative. Most of my comments are straightforward copy changes, but I also included some high level comments that I'm requesting changes on. 

Also, I noticed that much of the new copy includes manual line breaks to make it fit on the page. Our Markdown processor handles sizing paragraphs naturally, so could you go back through this PR and reformat the paragraphs to have line breaks only when starting a new paragraph? This will ensure that the text is correctly on both web and mobile screens.

2021-09-02 17:38 UTC, jwitz commented on guides/templating.md
> +`scripts/script.sh`.
```suggestion
Templating from files makes it easier to develop (especially when your scripts grow larger) because an IDE can apply language-specific syntax highlighting on the script. This wouldn't be possible if your script was defined as a big string in Airflow code.

By default, Airflow searches for `script.sh` relative to the directory the DAG file is defined in. So if your DAG is stored in `/path/to/dag.py` and your script is stored in `/path/to/scripts/script.sh`, you would set the value of `bash_command` to `scripts/script.sh`.
```

2021-09-02 17:38 UTC, jwitz commented on guides/templating.md
> +## Validating templates
```suggestion
## Validating Templates
```

2021-09-02 17:38 UTC, jwitz commented on guides/templating.md
> +Now you can store your Bash script in `/tmp` for Airflow to find it.
```suggestion
Now you can store your Bash script in `/tmp` and Airflow will find it.
```

2021-09-02 17:38 UTC, jwitz commented on guides/templating.md
> +The output of templates can be checked in both the Airflow UI and CLI. The advantage of the CLI is that you don't need
```suggestion
The output of templates can be checked in both the Airflow UI and CLI. One advantage of the CLI is that you don't need
```

2021-09-02 17:38 UTC, jwitz commented on guides/templating.md
> +task_id, and (dummy) execution_date will output something like this:
```suggestion
The Airflow CLI command `airflow tasks render` renders all templateable attributes of a given task. Given a `dag_id`, `task_id`, and dummy `execution_date`, the command outputs something like this:
```

2021-09-02 17:38 UTC, jwitz commented on guides/templating.md
> +For this to work, Airflow must have access to a metastore. You can quickly set up a local SQLite metastore for this:
```suggestion
For this command to work, Airflow must have access to a metastore. You can quickly set up a local SQLite metastore to achieve this:
```

2021-09-02 17:38 UTC, jwitz commented on guides/templating.md
> +Rendered button to see the result:
```suggestion
**Rendered** button to see the result:
```

2021-09-02 17:38 UTC, jwitz commented on guides/templating.md
> +Which shows the Rendered Template view and the output of the templated attributes:
```suggestion
Clicking this shows the Rendered Template view and the output of the templated attributes:
```

2021-09-02 17:38 UTC, jwitz commented on guides/templating.md
> +## Using custom functions and variables in templates
```suggestion
## Using Custom Functions and Variables in Templates
```

2021-09-02 17:38 UTC, jwitz commented on guides/templating.md
> +reasons (e.g. security), a Jinja environment is not the same as your Airflow runtime. You can view a Jinja environment
```suggestion
reasons such as security, a Jinja environment is not the same as your Airflow runtime. You can view a Jinja environment
```

2021-09-02 17:38 UTC, jwitz commented on guides/templating.md
> +For the full list of all available macros, refer to the documentation:
```suggestion
For the full list of all available macros, refer to the [Apache Airflow documentation](https://airflow.apache.org/docs/apache-airflow/stable/macros-ref.html#id1).
```

2021-09-02 17:38 UTC, jwitz commented on guides/templating.md
> +<https://airflow.apache.org/docs/apache-airflow/stable/macros-ref.html#id1>.
```suggestion
```

2021-09-02 17:38 UTC, jwitz commented on guides/templating.md
> +To use this inside a Jinja template, you can pass a dict to `user_defined_macros` on the DAG:
```suggestion
To use this inside a Jinja template, you can pass a dict to `user_defined_macros` in the DAG:
```

2021-09-02 17:38 UTC, jwitz commented on guides/templating.md
> +If you're familiar with filters in Jinja, it's also possible to inject those using `user_defined_filters`. It allows
```suggestion
It's also possible to inject Jinja [filters](https://jinja.palletsprojects.com/en/3.0.x/api/#jinja2.Environment.filters) using `user_defined_filters`. You can use filters to complete
```

2021-09-02 17:38 UTC, jwitz commented on guides/templating.md
> +functions to be used like pipe-operations in Bash. In this example it's a matter of preference since both will do the
```suggestion
pipe-operations in Bash. The following example completes the same work as the previous example, only this time using templates:
```

2021-09-02 17:38 UTC, jwitz commented on guides/templating.md
> +job:
```suggestion
```

2021-09-02 17:38 UTC, jwitz commented on guides/templating.md
> +Generally, filters are preferred for readability when multiple are used because it's more natural to read from left to
```suggestion
While they achieve the same result, we recommend using filters when you need to import multiple custom functions because the filter formatting improves the readability of your code. You can see this when comparing the two techniques side-to-side:
```

2021-09-02 17:38 UTC, jwitz commented on guides/templating.md
> +right (the result is the same though):
```suggestion
```

2021-09-02 17:38 UTC, jwitz commented on guides/templating.md
> +## Rendering native Python code
```suggestion
## Rendering Native Python Code
```

2021-09-02 17:38 UTC, jwitz commented on guides/templating.md
> +Say we would pass a list of values to this function by triggering a DAG with a config that holds some numbers:
```suggestion
Consider a scenario where you're passing a list of values to this function by triggering a DAG with a config that holds some numbers:
```

2021-09-02 17:38 UTC, jwitz commented on guides/templating.md
> +And trigger the DAG with the following JSON to the DAG run configuration:
```suggestion
We would trigger the DAG with the following JSON to the DAG run configuration:
```

2021-09-02 17:38 UTC, jwitz commented on guides/templating.md
> +The rendered value would be a string and since the `sum_numbers` function unpacks the given string it ends up trying to
```suggestion
The rendered value would be a string. Since the `sum_numbers` function unpacks the given string, it ends up trying to
```

2021-09-02 17:38 UTC, jwitz commented on guides/templating.md
> +add up every character in the string, which is:
```suggestion
add up every character in the string:
```

2021-09-02 17:38 UTC, jwitz commented on guides/templating.md
> +outputs strings, but we can configure a so-called [NativeEnvironment](https://jinja.palletsprojects.com/en/3.0.x/nativetypes/#jinja2.nativetypes.NativeEnvironment)
```suggestion
outputs strings, but we can configure a [NativeEnvironment](https://jinja.palletsprojects.com/en/3.0.x/nativetypes/#jinja2.nativetypes.NativeEnvironment)
```

2021-09-02 17:38 UTC, jwitz commented on guides/templating.md
> +which renders templates as native Python code. In Airflow 2.1.0 support for Jinja's NativeEnvironment was [added](https://github.com/apache/airflow/pull/14603)
```suggestion
which renders templates as native Python code. Support for Jinja's NativeEnvironment was added in [Airflow 2.1.0](https://github.com/apache/airflow/pull/14603)
```

2021-09-02 17:38 UTC, jwitz commented on guides/templating.md
> +via an argument `render_template_as_native_obj` on the DAG class. This argument takes a boolean value which determines
```suggestion
via the `render_template_as_native_obj` argyment on the DAG class. This argument takes a boolean value which determines
```

2021-09-02 17:38 UTC, jwitz commented on guides/templating.md
> +On a final note, the Jinja environment must be configured on the DAG-level. That means all tasks in a DAG render either
```suggestion
On a final note, the Jinja environment must be configured on the DAG-level. This means that all tasks in a DAG render either
```

2021-09-02 17:38 UTC, jwitz commented on guides/templating.md
> +To summarize, templating allows to give your tasks dynamic behaviour by evaluating expressions at runtime. There are
```suggestion
To summarize, you can use templating to give your tasks behaviour by evaluating expressions at runtime. There are
```

2021-09-02 17:38 UTC, jwitz commented on guides/templating.md
> +- For all Jinja templating features, refer to the [documentation](https://jinja.palletsprojects.com/en/3.0.x/)
```suggestion
- For all Jinja templating features, refer to the [Jinja documentation](https://jinja.palletsprojects.com/en/3.0.x/)
```

2021-09-03 09:36 UTC, BasPH commented
@jwitz thanks for the very thorough review! Changed the line breaks and processed all your feedback.

2021-09-03 15:10 UTC, jwitz approved these changes
Some small final comments, but otherwise looks great!

2021-09-03 15:10 UTC, jwitz commented on guides/templating.md
> +Templating in Airflow works exactly the same as templating with Jinja in Python: define your to-be-evaluated code between double curly braces, and the expression will be evaluated at runtime. As we s
```suggestion
Templating in Airflow works exactly the same as templating with Jinja in Python: define your to-be-evaluated code between double curly braces, and the expression will be evaluated at runtime. As we saw in the previous code snippet, `execution_date` is a variable available at runtime. 

Airflow includes many variables which can be used for templating. Some of the most used variables are:
```

2021-09-03 15:10 UTC, jwitz commented on guides/templating.md
> +If desired, additional "search paths" can be controlled at the DAG-level with the argument `template_searchpath`:
```suggestion
If desired, additional "search paths" can be controlled at the DAG-level with the `template_searchpath` argument:
```

2021-09-03 15:10 UTC, jwitz commented on guides/templating.md
> +For most templating, this will suffice. However, if any external systems (e.g. variable in production Airflow metastore) are reached in the templating logic, you must have connectivity to those syste
```suggestion
For most templating, this will suffice. However, if any external systems (e.g. a variable in your production Airflow metastore) are reached in the templating logic, you must have connectivity to those systems.
```

2021-09-03 15:10 UTC, jwitz commented on guides/templating.md
> +This is not going to work, so we must tell Jinja to return a native Python list instead of a string. Jinja supports this via _Environments_. The [default Jinja environment](https://jinja.palletsproje
```suggestion
This is not going to work, so we must tell Jinja to return a native Python list instead of a string. Jinja supports this via _Environments_. The [default Jinja environment](https://jinja.palletsprojects.com/en/3.0.x/api/#jinja2.Environment) outputs strings, but we can configure a [NativeEnvironment](https://jinja.palletsprojects.com/en/3.0.x/nativetypes/#jinja2.nativetypes.NativeEnvironment) which renders templates as native Python code. 

Support for Jinja's NativeEnvironment was added in [Airflow 2.1.0](https://github.com/apache/airflow/pull/14603) via the `render_template_as_native_obj` argument on the DAG class. This argument takes a boolean value which determines whether to render templates with Jinja's default Environment or NativeEnvironment. An example:
```

2021-09-07 17:43 UTC, kentdanas approved these changes

2021-09-07 17:45 UTC, kentdanas commented
@BasPH thanks for addressing all the comments, this looks great! Go ahead and merge when you're good with it :)

2021-09-08 08:16 UTC, merged