Managing dependencies update
astronomer/airflow-guides pull request #266
Opened 2021-09-08 21:18 UTC by kentdanas

@jwitz another week, another existing guide overhaul :) hit me with your comments!

Closes #249

2021-09-10 21:40 UTC, jwitz requested changes
Lots of great info in here @kentdanas , requesting changes on a few high level questions but overall looks great

2021-09-10 21:40 UTC, jwitz commented on guides/managing-dependencies.md
> +Which results in the following DAG:
```suggestion
This code results in the following DAG:
```

2021-09-10 21:40 UTC, jwitz commented on guides/managing-dependencies.md
> +Note that you cannot set dependencies between two lists (e.g. `[t0, t1] >> [t2, t3]` will throw an error). If you need to set parallel cross-dependencies in this manner, you can use Airflow's [`chain
```suggestion
What if we want to set multiple parallel cross-dependencies? Unfortunately, Airflow can't parse dependencies between two lists (e.g. `[t0, t1] >> [t2, t3]` throws an error). If you need to set dependencies in this manner, you can use Airflow's [`chain` function](https://github.com/apache/airflow/blob/main/airflow/models/baseoperator.py#L1650):
```

2021-09-10 21:40 UTC, jwitz commented on guides/managing-dependencies.md
> +Note that with the `chain` function any lists or tuples included must be the same length.
```suggestion
Note that with the `chain` function, any lists or tuples included must be of the same length.
```

2021-09-10 21:40 UTC, jwitz commented on guides/managing-dependencies.md
> +If you generate tasks dynamically in your DAG, you should also set dependencies dynamically to ensure they reflect any changes in the tasks. This is easy to accomplish: simply define the dependencies
```suggestion
If you [generate tasks dynamically](https://www.astronomer.io/guides/dynamically-generating-dags) in your DAG, you should also set dependencies dynamically to ensure that they reflect any changes in the tasks. This is easy to accomplish: simply define the dependencies within the context of the code used to dynamically create the tasks.
```

Appropriate to link out here?

2021-09-10 21:40 UTC, jwitz commented on guides/managing-dependencies.md
> +For example, below we generate a set of parallel dynamic tasks by looping through a list of endpoints. We define the dependencies within the loop, which means every `generate_file` task will be downs
```suggestion
For example, below we generate a set of parallel dynamic tasks by looping through a list of endpoints. We define the dependencies within the loop, which means every `generate_file` task is downstream of `start` and upstream of `send_email`.
```

2021-09-10 21:40 UTC, jwitz commented on guides/managing-dependencies.md
> +[Task groups](https://airflow.apache.org/docs/apache-airflow/stable/concepts/dags.html#taskgroups) are a UI grouping concept available in Airflow 2+ that can visually group tasks in the Airflow UI. F
```suggestion
[Task groups](https://airflow.apache.org/docs/apache-airflow/stable/concepts/dags.html#taskgroups) are a UI-based grouping concept available in Airflow 2.0+. For more information on task groups in general, including how to create them and when to use them, check out our [task groups guide](https://www.astronomer.io/guides/task-groups).
```

2021-09-10 21:40 UTC, jwitz commented on guides/managing-dependencies.md
> +When working with task groups, it is important to note that dependencies can be set both inside and outside the group. For example, in the DAG code below we have a start task, a task group with two d
```suggestion
When working with task groups, it is important to note that dependencies can be set both inside and outside of the group. For example, in the DAG code below we have a start task, a task group with two dependent tasks, and an end task that need to happen sequentially. The dependencies between the two tasks in the task group are set within the task group's context (`t1 >> t2`). The dependencies between the task group and the start/end tasks are set within the DAG's context (`t0 >> tg1 >> t3`).
```

2021-09-10 21:40 UTC, jwitz commented on guides/managing-dependencies.md
> +This code results in a DAG that looks like this:
```suggestion
This code results in the following DAG:
```

2021-09-10 21:40 UTC, jwitz commented on guides/managing-dependencies.md
> +For more examples of setting dependencies within different types of task groups, check out the guide linked above.
```suggestion
```

Would either link above or here, but not both.

2021-09-10 21:40 UTC, jwitz commented on guides/managing-dependencies.md
> +The [TaskFlow API](https://airflow.apache.org/docs/apache-airflow/stable/concepts/taskflow.html), available in Airflow 2+, provides an easy way to turn Python functions into Airflow tasks using the `
```suggestion
The [TaskFlow API](https://airflow.apache.org/docs/apache-airflow/stable/concepts/taskflow.html), available in Airflow 2.0+, provides an easy way to turn Python functions into Airflow tasks using the `@task` decorator. 
```

2021-09-10 21:40 UTC, jwitz commented on guides/managing-dependencies.md
> +If your DAG has only Python functions that are all defined with the decorator, setting dependencies is as easy as invoking the Python functions. For example, in the DAG below we have two dependent ta
```suggestion
If your DAG has only Python functions that are all defined with the decorator, setting dependencies is as easy as invoking the Python functions. For example, in the DAG below we have two dependent tasks, `get_testing_increases` and `analyze_testing_increases`. To set the dependencies, we invoke the function `analyze_testing_increases(get_testing_increase(state))`:
```

2021-09-10 21:40 UTC, jwitz commented on guides/managing-dependencies.md
> +In Airflow, when you set dependencies between tasks the default behavior is for a task to be run only when all upstream tasks have succeeded. However, you have many other options for when a task gets
```suggestion
When you set dependencies between tasks, Airflow's default behavior is to run a task only when all upstream tasks have succeeded. However, you can change this default behavior using [trigger rules](https://airflow.apache.org/docs/apache-airflow/stable/concepts/dags.html#concepts-trigger-rules).
```

2021-09-10 21:40 UTC, jwitz commented on guides/managing-dependencies.md
> +- **dummy:** dependencies are just for show, trigger at will
```suggestion
- **all_success:** (default) The task runs only when all upstream tasks have succeeded.
- **all_failed:** The task runs only when all upstream tasks are in a failed or upstream\_failed state.
- **all_done:** The task runs once all upstream tasks are done with their execution.
- **one_failed:** The task runs as soon as at least one upstream task has failed. 
- **one_success:** The task runs as soon as at least one upstream task has succeeded.
- **dummy:** Dependencies are just for show, trigger at will.
```

2021-09-10 21:40 UTC, jwitz commented on guides/managing-dependencies.md
> +One common scenario where you might need to implement trigger rules is if your DAG contains conditional logic like branching. In these cases `one_success` might be a more appropriate rule for tasks d
```suggestion
One common scenario where you might need to implement trigger rules is if your DAG contains conditional logic like branching. In these cases, `one_success` might be a more appropriate rule than `all_success`.
```

2021-09-10 21:40 UTC, jwitz commented on guides/managing-dependencies.md
```suggestion

This code results in the following DAG:

```

2021-09-10 21:40 UTC, jwitz commented on guides/managing-dependencies.md
Do we need to redefine "upstream" and "downstream" for this doc? I remember us doing that for more general topics, and it seems particularly relevant for this topic.

2021-09-10 21:51 UTC, kentdanas commented on guides/managing-dependencies.md
> +If you generate tasks dynamically in your DAG, you should also set dependencies dynamically to ensure they reflect any changes in the tasks. This is easy to accomplish: simply define the dependencies
Eh, not really. That guide is about generating _DAGs_ dynamically, but the comment here is about generating _tasks_ dynamically within a DAG, which are somewhat different concepts.

2021-09-10 21:53 UTC, kentdanas commented on guides/managing-dependencies.md
> +For more examples of setting dependencies within different types of task groups, check out the guide linked above.
It is only linked "above"? Or do you mean not reference it twice?

2021-09-13 17:10 UTC, kentdanas commented on guides/managing-dependencies.md
Yeah good call, added some language to the intro similar to what we have in other guides.

2021-09-13 17:10 UTC, kentdanas commented on guides/managing-dependencies.md
> +Dependencies are one of Airflow's most powerful and popular features - they define the [relationships between tasks](https://airflow.apache.org/docs/apache-airflow/stable/concepts/tasks.html#relation
Yup, re-wrote to put dependencies in terms of their role in the "graph". Let me know what you think.

2021-09-13 17:12 UTC, kentdanas commented
@jwitz thanks for your review! Made some changes based on your comments, let me know what you think.

2021-09-13 19:16 UTC, jwitz commented on guides/managing-dependencies.md
> +For more examples of setting dependencies within different types of task groups, check out the guide linked above.
I would remove this sentence and just keep the previous reference, because the original reference implies what's stated here (that you can find examples of using task groups in the guide)

2021-09-13 19:23 UTC, jwitz approved these changes
Made a minor edit to the intro paragraph and also bumped some previous comments that didn't look like they were addressed on the last revision. After that this is good to go @kentdanas !

2021-09-13 19:23 UTC, jwitz commented on guides/managing-dependencies.md
> +- ```python
Bumping this

2021-09-13 19:23 UTC, jwitz commented on guides/managing-dependencies.md
> +[Dependencies]((https://airflow.apache.org/docs/apache-airflow/stable/concepts/tasks.html#relationships)) are one of Airflow's most powerful and popular features. Remember that in Airflow your pipeli
```suggestion
[Dependencies]((https://airflow.apache.org/docs/apache-airflow/stable/concepts/tasks.html#relationships)) are one of Airflow's most powerful and popular features. In Airflow, your pipelines are defined as Directed, Acyclic Graphs (DAGs). If each task is a node in that graph, then dependencies are the directed edges that determine how you can move through the graph. Because of this, dependencies are key to following data engineering best practices because they help you define flexible pipelines with atomic tasks.
```

2021-09-13 19:23 UTC, jwitz commented on guides/managing-dependencies.md
> +[Dependencies]((https://airflow.apache.org/docs/apache-airflow/stable/concepts/tasks.html#relationships)) are one of Airflow's most powerful and popular features. Remember that in Airflow your pipeli
I rewrote the explanation to start mathematic, then move towards Airflow/ data engineering implications.

2021-09-13 19:23 UTC, jwitz commented on guides/managing-dependencies.md
> +One common scenario where you might need to implement trigger rules is if your DAG contains conditional logic like branching. In these cases `one_success` might be a more appropriate rule for tasks d
Bumping

2021-09-13 21:16 UTC, merged