Timetables guide!
astronomer/airflow-guides pull request #281
Opened 2021-10-12 21:54 UTC by kentdanas

@jwitz @marclamberti guide on Airflow scheduling! Mostly about 2.2 timetables. This one is pretty beefy, all comments welcome :)

2021-10-14 11:30 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +- **Cron expression:** `schedule_interval = '0 0 * * *'`
```suggestion
### Cron expression`
```
Let's make these into `###` headers instead of bullet points. The examples following each method suffice for showing the formatting.

2021-10-14 11:30 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +> Note: Do not make your DAG's schedule dynamic (e.g. `datetime.now()`)! This will cause an error in the scheduler.
```suggestion
> Note: Do not make your DAG's schedule dynamic (e.g. `datetime.now()`)! This will cause an error in the Scheduler.
```
```suggestion
> Note: Do not make your DAG's schedule dynamic (e.g. `datetime.now()`)! This will cause an error in the scheduler.
```

2021-10-14 11:30 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +The scheduling options detailed in the section above cover many common use cases, but they do have some limitations. For example, it is difficult or impossible to implement situations like:
I would introduce Timetables first, then discuss the limitations they eliminate. Either that, or add the limitations as an `###` header to the end of the previous section - up to you.

2021-10-14 11:30 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +[Timetables](https://airflow.apache.org/docs/apache-airflow/stable/concepts/timetable.html), introduced in Airflow 2.2, address these limitations by allowing users to define their own schedules in Py
```suggestion
[Timetables](https://airflow.apache.org/docs/apache-airflow/stable/concepts/timetable.html), introduced in Airflow 2.2, address these limitations by allowing users to define their own schedules in Python code. All DAG schedules are determined by their internal Timetable. 

Going forward, Timetables will become the primary method for scheduling in Airflow. You can still define a `schedule_interval`, but Airflow converts this to a Timetable behind the scenes. And if a cron expression or timedelta is not sufficient for your use case, you can define your own Timetable.
```

2021-10-14 11:30 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +Custom timetables can be registered as part of an Airflow plugin. They must be a subclass of `Timetable`, and should contain the following methods, both of which need to return a `DataInterval` with
```suggestion
Custom timetables can be registered as part of an Airflow plugin. They must be a subclass of `Timetable`, and they should contain the following methods, both of which return a `DataInterval` with a start and an end:
```

2021-10-14 11:30 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +- `infer_manual_data_interval`: Method that returns the data interval when the DAG is manually triggered.
```suggestion
- `next_dagrun_info`: Returns the data interval for the DAG's regular schedule
- `infer_manual_data_interval`: Returns the data interval when the DAG is manually triggered
```

2021-10-14 11:30 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +For this implementation, let's take the example of running a DAG multiple times a day but with uneven intervals: we want to run our DAG at 6:00 and 16:30. Because this schedule has run times with dif
```suggestion
For this implementation, let's run our DAG at 6:00 and 16:30. Because this schedule has run times with differing hours *and* minutes, it can't be represented by a single cron expression. But we can easily implement this schedule with a custom timetable!
```

2021-10-14 11:45 UTC, jwitz requested changes
Overall looks great @kentdanas, this is gonna be such a good resource for people who are excited to get started with Timetables. Requesting changes because I'd like to see if we can better organize the "Scheduling Concepts" section. Currently we group all of the concepts together in a single list. Is there any way to group these more logically/ functionally?

2021-10-14 11:45 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +To start, we need to define our `next_dagrun_info` and `infer_manual_data_interval` methods. Before diving into the code, it's helpful to think through what the data intervals will be for the schedul
```suggestion
To start, we need to define the `next_dagrun_info` and `infer_manual_data_interval` methods. Before diving into the code, it's helpful to think through what the data intervals will be for the schedule we want. Remember that the time the DAG runs (`run_after`) should be the *end* of the data interval since our interval has no holes. So in this case, for a DAG that we want to run at 6:00 and 16:30, we have two different alternating intervals:
```

2021-10-14 11:45 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +- Run at 6:00: interval is from 16:30 *the previous day* to 6:00 the current day
```suggestion
- Run at 6:00: Data interval is from 16:30 *the previous day* to 6:00 the current day
```

2021-10-14 11:45 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +- Run at 16:30: interval is from 6:00 to 16:30 the current day
```suggestion
- Run at 16:30: Data interval is from 6:00 to 16:30 the current day
```

2021-10-14 11:45 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +    - If the last DAG Run started at 6:00, then the next DAG run should start at 16:30 and end at 6:00 the next day.
```suggestion
    - If the previous DAG Run started at 6:00, then the next DAG run should start at 16:30 and end at 6:00 the next day.
```

2021-10-14 11:45 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +    - If the last DAG run started at 14:30, then the DAG run should start at 6:00 the next day and end at 16:30 the next day.
```suggestion
    - If the previous DAG run started at 16:30, then the DAG run should start at 6:00 the next day and end at 16:30 the next day.
```

2021-10-14 11:45 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +- The current time is after midnight but before 6:00. In this case the data interval is between 6:00 and 16:30 the previous day.
```suggestion
- The current time is between 6:00 and 16:30: In this case, the data interval is from 16:30 the previous day to 6:00 the current day.
- The current time is after 16:30 but before midnight: In this case, the data interval is from 6:00 to 16:30 the current day.
- The current time is after midnight but before 6:00: In this case, the data interval is from 6:00 to 16:30 the previous day.
```

2021-10-14 11:45 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +Some of these periods are the same timeframe but on different days relevant to the time the DAG is triggered, requiring three sets of logic. When defining custom timetables, always keep in mind what
```suggestion
We need to account for time periods in the same timeframe (6:00 to 16:30) on different days than the day that the DAG is triggered, which requires three sets of logic. When defining custom timetables, always keep in mind what the last complete data interval should be based on when the DAG should run.
```

2021-10-14 11:45 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +Now we can take those two methods and combine them into a `Timetable` class which will create our Airflow plugin. The full custom timetable plugin is below:
```suggestion
Now we can take those two methods and combine them into a `Timetable` class which will make up our Airflow plugin. The full custom timetable plugin is below:
```

2021-10-14 11:45 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +Note that because timetables are plugins, you will need to restart the Airflow scheduler and webserver after adding or updating them.
```suggestion
Note that because timetables are plugins, you will need to restart the Airflow Scheduler and Webserver after adding or updating them.
```

2021-10-14 11:45 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +This is a simple timetable that could easily be adjusted or built off of to suit other use cases. In general, timetables are completely customizable as long as the methods above are implemented.
```suggestion
This is a simple timetable that could easily be adjusted to suit other use cases. In general, timetables are completely customizable as long as the methods above are implemented.
```

2021-10-14 16:06 UTC, kentdanas commented on guides/scheduling-in-airflow.md
> +- **Data Interval**: The period of data that a task should operate on. This concept is made up of two parameters, both of which are `datetime` objects:
Re-orged this section to have subsections for general terms vs parameters that can be defined, and expanded on some of the definitions. Hopefully this makes it clearer.

2021-10-15 17:15 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +In the next section, we'll describe how these limitations were addressed in Airflow 2.2.
```suggestion
In the next section, we'll describe how these limitations were addressed in Airflow 2.2 with the introduction of timetables.
```

2021-10-15 17:21 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +- **`data_interval_start`**: A datetime object defining the start date and time of the data interval. A DAG's timetable will return this parameter for each DAG Run.
I just realized, if the DAG is returning this does that necessarily make it a parameter? I always assumed parameter is something that a user could control/ configure themselves. Not sure what the solution here is, but I would differentiate this from the other parameters that are configured in code.

2021-10-15 17:23 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +- **`data_interval_start`**: A datetime object defining the start date and time of the data interval. A DAG's timetable will return this parameter for each DAG Run.
I remember changing a lot of instances of this to the parameter name, but looking back maybe that was a misstep. If you change that back to a proper word, you can move these interval terms back up to the "Terms" section.

2021-10-15 18:18 UTC, kentdanas commented on guides/scheduling-in-airflow.md
> +- **`data_interval_start`**: A datetime object defining the start date and time of the data interval. A DAG's timetable will return this parameter for each DAG Run.
Yeah these ones are a bit tricky. They're a parameter in the sense that if you're defining a custom timetable, they're something your function has to return (so you are controlling them). But they're also inherent to a DAG Run now, so they'll be created automatically by Airflow in some cases. I do think it makes sense to keep them in the parameter section here, but I'll add some language to clarify.

For the rest of the text, I think it's okay to refer to them either as the parameter or as just plain text. Like "timetable", it is in some ways both a term and a parameter :)

2021-10-15 18:29 UTC, merged