Debugging dags guide
astronomer/airflow-guides pull request #293
Opened 2021-12-01 22:53 UTC by kentdanas

New guide on debugging DAGs to expand on our (older) [blog post](https://www.astronomer.io/blog/7-common-errors-to-check-when-debugging-airflow-dag#6-youre-missing-task-logs) that's really popular.

@mag3141592 if you wouldn't mind giving this a read and letting me know if you think it's missing anything content-wise based on your time as a new Airflow user and helping folks on your team learn, would much appreciate it!

@jwitz requesting the usual please :)

Closes #287

2021-12-02 16:57 UTC, jwitz requested changes
Requesting changes on the last section on connections, otherwise LGTM @kentdanas !

2021-12-02 16:57 UTC, jwitz commented on guides/debugging-dags.md
> +Once you have identified the cause of any failures in your tasks, you can begin to address them. If you've made any changes to your code, make sure to redeploy (if applicable), and check the Code Vie
```suggestion
Once you have identified the cause of any failures in your tasks, you can begin to address them. If you've made any changes to your code, make sure to redeploy (if applicable) and check the Code View in the Airflow UI to make sure that your changes have been picked up by Airflow.
```

2021-12-02 16:57 UTC, jwitz commented on guides/debugging-dags.md
> +If you want to rerun your full DAG or certain tasks after making changes, you can easily do so with Airflow. Check out [this guide](https://www.astronomer.io/guides/rerunning-dags#rerunning-tasks) fo
```suggestion
If you want to rerun your whole DAG or specific tasks after making changes, you can easily do so with Airflow. Check out [this guide](https://www.astronomer.io/guides/rerunning-dags#rerunning-tasks) for details on how to rerun and apply backfills or catchups. 
```

2021-12-02 16:57 UTC, jwitz commented on guides/debugging-dags.md
> +How to address specific failures will depend heavily on the hook/operator/sensor used, and the use case. However, Airflow connections are an area that consistently cause issues in early DAG developme
```suggestion
How to address specific failures will depend heavily on the hook/operator/sensor used, as well as the use case. However, Airflow connections are an area that consistently cause issues in early DAG development, so we talk about those in more depth below.
```

2021-12-02 16:57 UTC, jwitz commented on guides/debugging-dags.md
> +- Most hooks and operators will use the `default` connection of the correct type. You can change the `default` connection to use your connection details, or define a new connection with a different n
```suggestion
- Most hooks and operators will use the `default` connection of the correct type. You can change the `default` connection to use your connection details or define a new connection with a different name and pass that to the hook/operator.
```

2021-12-02 16:57 UTC, jwitz commented on guides/debugging-dags.md
> +### Connections
```suggestion
### Connection Troubleshooting
```

2021-12-02 16:57 UTC, jwitz commented on guides/debugging-dags.md
> +### Connections
Is there a specific type of error that people can look out for in relation to connections? This content feels like it belongs under an `##` alongside the other possible errors. If possible, we should move this up in the doc and include info on how to tell when a broken connection is the problem, then reword "Addressing Failures" to be more conclusive.

2021-12-02 16:59 UTC, jwitz commented on guides/debugging-dags.md
> +## Addressing Failures
```suggestion
## Recovering from Failures
```

This seems more appropriate? We discuss addressing failures in the previous section, and this content seems to be more about how to move on after the failure.

2021-12-02 18:29 UTC, kentdanas commented on guides/debugging-dags.md
> +If you do have package conflicts that can't be resolved, consider splitting your DAGs into multiple Airflow deployments.
Actually having different DAGs run in different Airflow deployments. So instead of having one mono-Airflow, you have different Airflows that support different dependencies (super common with Astronomer customers)

2021-12-02 18:32 UTC, kentdanas commented on guides/debugging-dags.md
> +- If you're looking at historical task failures, ensure that your logs are retained long enough. For example, the default log retention period on Astronomer is 15 days, so any logs prior to that will
Only for Enterprise, so figured that was too specific to link to for a guide. In general, this will depend on how the Airflow admins set up their environment.

2021-12-02 18:34 UTC, kentdanas commented on guides/debugging-dags.md
> +### Connections
Yeah I'm okay with moving it up. I'll add some wording on identifying when a connection is the problem, but there isn't a specific error. Unfortunately connection errors can be really vague and vary widely

2021-12-02 18:49 UTC, kentdanas commented on guides/debugging-dags.md
> +### Installing Supporting Packages
I wanted this section to be broader than just dependency conflicts, because we've gotten feedback that knowing how to install supporting packages and check that they are present is confusing. So I left the title as is, but happy to chat more about this if you think it doesn't make sense.

2021-12-02 18:50 UTC, kentdanas commented
@jwitz thanks for the review, super helpful feedback. I moved the last few sections around as you suggested, let me know if this flows better to you now.

2021-12-03 11:27 UTC, jwitz approved these changes
Last few suggestions and replies, otherwise LGTM!

2021-12-03 11:27 UTC, jwitz commented on guides/debugging-dags.md
> +Typically, Airflow connections are needed for Airflow to talk to any external system. Most hooks and operators will expect a connection parameter to be defined. Improperly defined connections are one
```suggestion
Typically, Airflow connections are needed for Airflow to talk to any external system. Most hooks and operators expect a defined connection parameter. Because of this, improperly defined connections are one of the most common issues Airflow users have to debug when first working with their DAGs. 
```

2021-12-03 11:27 UTC, jwitz commented on guides/debugging-dags.md
> +While the specific error associated with a poorly defined connection can vary widely, you will typically see a message with "connection" in the task logs. If you haven't defined a connection, you'll
```suggestion
While the specific error associated with a poorly defined connection can vary widely, you will typically see a message with "connection" in your task logs. If you haven't defined a connection, you'll see a message like `'connection_abc' is not defined`. 
```

2021-12-03 11:27 UTC, jwitz commented on guides/debugging-dags.md
> +How to address specific failures will depend heavily on the hook/operator/sensor used, as well as the use case. The sections above should help you through the most commonly encountered pitfalls that
```suggestion
How to address specific failures will depend heavily on the hook/operator/sensor used, as well as the use case. The sections above should help you through the most commonly encountered pitfalls that beginners face. For help with more complex issues, consider joining the [Apache Airflow Slack](https://airflow.apache.org/community/) or [reach out to Astronomer](https://www.astronomer.io/get-astronomer/).
```

2021-12-03 11:27 UTC, jwitz commented on guides/debugging-dags.md
> +If you do have package conflicts that can't be resolved, consider splitting your DAGs into multiple Airflow deployments.
Updated my suggestion in the previous comment, I think we should explicitly state how those DAGs should be split up even though it might seem obvious

2021-12-03 11:27 UTC, jwitz commented on guides/debugging-dags.md
> +### Installing Supporting Packages
I think it's okay to keep it broader, but I would try to frame the title as a troubleshooting topic. Installing Supporting Packages sounds like its own guide, whereas this topic is specifically about how that process can go awry. This would also make it more consistent with the current headers

2021-12-03 11:27 UTC, jwitz commented on guides/debugging-dags.md
> +    ![Test Connections](https://assets2.astronomer.io/main/guides/debugging-dags/test_connections.png)
Might need newlines between the image link, not sure tho

2021-12-03 15:53 UTC, kentdanas commented on guides/debugging-dags.md
> +    ![Test Connections](https://assets2.astronomer.io/main/guides/debugging-dags/test_connections.png)
Ok yeah, see your point on the supporting packages title. Will update.

And I wondered that about the image link, but it passed the markdown lint and is rendering fine on my local preview so...?....May add them anyway just to be safe :)

2021-12-03 21:48 UTC, mag3141592 commented on guides/debugging-dags.md
> +- Ensure your DAG has a start date that is in the past. If your start date is in the future, triggering the DAG results a "successful" DAG run even though no tasks ran.
Maybe a note about start date being in past and execution date being in the future because of the data interval size, so unpausing a DAG won't start a run unless both are in the past. I think there is still general confusion around execution date.

2021-12-03 21:52 UTC, mag3141592 reviewed
Hey @kentdanas,

This guide would have saved me a lot of head aheads a few months ago :)

2 other situations that we could add or are maybe for a different guide:

- "Task exited with return code Negsignal.SIGKILL"
- Adding tasks to DAG that has "depends on past" set won't run until you set the state of those tasks in the prior run

New people still struggle with getting XCOMs to work, I wonder if it's worth linking to the existing guide for XCOMs somewhere?

2021-12-03 22:26 UTC, kentdanas commented on guides/debugging-dags.md
> +- Ensure your DAG has a start date that is in the past. If your start date is in the future, triggering the DAG results a "successful" DAG run even though no tasks ran.
Good call, added a note about that and linked out to our new scheduling guide that covers data intervals and other scheduling concepts.

2021-12-03 22:37 UTC, kentdanas commented
@mag3141592 thanks a bunch for the review! These are super helpful points, added notes about all of them :).

2021-12-03 22:41 UTC, merged