Update Scaling out Airflow Guide
astronomer/airflow-guides pull request #322
Opened 2022-01-18 17:31 UTC by kentdanas

Updated Scaling out Airflow guide to fix some outdated info and add content based on feedback from solutions and CRE.

@collinmcnulty @dylanbstorey if you have a chance and want to give this a read and make sure I got it all right, that would be much appreciated!

Closes #308 #316

2022-01-18 19:41 UTC, collinmcnulty requested changes

2022-01-18 19:41 UTC, collinmcnulty commented on guides/airflow-scaling-workers.md
> +The reason Airflow has so many nobs at different levels is that, as an agnostic orchestrator, Airflow is used for a wide variety of use cases and by a wide variety of personas. Airflow admins or devo
spelling: knobs, DevOps

2022-01-18 19:41 UTC, collinmcnulty commented on guides/airflow-scaling-workers.md
> +- **`parallelism`:** Default 32. This is the maximum number of tasks that can run concurrently within a single Airflow environment. If this setting is set to 32, no more than 32 tasks can run at once
The state is called "Queued", so that might be clearer wording than "in a queue"

2022-01-18 19:41 UTC, collinmcnulty commented on guides/airflow-scaling-workers.md
> +- **`max_active_tasks_per_dag`:** (formerly `dag_concurrency`) Default 16. This determines how many task instances the Airflow Scheduler is able to schedule at once per DAG. Think of this as "maximum
Use this setting to prevent any one DAG from taking up too many of the available slots from parallelism or your pools. This helps DAGs to be good neighbors to one another.

2022-01-18 19:41 UTC, collinmcnulty commented on guides/airflow-scaling-workers.md
> +  If you increase the amount of resources available to Airflow (such as Celery Workers or Kubernetes Pods) and notice that tasks are still not running as expected, you might have to increase the valu
Kubernetes Resources, not Kubernetes pods. In K8s you add available memory and CPU and Airflow eats that to form pods.

2022-01-18 19:41 UTC, collinmcnulty commented on guides/airflow-scaling-workers.md
> +- **`max_active_runs_per_dag`:** Default 16. This determines the maximum number of active DAG Runs (per DAG) the Airflow Scheduler can create at any given time. In Airflow, a [DAG Run](https://airflo
This parameter is most relevant when backfilling or if Airflow has to catch up from missed DAG Runs. Consider how you want to handle these scenarios when setting this parameter.

2022-01-18 19:41 UTC, collinmcnulty commented on guides/airflow-scaling-workers.md
> +- **`dag_file_processor_timeout`:**: Default 30 seconds. This is how long a `DagFileProcessor`, which processes a DAG file, can run before timing out. If your DAG processing logs show timeouts, try i
If your DAG processing logs show timeouts or if your DAG is not showing up either in the list of DAGs or the import errors ...

2022-01-18 19:41 UTC, collinmcnulty commented on guides/airflow-scaling-workers.md
> +- **`concurrency`:** This is the maximum number of task instances allowed to run concurrently across all active DAG runs of the DAG for which this setting is defined. This allows you to set 1 DAG to
The value of max_active_tasks_per_dag is assumed

2022-01-18 19:41 UTC, collinmcnulty commented on guides/airflow-scaling-workers.md
> +- **`concurrency`:** This is the maximum number of task instances allowed to run concurrently across all active DAG runs of the DAG for which this setting is defined. This allows you to set 1 DAG to
Is it still called concurrency here?

2022-01-18 19:41 UTC, collinmcnulty commented on guides/airflow-scaling-workers.md
> +- **`max_active_tis_per_dag`:** Formerly `task_concurrency`. This is a limit to the amount of times the same task can run concurrently across all DAG Runs.
For instance, if a task reaches out to an external resource such as a data table that you do not want multiple tasks modifying at once, you can set this value to 1.

2022-01-18 19:41 UTC, collinmcnulty commented on guides/airflow-scaling-workers.md
> +Your `worker_concurrency` is limited by `max_active_tasks_per_dag`. If you increase `worker_concurrency`, you might also need to provision additional CPU and/or memory for your workers.
I don't think that's true. There's no reason you couldn't run 100 workers each of which can only handle a worker_concurrency of 2 (that I know of).

2022-01-18 19:41 UTC, collinmcnulty commented on guides/airflow-scaling-workers.md
> +    - Try changing: `max_active_task_per_dag`
missing s in tasks

Try looking at pools. See if you're at your overall parallelism limit.

2022-01-18 19:41 UTC, collinmcnulty commented on guides/airflow-scaling-workers.md
> +    - Try changing: `scheduler_heartbeat_sec`, `parsing_processes`
The try changing here is incorrect. By the time it gets to queued it's past parsing and the scheduler. If using K8s executor: check that there are available resources in the namespace and check if worker_pods_creation_batch_size can be increased. If using Celery check if worker_concurrency can be increased (and generally if you have workers available to do the work).

2022-01-18 20:25 UTC, kentdanas commented on guides/airflow-scaling-workers.md
> +The reason Airflow has so many nobs at different levels is that, as an agnostic orchestrator, Airflow is used for a wide variety of use cases and by a wide variety of personas. Airflow admins or devo
Ha, "nobs" was a funny typo in this context. Thanks for catching

2022-01-18 20:29 UTC, kentdanas commented on guides/airflow-scaling-workers.md
> +- **`concurrency`:** This is the maximum number of task instances allowed to run concurrently across all active DAG runs of the DAG for which this setting is defined. This allows you to set 1 DAG to
Yep, still "concurrency" in the 2.2 docs https://airflow.apache.org/docs/apache-airflow/stable/faq.html#scheduling-dag-file-parsing

2022-01-18 20:37 UTC, kentdanas commented
@collinmcnulty thanks for your comments! I think I addressed everything, but let me know if you catch anything else.

2022-01-19 14:25 UTC, collinmcnulty approved these changes

2022-01-19 14:25 UTC, collinmcnulty commented
@wolfier Curious as to your thoughts on this too

2022-01-19 21:34 UTC, wolfier commented
Great work! This will be immensely helpful to pass out to customer :D

2022-01-20 14:34 UTC, kentdanas commented on guides/airflow-scaling-workers.md
> +- **`dag_file_processor_timeout`:**: Default 30 seconds. This is how long a `DagFileProcessor`, which processes a DAG file, can run before timing out. If your DAG processing logs show timeouts, or if
Good catch, thanks

2022-01-20 19:20 UTC, collinmcnulty commented on guides/airflow-scaling-workers.md
> +- **`parsing_processes`:** (formerly `max_threads`) Default 2 x vCPU. The scheduler can run multiple processes in parallel to parse dags. This defines how many processes will run. Increasing this val
The default really is 2. We *recommend* you set it to 2 x vCPU

2022-01-20 19:25 UTC, kentdanas commented on guides/airflow-scaling-workers.md
> +- **`parsing_processes`:** (formerly `max_threads`) Default 2 x vCPU. The scheduler can run multiple processes in parallel to parse dags. This defines how many processes will run. Increasing this val
Sigh, moving too quickly. Thanks for catching!

2022-01-21 15:20 UTC, kentdanas commented
@jwitz this should be good to go content-wise. If I could get a copy review whenever it's convenient that would be much appreciated!

2022-01-21 17:35 UTC, jwitz requested changes
Sorry for loads of suggestions, but most are very minor! Only things I'm requesting changes on are the code snippets for DAG and task-level settings. I think we should remove our specific examples and instead only include snippets if we're explaining how to define settings more generally.

2022-01-21 17:35 UTC, jwitz commented on guides/airflow-scaling-workers.md
> +  It is helpful know how long it takes to parse your DAGs (`dag_processing.total_parse_time`) to know what values to choose for `min_file_process_interval` and `dag_dir_list_interval`. If your `dag_d
```suggestion
  It is helpful know how long it takes to parse your DAGs (`dag_processing.total_parse_time`) to know what values to choose for `min_file_process_interval` and `dag_dir_list_interval`. If your `dag_dir_list_interval` is less than the amount of time it takes to parse each DAG, you might see performance issues.
```

2022-01-21 17:35 UTC, jwitz commented on guides/airflow-scaling-workers.md
> +- **`parsing_processes`:** (formerly `max_threads`) Default 2. The scheduler can run multiple processes in parallel to parse dags. This setting defines how many processes will run. We recommend setti
```suggestion
- **`parsing_processes`:** (formerly `max_threads`) The scheduler can run multiple processes in parallel to parse DAGs. This setting defines how many processes can run in parallel. We recommend setting a value of 2x your available vCPUs. Increasing this value can help serialize DAGs more efficiently if you have a large number of them. Note that if you are running multiple schedulers, this value will apply to *each* of them. By default, this value is set to 2. 
```

2022-01-21 17:35 UTC, jwitz commented on guides/airflow-scaling-workers.md
> +- **`file_parsing_sort_mode`**: Default `modified_time`. This determines how the scheduler will list and sort DAG files to decide the parsing order. Set to one of: `modified_time`, `random_seeded_by_
```suggestion
- **`file_parsing_sort_mode`:** This determines how the scheduler will list and sort DAG files to decide the parsing order. Set to one of: `modified_time`, `random_seeded_by_host` and `alphabetical`. The default setting is `modified_time`. 
```

2022-01-21 17:35 UTC, jwitz commented on guides/airflow-scaling-workers.md
> +- **`scheduler_heartbeat_sec`:** Default 5 seconds. The scheduler constantly tries to trigger new tasks. This defines how often the scheduler should run (in seconds).
```suggestion
- **`scheduler_heartbeat_sec`:** This setting defines how often the scheduler should run (in seconds) to trigger new tasks. The default value is 5 seconds. 
```

2022-01-21 17:35 UTC, jwitz commented on guides/airflow-scaling-workers.md
> +- **`max_dagruns_to_create_per_loop`:** Default 10. This is the max number of DAGs to create DagRuns for per scheduler loop. You can use this option to free up resources for scheduling tasks by **dec
```suggestion
- **`max_dagruns_to_create_per_loop`:** This is the max number of DAGs to create Dag runs for per scheduler loop. You can use this option to free up resources for scheduling tasks by decreasing the value. The default value is 10 seconds. 
```

2022-01-21 17:35 UTC, jwitz commented on guides/airflow-scaling-workers.md
> +- **`max_tis_per_query`:** Default 512. This parameter changes the batch size of queries to the metastore in the main scheduling loop. If the value is higher, you can process more `tis` per query, bu
```suggestion
- **`max_tis_per_query`:** This parameter changes the batch size of queries to the metastore in the main scheduling loop. If the value is higher, you can process more `tis` per query, but your query may become too complex and create a performance bottleneck. The default value is 512 queries. 
```

2022-01-21 17:35 UTC, jwitz commented on guides/airflow-scaling-workers.md
> +DAG-level settings apply only to specific DAGs and are defined in your DAG code. You should look to modify DAG-level settings if you want to performance tune a particular DAG, especially in cases whe
```suggestion
DAG-level settings apply only to specific DAGs and are defined in your DAG code. You should modify DAG-level settings if you want to performance tune a particular DAG, especially in cases where that DAG is hitting an external system (e.g. an API or database) that might cause performance issues if hit too frequently. When a there's a setting at both the DAG-level and environment-level, the DAG-level setting takes precedence.
```

2022-01-21 17:35 UTC, jwitz commented on guides/airflow-scaling-workers.md
> +There are three primary DAG-level Airflow settings users can define in code:
```suggestion
There are three primary DAG-level Airflow settings that users can define in code:
```

2022-01-21 17:35 UTC, jwitz commented on guides/airflow-scaling-workers.md
> +  If are utilizing `catchup` or `backfill` for your DAG, consider defining this parameter to ensure you don't accidentally trigger a high number of DAG runs.
```suggestion
  If are utilizing `catchup` or `backfill` for your DAG, consider defining this parameter to ensure that you don't accidentally trigger a high number of DAG runs.
```

2022-01-21 17:35 UTC, jwitz commented on guides/airflow-scaling-workers.md
> +- **`max_active_runs`:** This is the maximum number of active DAG Runs allowed for the DAG in question. Once this limit is hit, the Scheduler will not create new active DAG Runs. If this setting is n
```suggestion
- **`max_active_runs`:** This is the maximum number of active DAG Runs allowed for the DAG in question. Once this limit is hit, the Scheduler will not create new active DAG Runs. If this setting is not defined, the value of the environment-level setting `max_active_runs_per_dag` is assumed.
```

2022-01-21 17:35 UTC, jwitz commented on guides/airflow-scaling-workers.md
> +- **`max_active_tasks`:** This is the total number of tasks that can run at the same time for a given DAG run. It essentially controls the parallelism within your DAG. If this setting is not defined,
```suggestion
- **`max_active_tasks`:** This is the total number of tasks that can run at the same time for a given DAG run. It essentially controls the parallelism within your DAG. If this setting is not defined, the value of the environment-level setting `max_active_tasks_per_dag` is assumed.
```

2022-01-21 17:35 UTC, jwitz commented on guides/airflow-scaling-workers.md
> +- **`concurrency`:** This is the maximum number of task instances allowed to run concurrently across all active DAG runs of the DAG for which this setting is defined. This allows you to set 1 DAG to
```suggestion
- **`concurrency`:** This is the maximum number of task instances allowed to run concurrently across all active DAG runs for a given DAG. This allows you to set 1 DAG to be able to run 32 tasks at once, while another DAG might only be able to run 16 tasks at once. If this setting is not defined, the value of the environment-level setting `max_active_tasks_per_dag` is assumed.
```

2022-01-21 17:35 UTC, jwitz commented on guides/airflow-scaling-workers.md
>    For example:
Why do we have an example just for this setting? I think it's save to remove this, unless it's describing how to set DAG-level settings in general (and in that case, let's say that)

2022-01-21 17:35 UTC, jwitz commented on guides/airflow-scaling-workers.md
> +Task-level settings can be used to implement even finer grain control within a specific DAG(s) and are defined in your operators. You should look to modify task-level settings if you have specific ty
```suggestion
Task-level settings are defined in a task's operators and can be used to implement even finer-grained control of performance. You should modify task-level settings if you have specific types of tasks that are known to cause performance issues. 
```

2022-01-21 17:35 UTC, jwitz commented on guides/airflow-scaling-workers.md
> +- **`max_active_tis_per_dag`:** Formerly `task_concurrency`. This is a limit to the amount of times the same task can run concurrently across all DAG Runs. For instance, if a task reaches out to an e
```suggestion
- **`max_active_tis_per_dag`:** (Formerly `task_concurrency`) This the maximum amount of times that the same task can run concurrently across all DAG Runs. For instance, if a task reaches out to an external resource, such as a data table, that should not me modified by multiple tasks at once, then you can set this value to 1.
```

2022-01-21 17:35 UTC, jwitz commented on guides/airflow-scaling-workers.md
>    ```
Why don't we just include a general example of task configuration towards the end of this section? I don't have any further understanding of this setting from seeing this snippet.

2022-01-21 17:35 UTC, jwitz commented on guides/airflow-scaling-workers.md
> +- **`pool`:** Pools are a way to limit the number of concurrent instances of an arbitrary group of tasks. This is useful if you have a lot of workers or DAG runs in parallel, but you want to avoid an
```suggestion
- **`pool`:** This setting defines the amount of pools available for a task. Pools are a way to limit the number of concurrent instances of an arbitrary group of tasks. This setting is useful if you have a lot of workers or DAG runs in parallel, but you want to avoid an API rate limit or otherwise don't want to overwhelm a data source or destination. For more information, read our [Airflow Pools Guide](https://www.astronomer.io/guides/airflow-pools).
```

2022-01-21 17:35 UTC, jwitz commented on guides/airflow-scaling-workers.md
> +You can also tune your **`worker_concurrency`** (environment variable `AIRFLOW__CELERY__WORKER_CONCURRENCY`), which determines how many tasks each Celery worker can run at any given time. If this val
```suggestion
You can also tune your **`worker_concurrency`** (environment variable: `AIRFLOW__CELERY__WORKER_CONCURRENCY`), which determines how many tasks each Celery worker can run at any given time. By default, the Celery executor will run a maximum of 16 tasks concurrently. If you increase `worker_concurrency`, you might also need to provision additional CPU and/or memory for your workers.   
```

2022-01-21 17:35 UTC, jwitz commented on guides/airflow-scaling-workers.md
> +Depending on which executor you choose for your Airflow environment, there are a couple of additional concepts to keep in mind when scaling.
```suggestion
Depending on which executor you choose for your Airflow environment, there are a couple of additional settings to keep in mind when scaling.
```

2022-01-21 17:35 UTC, jwitz commented on guides/airflow-scaling-workers.md
> +When performance tuning with the Kubernetes executor, it is important to keep in mind the supporting infrastructure of your Kubernetes cluster. Many users will enable auto-scaling on their cluster to
```suggestion
When performance tuning with the Kubernetes executor, it is important to consider the supporting infrastructure of your Kubernetes cluster. Many users will enable auto-scaling on their cluster to ensure they get the benefit of Kubernetes' elasticity.
```

2022-01-21 17:35 UTC, jwitz commented on guides/airflow-scaling-workers.md
> +You can also tune your **`worker_pods_creation_batch_size`** (environment variable `AIRFLOW__KUBERNETES__WORKER_PODS_CREATION_BATCH_SIZE`), which determines how many pods can be created per scheduler
```suggestion
You can also tune your **`worker_pods_creation_batch_size`** (environment variable: `AIRFLOW__KUBERNETES__WORKER_PODS_CREATION_BATCH_SIZE`), which determines how many pods can be created per scheduler loop. The default is 1, but most users will want to increase this number for better performance, especially if you have concurrent tasks. How high you can increase the value depends on the tolerance of your Kubernetes cluster.
```

2022-01-21 17:35 UTC, jwitz commented on guides/airflow-scaling-workers.md
> +- Issue: Tasks scheduling latency is high
Let's bold everything to the left of the colons. Or maybe even as a table?

2022-01-21 17:35 UTC, jwitz commented on guides/airflow-scaling-workers.md
> +Scaling your Airflow environment can be more of an art than a science, and is highly dependent on your supporting infrastructure and your DAGs. There are too many potential scaling issues to address
```suggestion
Scaling your Airflow environment can be more of an art than a science, and it's highly dependent on your supporting infrastructure and your DAGs. There are too many potential scaling issues to address them all here, but below are some commonly encountered issues and possible parameters to change. 
```

2022-01-21 18:23 UTC, kentdanas commented on guides/airflow-scaling-workers.md
>    For example:
Yeah this was legacy and I don't think it's needed with the way we rewrote. Will remove it

2022-01-21 18:26 UTC, kentdanas commented on guides/airflow-scaling-workers.md
> +- Issue: Tasks scheduling latency is high
Tables are really tough in markdown, but bolding is a good idea.

2022-01-21 18:37 UTC, kentdanas commented
Thanks for the review @jwitz! For the code snippets, I removed some of them, but left one each in the DAG-level and task-level settings. I want it to be clear that these settings are defined in DAG code instead of with environment variables like the environment-settings, and I think the examples are helpful to show *how* you can modify them (we're not advising on what they *should* be). I cleaned up the language and changed where they are in the section to hopefully make that clearer. Let me know what you think.

2022-01-24 16:30 UTC, jwitz commented on guides/airflow-scaling-workers.md
> +You should modify environment-level settings if you want to tune performance across *all* of the DAGs in your Airflow environment. This is particularly relevant if you want your DAGs can run adequate
```suggestion
You should modify environment-level settings if you want to tune performance across *all* of the DAGs in your Airflow environment. This is particularly relevant if you want your DAGs to run adequately on your supporting infrastructure. Specifically, the following settings are relevant:
```

2022-01-24 16:31 UTC, jwitz commented on guides/airflow-scaling-workers.md
> +- **`max_active_tasks_per_dag`:** (formerly `dag_concurrency`) This determines maximum number of tasks that can be scheduled at once, per DAG." Use this setting to prevent any one DAG from taking up
```suggestion
- **`max_active_tasks_per_dag`:** (formerly `dag_concurrency`) This determines the maximum number of tasks that can be scheduled at once, per DAG." Use this setting to prevent any one DAG from taking up too many of the available slots from parallelism or your pools, which helps DAGs be good neighbors to one another. By default, this is set to 16.
```

2022-01-24 16:31 UTC, jwitz commented on guides/airflow-scaling-workers.md
> +  It is helpful know how long it takes to parse your DAGs (`dag_processing.total_parse_time`) to know what values to choose for `min_file_process_interval` and `dag_dir_list_interval`. If your `dag_d
```suggestion
  It is helpful to know how long it takes to parse your DAGs (`dag_processing.total_parse_time`) to know what values to choose for `min_file_process_interval` and `dag_dir_list_interval`. If your `dag_dir_list_interval` is less than the amount of time it takes to parse each DAG, you might see performance issues.
```

2022-01-24 16:32 UTC, jwitz commented on guides/airflow-scaling-workers.md
> +DAG-level settings apply only to specific DAGs and are defined in your DAG code. You should modify DAG-level settings if you want to performance tune a particular DAG, especially in cases where that
```suggestion
DAG-level settings apply only to specific DAGs and are defined in your DAG code. You should modify DAG-level settings if you want to performance tune a particular DAG, especially in cases where that DAG is hitting an external system (e.g. an API or database) that might cause performance issues if hit too frequently. When a setting exists at both the DAG-level and environment-level, the DAG-level setting takes precedence.
```

2022-01-24 16:33 UTC, jwitz approved these changes
New example settings look great! Some final typos here (probably from my own suggestions haha) but otherwise LGTM

2022-01-24 16:45 UTC, merged