Update Airflow components guide
astronomer/airflow-guides pull request #344
Opened 2022-03-01 21:42 UTC by kentdanas

Closes #248 

@jwitz quick update of this existing guide. Love your review when you get a chance

2022-03-14 17:28 UTC, kentdanas commented
@jwitz friendly ping on this in case it got buried. I know you have a ton on your plate and this isn't super high priority, so no rush.

2022-03-15 00:29 UTC, jwitz requested changes
Thank you for the ping @kentdanas ! Mostly minor suggestions in here, but I am wondering about why we frame executors as a non-core component of Airflow. Once that's resolved, this should be good to go

2022-03-15 00:29 UTC, jwitz commented on guides/airflow-components.md
> +description: "The core components of Apache Airflow's infrastructure."
```suggestion
description: "Learn about the core components of Apache Airflow's infrastructure."
```

2022-03-15 00:29 UTC, jwitz commented on guides/airflow-components.md
> +When working with Airflow, it is important to understand the underlying components: these are the pieces of Airflow infrastructure that power Airflow's orchestration capabilities "under the hood". Ev
```suggestion
When working with Airflow, it is important to understand its underlying components of its infrastructure. Even if you mostly interact with Airflow as a DAG author, knowing which components are "under the hood" are and why they are needed can be helpful for running developing your DAGs, debugging, and running Airflow successfully.
```

2022-03-15 00:29 UTC, jwitz commented on guides/airflow-components.md
> +In this guide, we'll define Airflow's components, discuss the different available executors, and touch on managing Airflow infrastructure and high availability. Note that this guide is focused on the
```suggestion
In this guide, we'll describe Airflow's core components and touch on managing Airflow infrastructure and high availability. Note that this guide is focused on the components and features of Airflow 2.0+. Some of the components and features mentioned here are not available in earlier versions of Airflow.
```

2022-03-15 00:29 UTC, jwitz commented on guides/airflow-components.md
> +- **[Scheduler:](https://airflow.apache.org/docs/apache-airflow/stable/concepts/scheduler.html)** The Daemon responsible for scheduling jobs. This is a multi-threaded Python process that uses the DAG
```suggestion
- **[Scheduler](https://airflow.apache.org/docs/apache-airflow/stable/concepts/scheduler.html):** A Daemon responsible for scheduling jobs. This is a multi-threaded Python process that determines what tasks need to be run, when they need to be run, and where they are run.
```

2022-03-15 00:29 UTC, jwitz commented on guides/airflow-components.md
> +- **Webserver:** A Flask server running with Gunicorn that serves the Airflow UI. It provides an interface to interact with your DAGs, tasks, and database.
```suggestion
- **Webserver:** A Flask server running with Gunicorn that serves the [Airflow UI](https://www.astronomer.io/guides/airflow-ui/).
```

2022-03-15 00:29 UTC, jwitz commented on guides/airflow-components.md
> +- **[Database:](https://airflow.apache.org/docs/apache-airflow/stable/howto/set-up-database.html)** A database where all DAG and task metadata are stored. This is typically a Postgres database, but M
```suggestion
- **[Database](https://airflow.apache.org/docs/apache-airflow/stable/howto/set-up-database.html):** A database where all DAG and task metadata are stored. By default this is a Postgres database, but MySQL, MsSQL, and SQLite are also supported.
```

2022-03-15 00:29 UTC, jwitz commented on guides/airflow-components.md
> +Additionally, there are a couple of other components that not considered part of the "core" of Airflow, but are required to run your tasks or make use of certain features:
```suggestion
In addition to these core components, there are a few situational components that are used only to run tasks or make use of certain features:
```

2022-03-15 00:29 UTC, jwitz commented on guides/airflow-components.md
> +- **[Executor:](https://airflow.apache.org/docs/apache-airflow/stable/executor/index.html)** The mechanism by which tasks are run. An executor is running at all times Airflow is up (it runs within th
```suggestion
- **[Executor](https://airflow.apache.org/docs/apache-airflow/stable/executor/index.html):** The mechanism for running tasks. An executor is running at all times Airflow is up (it runs within the Scheduler process). In the section below, we walk through the different executors available and how to choose between them.
```
The fact that this runs at all times "Airflow is up" doesn't seem meaningfully different from how we define the other core components. Why is this here instead of up above, especially since it runs in the Scheduler?

2022-03-15 00:29 UTC, jwitz commented on guides/airflow-components.md
> +- **[Triggerer:](https://airflow.apache.org/docs/apache-airflow/stable/concepts/deferring.html)** A separate process in addition to the Scheduler running `asyncio` to support deferrable operators. Th
```suggestion
- **[Triggerer](https://airflow.apache.org/docs/apache-airflow/stable/concepts/deferring.html):** A separate process which supports [deferrable operators](https://www.astronomer.io/guides/deferrable-operators). This component is optional and must be run separately. It is needed only if you plan to use deferrable (or "asynchronous") operators. 
```

2022-03-15 00:29 UTC, jwitz commented on guides/airflow-components.md
> +All of these components work together to schedule your DAGs and run your tasks:
```suggestion
In the following diagram, you can see how all of these components work together to schedule your DAGs and run your tasks:
```

2022-03-15 00:29 UTC, jwitz commented on guides/airflow-components.md
> +![title](https://assets2.astronomer.io/main/guides/airflow_component_relationship_fixed.png)
Worth updating this in light of the rebrand, even if just to remove the old logo?

2022-03-15 00:29 UTC, jwitz commented on guides/airflow-components.md
> +Airflow users can choose from multiple available executors or [write their own custom one](https://airflow.apache.org/docs/apache-airflow/stable/executor/index.html). Each executor is good for differ
```suggestion
Airflow users can choose from multiple available executors or [write a custom one](https://airflow.apache.org/docs/apache-airflow/stable/executor/index.html). Each executor excels in specific situations:
```

2022-03-15 00:29 UTC, jwitz commented on guides/airflow-components.md
> +- **[KubernetesExecutor:](https://airflow.apache.org/docs/apache-airflow/stable/executor/kubernetes.html)** Calls the Kubernetes API to create a separate pod for each task to run, enabling users to p
```suggestion
- **[SequentialExecutor](https://airflow.apache.org/docs/apache-airflow/stable/executor/sequential.html):** Executes tasks sequentially inside the Scheduler process, with no parallelism or concurrency. This executor is rarely used in practice, but it is the default in Airflow's configuration.
- **[LocalExecutor](https://airflow.apache.org/docs/apache-airflow/stable/executor/local.html):** Executes tasks locally inside the Scheduler process, but supports parallelism and hyperthreading. This executor is a good fit for testing Airflow on a local machine or on a single node.
- **[CeleryExecutor](https://airflow.apache.org/docs/apache-airflow/stable/executor/celery.html):** Uses a Celery backend (such as Redis, RabbitMq, or another message queue system) to coordinate tasks between preconfigured workers. This executor is ideal if you have a high volume of shorter running tasks or a more consistent task load.
- **[KubernetesExecutor](https://airflow.apache.org/docs/apache-airflow/stable/executor/kubernetes.html):** Calls the Kubernetes API to create a separate pod for each task to run, enabling users to pass in custom configurations for each of their tasks and use resources efficiently. This executor is great in a few different contexts: 

    - You have long running tasks that you don't want to be interrupted by code deploys or Airflow updates
    - Your tasks require very specific resource configurations
    - Your tasks run infrequently, and you don't want to incur worker resource costs when they aren't running.
```

2022-03-15 00:29 UTC, jwitz commented on guides/airflow-components.md
> +Note, there are also a couple of other executors that we don't cover here, including the [CeleryKubernetes Executor](https://airflow.apache.org/docs/apache-airflow/stable/executor/celery_kubernetes.h
```suggestion
Note that there are also a couple of other executors that we don't cover here, including the [CeleryKubernetes Executor](https://airflow.apache.org/docs/apache-airflow/stable/executor/celery_kubernetes.html) and the [Dask Executor](https://airflow.apache.org/docs/apache-airflow/stable/executor/dask.html). These are considered more experimental and are not as widely adopted as the other executors covered here.
```

2022-03-15 00:29 UTC, jwitz commented on guides/airflow-components.md
> +Airflow can be made highly available, which helps make it suitable for large organizations with critical production workloads. Airflow 2 introduced a highly available Scheduler, meaning you can run m
```suggestion
Airflow can be made highly available, which makes it suitable for large organizations with critical production workloads. Airflow 2 introduced a highly available Scheduler, meaning that you can run multiple Scheduler replicas in an active-active model. This makes the Scheduler more performant and resilient, eliminating a single point of failure within your Airflow environment. 
```

2022-03-15 15:19 UTC, kentdanas commented on guides/airflow-components.md
> +- **[Database:](https://airflow.apache.org/docs/apache-airflow/stable/howto/set-up-database.html)** A database where all DAG and task metadata are stored. This is typically a Postgres database, but M
Actually with OSS Airflow the default is SQLite (our CLI defaults to Postgres), but it's highly recommended to not use SQLite, which is why I put "typically" since Postgres is most common.

2022-03-15 15:23 UTC, kentdanas commented on guides/airflow-components.md
> +- **[Executor:](https://airflow.apache.org/docs/apache-airflow/stable/executor/index.html)** The mechanism by which tasks are run. An executor is running at all times Airflow is up (it runs within th
I'll move it up, I think it's fine to put it as a core component. I think it wasn't in the original guide because it's not a "separate" process that has to run (e.g. you wouldn't have a container for it) like the scheduler/webserver/database. But agree that since it's always running it makes sense to have it above.

2022-03-15 20:28 UTC, kentdanas commented
Thanks for the review @jwitz! I think I addressed everything, but let me know if you see anything else.

2022-03-15 22:29 UTC, jwitz approved these changes
Two minor edits, otherwise LGTM!

2022-03-15 22:29 UTC, jwitz commented on guides/airflow-components.md
> +- **[Database:](https://airflow.apache.org/docs/apache-airflow/stable/howto/set-up-database.html)** A database where all DAG and task metadata are stored. This is typically a Postgres database, but M
```suggestion
- **[Scheduler](https://airflow.apache.org/docs/apache-airflow/stable/concepts/scheduler.html):** A Daemon responsible for scheduling jobs. This is a multi-threaded Python process that determines what tasks need to be run, when they need to be run, and where they are run.
- **[Database](https://airflow.apache.org/docs/apache-airflow/stable/howto/set-up-database.html):** A database where all DAG and task metadata are stored. This is typically a Postgres database, but MySQL, MsSQL, and SQLite are also supported.
```

2022-03-15 22:29 UTC, jwitz commented on guides/airflow-components.md
> +- **[Executor](https://airflow.apache.org/docs/apache-airflow/stable/executor/index.html):** The mechanism for running tasks. An executor is running at all times Airflow is up (it runs within the Sch
```suggestion
- **[Executor](https://airflow.apache.org/docs/apache-airflow/stable/executor/index.html):** The mechanism for running tasks. An executor is running within the Scheduler whenever Airflow is up. In the section below, we walk through the different executors available and how to choose between them.
```

2022-03-16 14:47 UTC, merged