OpenLineage + Airflow guide
astronomer/airflow-guides pull request #349
Opened 2022-03-25 19:26 UTC by kentdanas

Hey @jwitz and @rossturk! Would love your review on this OpenLineage + Airflow guide. We will definitely make changes/additions to this as OpenLineage evolves, but were hoping to have something to publish next week to follow this week's announcements/coincide with the webinar, etc. So I've kept it a bit "bare bones", but hoping this adequately covers the "why?" and has enough info to get folks started.

2022-03-28 19:14 UTC, jwitz requested changes
I saw a draft of this early on - looked good then and looks better now! Thanks @kentdanas, this will be a really valuable guide to have on the site. Hope you don't mind if I borrow the "Concepts" and "Why OpenLineage with Airflow?" sections for the Astro docs, they're too good 😅 

I know this doc will be updated over time, but I do think we should mention something about the DK acquisition/ Astro functionality given that we're hoping to have that in production next week. I marked a few places where I think we could update that language, but besides that this LGTM

2022-03-28 19:14 UTC, jwitz commented on guides/airflow-openlineage.md
> +For this example, we’ll run Airflow with OpenLineage and Marquez locally following the steps below. You will need Docker and the [Astro CLI](https://docs.astronomer.io/cloud/install-cli) installed be
```suggestion
For this example, we’ll run Airflow with OpenLineage and Marquez locally. You will need to install Docker and the [Astro CLI](https://docs.astronomer.io/cloud/install-cli) before starting.
```

2022-03-28 19:14 UTC, jwitz commented on guides/airflow-openlineage.md
> +1. Run Marquez locally using their [quickstart instructions](https://github.com/MarquezProject/marquez#quickstart): clone the repo, then run `./docker/up.sh` from the root directory.
```suggestion
1. Run Marquez locally using the quickstart in the [Marquez README](https://github.com/MarquezProject/marquez#quickstart).
```

2022-03-28 19:14 UTC, jwitz commented on guides/airflow-openlineage.md
> +2. Start an astro project using the CLI by creating a new directory and running `astrocloud dev init`.
```suggestion
2. Start an Astro project using the CLI by creating a new directory and running `astrocloud dev init`.
```

2022-03-28 19:14 UTC, jwitz commented on guides/airflow-openlineage.md
> +3. Add `openlineage-airflow` to your `requirements.txt` file. Note if you are using Astronomer Runtime 4.0.9 or greater, this package is already included.
```suggestion
3. Add `openlineage-airflow` to your `requirements.txt` file. Note if you are using Astro Runtime 4.0.9 or greater, this package is already included.
```

2022-03-28 19:14 UTC, jwitz commented on guides/airflow-openlineage.md
> +    Port 5000 is used by Marquez by default when you run it using Docker in Step 1. If you are not using Marquez and are using a different OpenLineage front end, or are running Marquez remotely, you
```suggestion
    By default, Marquez uses port 5000 when you run it using Docker. If you are using a different OpenLineage front end instead of Marquez, or you are running Marquez remotely, you can modify the `OPENLINEAGE_URL` as needed.
```

2022-03-28 19:14 UTC, jwitz commented on guides/airflow-openlineage.md
> +- Only the following operators have bundled extractors (needed to collect lineage data out of the box):
Maybe we should add another point here like "To get lineage from an external system connected to Airflow, such as Spark, you need to complete an integration with that system in addition to Airflow".

2022-03-28 19:22 UTC, kentdanas commented on guides/airflow-openlineage.md
> +According to [Datakin](https://datakin.com/), the creators of the OpenLineage standard and leaders in the data lineage space, data lineage is “the complicated set of relationships between datasets”.
Great question. @rossturk do you have a sense of what our language should be around Datakin now post-announcement? Do we still refer to it as a separate entity, will our websites be integrated, etc.?

2022-03-28 19:26 UTC, kentdanas commented on guides/airflow-openlineage.md
> +If you are using data lineage, you will likely have a lineage tool that collects lineage metadata, as well as a front end for visualizing the lineage graph. There are paid tools (including Datakin) t
I originally had a section in here for lineage on Astro, but took it out for now since that isn't available just yet. I don't want to hold up publishing the guide since we wanted it for marketing/PR purposes this week. But as soon as we have something in Astro I plan to update to reference that.

2022-03-28 19:32 UTC, kentdanas commented on guides/airflow-openlineage.md
> +- Only the following operators have bundled extractors (needed to collect lineage data out of the box):
Good call, added that bullet with some relevant links

2022-03-28 19:39 UTC, kentdanas commented
Thanks for the review @jwitz! Left an open question for Ross on language re: datakin acquisition, but otherwise I think I addressed everything.

re: Astro, I mentioned in another comment, but we wanted to publish this guide this week (for marketing, and to have before the webinar next tuesday), so I don't want to hold it up for adding Astro-specific pieces (especially for the off chance that the rollout to prod gets pushed back). But as soon as that's rolled out (even if just next week), I'll make some updates!

2022-03-29 02:00 UTC, rossturk approved these changes
@kentdanas This is superb! It's a solid guide and I really enjoyed reading it. I left a few notes with my thoughts, nothing essential.

I am unsure whether this guide should draw a distinction between the "lineage frontend" and the "lineage backend". If that's not useful, perhaps we should consider using the more encompassing phrase "lineage system" instead since there is, architecturally-speaking, a backend.

2022-03-29 15:11 UTC, kentdanas commented on guides/airflow-openlineage.md
> +According to [Datakin](https://datakin.com/), the creators of the OpenLineage standard and leaders in the data lineage space, data lineage is “the complicated set of relationships between datasets”.
Sounds good, will update to that language. When I originally wrote it I mostly wanted to make sure I wasn't plagiarizing directly from Datakin's stuff, but it's a little easier now that we're publishing stuff together :)

2022-03-29 15:13 UTC, kentdanas commented on guides/airflow-openlineage.md
> +- **A lineage frontend** that allows you to view and interact with your lineage metadata, including a graph that visualizes your jobs and datasets and shows how they are connected.
Good call, added that bullet

2022-03-29 15:18 UTC, kentdanas commented on guides/airflow-openlineage.md
> +import random
Nope, a leftover from playing with Willy's example :)

2022-03-29 15:45 UTC, kentdanas commented
Thanks @rossturk for your review! I made some minor updates based on your comments. Sounds like blog post is coming Thursday, so as soon as that is published I'll update the link and get this merged!

2022-03-31 15:20 UTC, merged