First draft updated guide on hooks
astronomer/airflow-guides pull request #376
Opened 2022-05-20 17:09 UTC by TJaniF

This is the first draft of an updated version of the Hooks 101 guide including instructions how to install hooks, a description of the S3Hook including its currently available methods, and an example DAG using the S3Hook and the SlackHook.

2022-05-23 20:59 UTC, kentdanas requested changes
@TJaniF this is a great start! I left some comments throughout, mostly about high level organization to pull this more in line with some of our other (recent) guides. Let me know if you have questions about any of the requested updates.

2022-05-23 20:59 UTC, kentdanas commented on guides/what-is-a-hook.md
>  ## Hooks
Love the content in this! I think we can rearrange it a bit to be consistent with some of our other guides in terms of flow/sections (not all of them follow a pattern, but we try to be consistent with the newer ones). Check out the Sensors 101 guide as an example: https://www.astronomer.io/guides/what-is-a-sensor

I'm thinking for this one we could have:

- Overview (basically your intro, plus a short "in this guide, we'll cover....")
- Hook Basics (basically your Example: S3Hook section, but maybe a bit more general. More comments on this below)
- When to Use Hooks (short section describing practically when hooks are used e.g. if an operator doesn't exist, etc. these can be bullet points without code examples)
- Example Implementation (the example DAG you provide)

2022-05-23 20:59 UTC, kentdanas commented on guides/what-is-a-hook.md
> +To interact with data source and destination systems, Operators have to communicate with varying APIs. This is where hooks come in as a way to make handling connections more standardized and easier b
Maybe we can rewrite this first paragraph to be a bit more "hook-forward", something like "[Hooks](https://airflow.apache.org/docs/apache-airflow/stable/concepts/connections.html#hooks) are one of the most basic concepts of Airflow. At a high level, hooks are an abstraction of an API that allows Airflow to interface with an external system. Hooks are the building blocks of operators, but they can also be used themselves in DAG code." 

Or something like that, and then have a second short paragraph that describes what we'll cover in the guide.

2022-05-23 20:59 UTC, kentdanas commented on guides/what-is-a-hook.md
> +### Install
I think we can move this down within the Example Implementation section where you have the example DAG below. It's definitely worth noting that you have to install relevant provider packages to use most hooks, but probably doesn't need it's own high level section in the guide.

2022-05-23 20:59 UTC, kentdanas commented on guides/what-is-a-hook.md
> +### Example: S3Hook
Let's rewrite this section to be more general "Hook Basics". I think the most important things to cover are:

- Hooks are abstractions on APIs
- Hooks are used to make connections to external systems
- Hooks can also have other methods for interacting with those systems, and these will vary by each hook

A lot of this is already in here, but I think we can make it less S3 specific and a little clearer. Also, I don't think we need to show every method in the Hook (I know it was this way before, but I don't think it's super helpful). Maybe just highlight a few of the additional methods as an example.

2022-05-23 20:59 UTC, kentdanas commented on guides/what-is-a-hook.md
> +
This is a great example! Let's describe up front why you would want to write a DAG this way using Hooks (as opposed to using specific operators) - I'm guessing because you can't pass information between S3ListKeys (or whatever it's called) operator and SlackWebhookOperator in the way you're showing here, but we should make that explicit

2022-05-24 10:38 UTC, TJaniF commented on guides/what-is-a-hook.md
> +
I expanded the example to include a third task in between the two Hooks that uses the output from the S3Hook (that now reads three files from the S3) and provides input to the SlackHook, as well as added in the return of the Slack API response because otherwise one could just use the SlackAPIPostOperator.

2022-05-24 10:43 UTC, TJaniF commented
I rearranged the content in the way suggested and expanded the example DAG so the use-case is not covered by existing Operators.

2022-05-24 21:05 UTC, kentdanas requested changes
@TJaniF this is looking really good! Thanks for your updates!

Overall I think the content here is good. I went through and made some suggested edits, mostly small things. (I suggest reviewing them from the `Files changed` tab and batching them, so you don't have a commit and trigger the CI for every single one :) )

I'll also request a copy edit from @jwitz who usually reviews our guides before we publish them.

2022-05-24 21:05 UTC, kentdanas commented on guides/what-is-a-hook.md
> +Next you will need to set up the connection to the S3 bucket and Slack in the Airflow UI (localhost:8080 by default).
```suggestion
Next you will need to set up the connection to the S3 bucket and Slack in the Airflow UI.
```

2022-05-24 21:05 UTC, kentdanas commented on guides/what-is-a-hook.md
> +```
Maybe just add one final sentence or two here describing the specific Hooks used for accomplishing the use case? Check out this guide as an example (it describes the DAG's steps before the code, which would also be fine): https://www.astronomer.io/guides/dynamic-tasks#example-implementations

2022-05-24 21:05 UTC, kentdanas commented on guides/what-is-a-hook.md
> +
Looks great!

2022-05-25 07:44 UTC, TJaniF commented on guides/what-is-a-hook.md
> +date: 2022-05-24T00:00:00.000Z
That does make sense, I changed it back :)

2022-05-25 07:47 UTC, TJaniF commented on guides/what-is-a-hook.md
> +```
I added a description of the DAGs steps at the end of the document and included which Hooks were used with which methods there.

2022-05-25 18:47 UTC, kentdanas approved these changes
Thanks @TJaniF, this looks great! One more minor comment, otherwise I'll hand off to Jake for a copy edit.

@jwitz you mind giving this a read when you have a minute?

2022-05-26 16:02 UTC, jwitz approved these changes
@TJaniF This guide is great! Such a huge improvement over our existing Hooks guide - I was able to immediately figure out why Hooks are important and how to use them.

Don't be alarmed by the number of suggestions here, basically all of them are minor copy changes. Feel free to tag me again if you have any questions or if one of my suggestions missed the mark.

2022-05-26 16:02 UTC, jwitz commented on guides/what-is-a-hook.md
> +The DAG below uses [Airflow Decorators](https://registry.astronomer.io/guides/airflow-decorators) to define tasks and [XCom](https://registry.astronomer.io/guides/airflow-passing-data-between-tasks)
```suggestion
The DAG below uses [Airflow Decorators](https://registry.astronomer.io/guides/airflow-decorators) to define tasks and [XCom](https://registry.astronomer.io/guides/airflow-passing-data-between-tasks) to pass information between them. The name of the S3 bucket and the names of the files that the first task reads are stored as environment variables for security purposes.
```

2022-05-26 16:02 UTC, jwitz commented on guides/what-is-a-hook.md
> +The DAG below uses [Airflow Decorators](https://registry.astronomer.io/guides/airflow-decorators) to define tasks and [XCom](https://registry.astronomer.io/guides/airflow-passing-data-between-tasks)
```suggestion
The DAG below uses [Airflow Decorators](https://registry.astronomer.io/guides/airflow-decorators) to define tasks and [XCom](https://registry.astronomer.io/guides/airflow-passing-data-between-tasks) to pass information between them. The name of the S3 bucket and the names of the files that the first task reads are stored as environment variables for security purposes.
```

2022-05-26 16:02 UTC, jwitz commented on guides/what-is-a-hook.md
> +3. Post the result of the check to a Slack Channel using the `call` method of the SlackHook and return the response from the Slack API.
```suggestion
1. Use a decorated Python Operator with a manually implemented `S3Hook` to read three specific keys from S3 with the `read_key` method. Returns a dictionary with the file contents converted to integers.
2. With the results of the first task, use a second decorated Python Operator to complete a simple sum check. 
3. Post the result of the check to a Slack channel using the `call` method of the SlackHook and return the response from the Slack API.
```

2022-05-26 16:02 UTC, jwitz commented on guides/what-is-a-hook.md
> +3. Post the result of the check to a Slack Channel using the `call` method of the SlackHook and return the response from the Slack API.
```suggestion
1. Use a decorated Python Operator with a manually implemented `S3Hook` to read three specific keys from S3 with the `read_key` method. Returns a dictionary with the file contents converted to integers.
2. With the results of the first task, use a second decorated Python Operator to complete a simple sum check. 
3. Post the result of the check to a Slack channel using the `call` method of the SlackHook and return the response from the Slack API.
```

2022-05-26 18:22 UTC, TJaniF commented
@jwitz Thank you! :)

2022-05-26 18:23 UTC, merged