Updated logging guide
astronomer/airflow-guides pull request #380
Opened 2022-05-31 11:59 UTC by TJaniF

This is the first draft of an updated guide to logging. Chapters: Logging Basics, Logging in Airflow, Why to configure logging, How to configure logging, Logging remotely, Example (logging to S3), Logging display, Custom Handlers and Default config.

2022-05-31 23:43 UTC, kentdanas requested changes
@TJaniF tons of great info in here, thanks for wading through all of this! I think this is going to be super helpful. I made some high level comments about content, mostly to move a few things around and add some use-case based context throughout. Let me know if you want to talk about any of my comments, and we can go from there!

2022-05-31 23:43 UTC, kentdanas commented on guides/logging.md
> +## Logging Basics
I'm wondering if we can either cut down on this section and/or roll it into the Logging in Airflow section. Some definitions of terms used are definitely helpful, but on the other hand, most people reading these guides will be looking for help implementing something specific, so we want to balance background info with instructional content. This may be something where we link out to other docs and leave most of the explanation to those, if people want it.

2022-05-31 23:43 UTC, kentdanas commented on guides/logging.md
> +## Logging in Airflow
I think it would be helpful in this section to put things in terms of what sorts of logs are generated by each logger. Most Airflow users will care about task logs and scheduler logs the most, so indicating where those are generated will be useful. e.g. something like "if you need to debug a failing scheduler, you would want to look at these logs" in whatever section is relevant.

2022-05-31 23:43 UTC, kentdanas commented on guides/logging.md
> +The current task handler and logging configuration can be found running the following commands:
I would specify that this is using the Airflow CLI

2022-05-31 23:43 UTC, kentdanas commented on guides/logging.md
> +Advanced configuration might necessitate the logging config class to be overwritten. To enable custom logging config a configuration file `~/airflow/config/log_config.py` has to be created in which m
Can we add an example use case when you might want to do this (maybe the same one you present in the remote logging example?)? Just a sentence like "You may need to do this if you are ...."

2022-05-31 23:43 UTC, kentdanas commented on guides/logging.md
> +
I think adding a super brief example of changing a logging parameter for a particular use case would be helpful (ideally corresponding to one of the bullet points in the Why section). Doesn't need to be long, just a couple of sentences about "For example, if you wanted to modify logging for xyz purpose, you could update xyz in the config...."

2022-05-31 23:43 UTC, kentdanas commented on guides/logging.md
> +It is important to note that logs are only sent to remote storage once a task has been completed (including in case of failure), this means you will only be able to see the logs of currently running
I believe you can only see logs for running tasks with certain implementations of Airflow (like ours, which uses elasticsearch for this purpose). Worth confirming though, I could be wrong.

2022-05-31 23:43 UTC, kentdanas commented on guides/logging.md
> +There are implementations for writing task logs to a remote destination for a number of community-managed providers:
Can we add a sentence or two here about why you would want to set up remote logging? Scalability and resilience are the big things that come to my mind.

2022-05-31 23:43 UTC, kentdanas commented on guides/logging.md
> +## Logging display
I think we should incorporate this section into the Logging in Airflow section above, rather than having it be its own section.

2022-05-31 23:43 UTC, kentdanas commented on guides/logging.md
I think we would want to talk more about when you would want to create a custom handler here. Alternatively, do you think this section is necessary for most average Airflow users, or would it be considered pretty advanced? Maybe we don't devote as much space to it if we think most users wouldn't need it.

2022-05-31 23:43 UTC, kentdanas commented on guides/logging.md
> +## Beyond Logging
I think rather than have a separate section for this we could add a note (using the `>  Note` syntax so it stands out) that says there are other monitoring options within Airflow and then link to the Airflow docs and maybe also our monitoring docs.

2022-05-31 23:43 UTC, kentdanas commented on guides/logging.md
> +## Airflow's default logging configuration for reference
This is somewhere in the Airflow code, right? If so, do you think we can just link out to the code in a note in the Logging in Airflow section? That way if it changes, we don't have to worry about the guide being out of date.

2022-06-02 20:50 UTC, TJaniF commented on guides/logging.md
> +It is important to note that logs are only sent to remote storage once a task has been completed (including in case of failure), this means you will only be able to see the logs of currently running
I was actually able to get the output from running tasks in local airflow, it is a .log file that gets appended in real time (even if I have it open interestingly).
![Screenshot 2022-06-02 at 22 50 08](https://user-images.githubusercontent.com/90063506/171735713-6927ff18-5c84-421d-bf99-582a5512a435.png)

2022-06-03 18:10 UTC, kentdanas requested changes
@TJaniF this is looking really good! Added a few more comments (most of them minor), and a few copy edits, but I think content-wise this is in a great place. Very helpful background and examples while still being easily digestible. 

I'm going to ask @pgagnon to give it a quick read for content since he's more of a SME than I am :). @pgagnon if you wouldn't mind letting us know if all of the info in here looks accurate that would be super helpful. 

After that and any minor edits for my comments we can move on to copy editing!

2022-06-03 18:10 UTC, kentdanas commented on guides/logging.md
> +After completing step 1 and 2 from the example above add the following commands to your Dockerfile:
```suggestion
First, complete Steps 1 and 2 from the section above to configure your Airflow environment for S3 remote logging. Then, add the following commands to your Dockerfile:
```

2022-06-03 18:10 UTC, kentdanas commented on guides/logging.md
> +Create a `log_config.py` file outside of your /dags/ folder and use it to create and modify a deepcopy of `DEFAULT_LOGGING_CONFIG`:
Can we add a sentence here briefly describing what these environment variables will do? e.g. "This will configure remote logging to two separate S3 buckets, `AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER` and `AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER_2`.

2022-06-03 18:10 UTC, kentdanas commented on guides/logging.md
> +Create a `log_config.py` file outside of your /dags/ folder and use it to create and modify a deepcopy of `DEFAULT_LOGGING_CONFIG`:
```suggestion
Next, create a `log_config.py` file outside of your /dags/ folder and use it to create and modify a deep copy of `DEFAULT_LOGGING_CONFIG`:
```

Can we be more specific about where the file should go than just "outside of the DAGs folder". Is it somewhere in the Airflow project as long as it's not in `dags/`?

2022-06-03 18:10 UTC, kentdanas commented on guides/logging.md
> +Afterwards don't forget to restart your Airflow environment and run any task to verify that the task logs are copied to your S3 buckets.
Same comment here, can we add a brief sentence or two describing what these updates do?

2022-06-03 18:10 UTC, kentdanas commented on guides/logging.md
> +## Log locations
```suggestion
## Log Locations
```

2022-06-03 18:10 UTC, kentdanas commented on guides/logging.md
> +## Adding task logs
```suggestion
## Adding Task Logs
```

2022-06-03 18:10 UTC, kentdanas commented on guides/logging.md
> +## Why to configure logging
```suggestion
## Why to Configure Logging
```

2022-06-03 18:10 UTC, kentdanas commented on guides/logging.md
> +## How to configure logging
```suggestion
## How to Configure Logging
```

2022-06-03 18:10 UTC, kentdanas commented on guides/logging.md
> +## Logging remotely
```suggestion
## Logging Remotely
```

2022-06-03 18:10 UTC, kentdanas commented on guides/logging.md
> +## Example: Remote logging of tasks to S3 using Astro CLI
```suggestion
## Remote Logging Example: Sending Task Logs to S3
```

2022-06-03 18:10 UTC, kentdanas commented on guides/logging.md
> +## Example Advanced configuration: Add a multiple handlers to the same logger
```suggestion
## Advanced Configuration Example: Add Multiple Handlers to the Same Logger
```

2022-06-06 07:30 UTC, TJaniF commented on guides/logging.md
> +More logging statements can be added from within your DAGs by accessing the `airflow.task` logger:
That is a really good question. I could not find a way to add log statements from any other place than from within python functions. I also tried using the airflow.processor logger to send logs to the scheduler but it seems to be ignoring them.

2022-06-06 09:23 UTC, TJaniF commented on guides/logging.md
> +It is important to note that logs are only sent to remote storage once a task has been completed (including in case of failure), this means you will only be able to see the logs of currently running
I see. I can see logs for currently running tasks in the UI both for local airflow and for Astro CLI.

2022-06-06 17:56 UTC, kentdanas reviewed
@TJaniF I think this looks good content-wise! I may see if we can find somebody from CRE to give it a quick glance since Phil is out for a few weeks.

But for now, @jwitz you mind giving this a copy edit?

2022-06-06 17:56 UTC, kentdanas commented on guides/logging.md
> +Please see the Python documentation for more information on [methods available for the classes above](https://docs.python.org/3/library/logging.html#logger-objects), attributes of a [LogRecord object
```suggestion
The Python documentation contains more information on [methods available for the classes above](https://docs.python.org/3/library/logging.html#logger-objects), attributes of a [LogRecord object](https://docs.python.org/3/library/logging.html#logrecord-objects), and the [6 levels of logging severity](https://docs.python.org/3/library/logging.html#logging-levels) (CRITICAL, ERROR, WARNING, INFO, DEBUG and NOTSET).
```

2022-06-06 17:56 UTC, kentdanas commented on guides/logging.md
> +If not otherwise specified log files will be named according to the following pattern, which can be configured as `log_filename_template` in `airflow.cfg`:
```suggestion
If not otherwise specified, log files will be named according to the following pattern, which can be configured as `log_filename_template` in `airflow.cfg`:
```

2022-06-06 17:56 UTC, kentdanas commented on guides/logging.md
> +3. Logs from worker logs webserver
Is this logs from workers or the webserver? I'm not clear on what 'worker logs webserver' is

2022-06-07 07:35 UTC, TJaniF commented on guides/logging.md
> +3. Logs from worker logs webserver
It refers to small webserver sub processes created for workers: https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#worker-log-server-port . Philippe used the term "worker logs webserver" in his presentation for it. I changed the wording and added the link to the Airflow docs, hope that makes it clearer.

2022-06-07 19:51 UTC, jwitz requested changes
Wow, what a guide update! Lots of comments, but only because there's so much new content here.

Requesting changes because I asked a few questions throughout, and I also want to see if you can reorganize the sections about configuring task logging to have a more natural progression. See my comments in those sections for more details.

2022-06-07 19:51 UTC, jwitz commented on guides/logging.md
> +The default location of logs which are outputted to the file system is specified as `base_log_folder` in `airflow.cfg` which is located in the `$AIRFLOW_HOME` directory.
We state this default, then jump to the Docker locations and then back to the default locations. Instead, can we clearly split this section up based on how you're running Airflow? You can use headers to help with this:

```
### Running Airflow Locally 

<All default file locations, including `base_log_folder` info>

### Running Airflow in Docker 

<all file locations when using Docker?

2022-06-07 19:51 UTC, jwitz commented on guides/logging.md
> +All hooks and operators in Airflow will generate logs when the task is run. The logs that are generated will vary for each specific module but you can also add additional logging statements from with
```suggestion
All hooks and operators in Airflow generate logs when a task is run. While it is currently not possible to modify logs from within other operators or in the top-level code, you can add custom logging statements from within your Python functions by modifying the `airflow.task` logger.
```

2022-06-07 19:51 UTC, jwitz commented on guides/logging.md
> +## Why to Configure Logging
```suggestion
## When to Use Custom Logging
```

2022-06-07 19:51 UTC, jwitz commented on guides/logging.md
> +Logging in Airflow is set up to be ready to use without any configuration being necessary. However, there are many use cases where customization of logging is beneficial. For example:
```suggestion
Logging in Airflow is ready to use without any additional configuration. However, there are many use cases where customization of logging is beneficial. For example:
```

2022-06-07 19:51 UTC, jwitz commented on guides/logging.md
> +For these providers Airflow contains logic to overwrite your task handler (`FileTaskHandler`) with the corresponding remote destination task handler (for example `GCSTaskHandler`) if you provide a va
```suggestion
By configuring `REMOTE_BASE_LOG_FOLDER`, you can override the default task handler (`FileTaskHandler`) to send logs to a remote destination task handler (for example `GCSTaskHandler`.
```

2022-06-07 19:51 UTC, jwitz commented on guides/logging.md
> +If you want different behavior or add several handlers to one logger you will need to make changes to `DEFAULT_LOGGING_CONFIG` as described in the [Airflow documentation](https://airflow.apache.org/d
```suggestion

To map multiple different remote logging services to a single logger, you need to make changes to `DEFAULT_LOGGING_CONFIG` as described in the [Airflow documentation](https://airflow.apache.org/docs/apache-airflow/stable/logging-monitoring/logging-tasks.html#advanced-configuration).
```

2022-06-07 19:51 UTC, jwitz commented on guides/logging.md
> +If you want different behavior or add several handlers to one logger you will need to make changes to `DEFAULT_LOGGING_CONFIG` as described in the [Airflow documentation](https://airflow.apache.org/d
Why are we linking to the Airflow documentation here instead of our advanced example below?

2022-06-07 19:51 UTC, jwitz commented on guides/logging.md
> +Additionally a second remote log folder `AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER_2` is set as an environmental variable to be retrieved from within `log_config.py`. Importantly the `AIRFLOW__LOGGING
```suggestion
Additionally a second remote log folder `AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER_2` is set as an environment variable to be retrieved from within `log_config.py`. Importantly, the `AIRFLOW__LOGGING__LOGGING_CONFIG_CLASS` is replaced with your custom `LOGGING_CONFIG` class that you will define in the next step.
```

2022-06-08 21:51 UTC, TJaniF reviewed
Thank you @jwitz for all the great suggestions! The text looks much cleaner now :) 
(also sorry for apparently calling environment variables "environmental variables" until today).

2022-06-08 21:51 UTC, TJaniF commented on guides/logging.md
> +Additionally to standard logging, there are a variety of other monitoring options when using Airflow that let you collect metrics, use tasks events to trigger callback functions, monitor Airflow heal
That is a good point! I'll try to keep that in mind for the flow of future docs too!

2022-06-08 21:51 UTC, TJaniF commented on guides/logging.md
> +The Python documentation contains more information on [methods available for the classes above](https://docs.python.org/3/library/logging.html#logger-objects), attributes of a [LogRecord object](http
Noted!

2022-06-08 21:51 UTC, TJaniF commented on guides/logging.md
> +> **Note:** If a Kubernetes Executer was used and the Worker pod still exists `read()` will display the first 100 lines from Kubernetes pod logs, if the Worker pod ceased to exists those logs will be
I discussed this with Kenten today and Kubernetes logging is a whole topic in itself so I added a link to Kubernetes doc page on that.

2022-06-08 21:51 UTC, TJaniF commented on guides/logging.md
> +The default location of logs which are outputted to the file system is specified as `base_log_folder` in `airflow.cfg` which is located in the `$AIRFLOW_HOME` directory.
I really like that idea, looks much more organized now! :)

2022-06-08 21:51 UTC, TJaniF commented on guides/logging.md
> +The DAG above shows how to log at different levels of severity from within a custom python function. The logs for the `extract` task will show the following lines under the default Airflow logging co
In the example task the added logs don't really achieve anything other than showing the syntax for all the levels and from where you can add logs and from where you cannot. I added a sentence talking about some use cases :)

2022-06-08 21:51 UTC, TJaniF commented on guides/logging.md
> +## Why to Configure Logging
I discussed this with Kenten today and we'd like to keep the structure "how to add task logs", "why to configure", "how to configure", "config examples" because the people who need to add task logs (DAG authors) often will not have anything to do with the deeper configuration of airflow logging (maybe apart from setting the logging level down during dev), which is left to admins of the airflow instance. 

I think my wording of the title of the section with the example DAG was confusing and I tried to clarify it now and I removed the "changing logging level" from the "when to configure logging" since it was mentioned in the "how to add tasks" section. :)

2022-06-08 21:51 UTC, TJaniF commented on guides/logging.md
> +```
thank you!

2022-06-08 21:51 UTC, TJaniF commented on guides/logging.md
> +For full control over the logging configuration you will need to create and modify a `log_config.py` file. This is relevant for use cases such as adding several handlers to the same logger with diffe
I added a sentence listing 3 reasons why someone may want to do that. Generally every case where task logs are stored in more than one destination (whether it is an exact copy or changed logs like different severity or additional filters) would need two handlers. I don't know how commonly people actually have a setup like this but it was one of the clearest examples I found where creating a log_config.py file is necessary.

2022-06-09 15:42 UTC, jwitz approved these changes
Just a few remaining final comments, some of which are optional. Besides that LGTM ✅ thanks for reading through all of my comments, and great job taking on such a major guide revision!

2022-06-09 16:54 UTC, TJaniF commented on guides/logging.md
> +### Running Airflow locally
Is done :)

2022-06-09 16:57 UTC, TJaniF commented on guides/logging.md
> +## Adding Additional Task Logs from within a DAG
oh that alliteration was not on purpose, thanks for pointing it out 😂 . I changed the headers now to:

## Adding Custom Task Logs from within a DAG
## When to Configure Logging
## How to Configure Logging

so that there is a clear distinction between "adding something custom" which uses the default config and is more of a "user thing" to do and when and how to actually change the configuration, which is more for the admins. Hope that works :)

2022-06-09 17:45 UTC, kentdanas approved these changes
@TJaniF this looks so great! A couple of tiny edits, but otherwise this looks good to go to me! Feel free to hit 'merge' when you're ready :)

2022-06-09 17:45 UTC, kentdanas commented on guides/logging.md
> +By configuring `REMOTE_BASE_LOG_FOLDER` with a prefix of a supported provider (as listed above), you can override the default task handler (`FileTaskHandler`) to send logs to a remote destination tas
```suggestion
By configuring `REMOTE_BASE_LOG_FOLDER` with a prefix of a supported provider (as listed above), you can override the default task handler (`FileTaskHandler`) to send logs to a remote destination task handler (for example `GCSTaskHandler`).
```

2022-06-09 17:45 UTC, kentdanas commented on guides/logging.md
> +The advantage of using a logger over print statements is that you can log at different levels and control which logs are emitted to a specific location. For example, by default the `airflow.task` log
```suggestion
The advantage of using a logger over print statements is that you can log at different levels and control which logs are emitted to a specific location. For example, by default the `airflow.task` logger is set at the level of `INFO`, which means that logs at the level of `DEBUG` aren't logged. To see `DEBUG` logs when debugging your Python tasks, you simply need to set `AIRFLOW__LOGGING__LOGGING_LEVEL=DEBUG` or change the value of `logging_level` in `airflow.cfg`. After debugging, you can change the `logging_level` back to `INFO` without ever having to touch your DAG code.
```

2022-06-09 17:45 UTC, kentdanas commented on guides/logging.md
> +Logging in Airflow can be configured in `airflow.cfg` and by providing a custom `log_config.py` file. It is considered best practise to not declare configs or variables within the `.py` handler files
```suggestion
Logging in Airflow can be configured in `airflow.cfg` and by providing a custom `log_config.py` file. It is considered best practice to not declare configs or variables within the `.py` handler files except for testing or debugging purposes.
```

2022-06-09 17:45 UTC, kentdanas commented on guides/logging.md
> +Lastly, create a `log_config.py` file. While you can put this file anywhere in your Airflow project as long as it is not within a folder listed in `.dockerignore`, it is best practise to put it outsi
```suggestion
Lastly, create a `log_config.py` file. While you can put this file anywhere in your Airflow project as long as it is not within a folder listed in `.dockerignore`, it is best practice to put it outside of your `dags/` folder, such as `/include`, to prevent the scheduler wasting resources by continuously parsing the file. Make sure to adjust the COPY statement in the previous step depending on where you decide to store this file.
```

2022-06-09 17:45 UTC, kentdanas commented on guides/logging.md
> +This modified version of `DEFAULT_LOGGING_CONFIG` creates a second S3TaskHandler using the s3 location provided as `AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER_2`. It is configured with a custom `filena
```suggestion
This modified version of `DEFAULT_LOGGING_CONFIG` creates a second S3TaskHandler using the S3 location provided as `AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER_2`. It is configured with a custom `filename_template`, further customization is of course possible with regards to formatting, log level or additional filters.
```

2022-06-09 21:38 UTC, merged