First draft of an update to the KPO guide
astronomer/airflow-guides pull request #388
Opened 2022-06-21 22:01 UTC by TJaniF

Rough first draft of the structure and content. 

Comments:
- Requirements to use KPO: currently lists CeleryExecutor, KubernetesExecutor and CeleryKubernetesExecutor. I have not found examples using other executors yet with KPO but can't be sure it is not possible at this point.
- How to configure KPO: I described a variety of arguments, maybe too many. I tried to group them logically where possible and put the 4 args pertaining to connections below a subheader because I assume these are the most searched for
- Configuring Kubernetes Connection: Not 100% certain I understood this correctly but it seems like the move is towards using the Airflow connection and away from using arguments or specifying these parameters in airflow.cfg.
- KPO vs KubernetesExecutor: I found the info that K8sExecutor needs Airflow to be installed in the Dockerimage in one of Marc's blog posts. Is this still accurate? 
- KPO local development: As discussed I only give rough steps here for how to set up running Airflow on K8s locally. I do have the step-by-step for newbies (for me) list in my files so I can easily expand on that if necessary.
- KPO best practices: as discussed this section is incomplete, I listed the suggestions from the issue.
- Example: Spinning up a pod in the same cluster: I was wondering since this is pretty straight forward if we want to expand this example a bit, maybe including XCom usage? On the other hand it might be better to have a short example like this. 
- Example: Spinning up a pod in EKS from Airflow: I included all steps here, some of which might be obvious to more experienced AWS users and can be deleted. Currently I am still stuck at the nodegroup not starting, so there might be changes if there is something wrong with the steps I took. I do not know how the service account interacts with the AWS connection yet, I'll add that if/when I find out. 

Sorry for the wall of text 😅

2022-06-22 17:49 UTC, kentdanas commented on guides/kubepod-operator.md
> +## KPO local development
Now that I'm reading this, for general flow I think it would make sense to have this as a subsection under Requirements to Use KPO. So at a high level we would have infra/environment requirements -> when/how to use the operator -> best practices and specific examples

2022-06-22 17:51 UTC, kentdanas commented on guides/kubepod-operator.md
> +## KPO vs KubernetesExecutor
Maybe this section should go as a subsection under When to Use KPO? I think that would flow well if we expand on the use cases a bit

2022-06-22 17:55 UTC, kentdanas commented on guides/kubepod-operator.md
> +## How to configure KPO
I don't think you have too many parameters described here, but I do think we should intro this section with a bit more context on what the KPO is doing - e.g. the work the task actually does is run the docker image you provide, and all other parameters are specific to the pod configuration. And that through the parameters you have access to everything available in the k8s API and then link to that.

2022-06-22 17:59 UTC, kentdanas commented on guides/kubepod-operator.md
> +## KPO local development
Another comment on this section - for the instructions, we should probably either make them more detailed or keep it very high level and not have steps. I'm kind of leaning towards the latter, and keeping this section pretty short and maybe linking out to other resources (so we can focus the guide more on the operator itself and use cases). But would love your opinion here having just learned it and worked with it.

2022-06-22 19:14 UTC, kentdanas commented on guides/kubepod-operator.md
> +## How to configure KPO
Also, I think it would be helpful to present some of these parameters in the context of a simple example. Maybe running a 'hello world' script in some other language - then talk about what would be in the image, how you would set up the pod, etc.

2022-06-23 08:58 UTC, TJaniF commented on guides/kubepod-operator.md
> +## KPO local development
Yes I agree, a more detailed explanation would feel out of place here and distract from the KPO itself. 

I would have been lost without Marc's blogpost in setting this up (the official docs only provide instructions on how to install the helm chart but not the full setup) and just found a webinar on the Astronomer channel containing the same content. I think linking to that works? :)

2022-06-24 18:57 UTC, kentdanas commented on guides/kubepod-operator.md
> +## KPO local development
Ah I had forgotten we did a webinar on that - great idea to link out to that one :)

2022-06-24 20:27 UTC, kentdanas requested changes
@TJaniF this is great!! Amazing work on this, k8s is a tough topic and there's so much helpful stuff in here!

I left a bunch of comments, but most of them are small edits and style things. Content-wise I think we're very close. Let's chat next week on the best practices section. I want to review the issues that have been submitted again, but I'm honestly wondering if a separate section for this is really necessary, and if it wouldn't be better just to add a couple of comments on best practices in the examples if we need to address something specific.

And one more thing - I generally put the names of operators and executors in fences in our guides, e.g. `KubernetesPodOperator` and `KubernetesExecutor`, so unless Jake says otherwise for styling, I think we should do the same here. Figured it would be easier for you to do a find and replace than for me to correct them :) (and note that 'KPO' would stay as just plain text wherever you have it abbreviated)

2022-06-24 20:27 UTC, kentdanas commented on guides/kubepod-operator.md
> +The Dockerfile uses `cabal` as a system for building and packaging Haskell programs, for this example the `haskell_example.cabal` file built automatically when running `cabal init` in a directory nam
```suggestion
The Dockerfile creates the necessary environment to run the script and then executes it with a `CMD` command.
```
I know the context you had is relevant for the actual content of the example, but for the purposes of what we're trying to show I think we can keep it more general.

2022-06-24 20:27 UTC, kentdanas commented on guides/kubepod-operator.md
> +After making the Docker image available it is possible to launch it from the KPO via the `image` argument. The example DAG below showcases a variety of arguments of the KubernetesPodOperator includin
```suggestion
After making the Docker image available it can be run from the KPO via the `image` argument. The example DAG below showcases a variety of arguments of the KubernetesPodOperator, including how to pass the environment variable `NAME_TO_GREET` which is used from within the Haskell code.
```

2022-06-24 20:27 UTC, kentdanas commented on guides/kubepod-operator.md
> +The DAG below shows a straightforward ETL pipeline with an `extract_data` task simulating running a query on a database and returning one value that by being returned from the Python function is auto
```suggestion
The DAG below shows a straightforward ETL pipeline with an `extract_data` task that runs a query on a database and returns a value; the return value is automatically pushed to XComs thanks to the [TaskFlow API](https://airflow.apache.org/docs/apache-airflow/stable/tutorial_taskflow_api.html#tutorial-on-the-taskflow-api).  
```

2022-06-24 20:27 UTC, kentdanas commented on guides/kubepod-operator.md
> +The `transform` task is a KubernetesPodOperator which launches an image having been built with the following Dockerfile:
```suggestion
The `transform` task is a KubernetesPodOperator which requires the XCom data pushed from the upstream task before it, and launches an image having been built with the following Dockerfile:
```

2022-06-24 20:27 UTC, kentdanas commented on guides/kubepod-operator.md
> +However you may want to use a specific AWS or GCP account that you keep separate from your Airflow environment. Or you are currently running Airflow on a local setup not using Kubernetes but still wa
```suggestion
However, you may want to use a specific AWS or GCP account that you keep separate from your Airflow environment. Or you are currently running Airflow on a local setup not using Kubernetes, but still want to run some tasks in a Kubernetes pod on a remote cluster.
```

2022-06-24 20:27 UTC, kentdanas commented on guides/kubepod-operator.md
> +The example below shows the steps to take to set up an EKS cluster on AWS and run a Pod on it from an Airflow instance if cross-account access is not feasible. After setup of the EKS cluster the `Kub
```suggestion
The example below shows the steps to take to set up an EKS cluster on AWS and run a pod on it from an Airflow instance where cross-account access is not feasible. After setup of the EKS cluster, the `KubeConfig` as well as the `AWS Profile` have to be provided to Airflow to make the connection to the remote cluster. Note that the same general steps are applicable to other Kubernetes services (e.g. GKE).  
```

2022-06-24 20:27 UTC, kentdanas commented on guides/kubepod-operator.md
> +> **Note**: If you are using [Google Kubernetes Engine](https://cloud.google.com/kubernetes-engine/) consider using [GKEStartPodOperator](https://registry.astronomer.io/providers/google/modules/gkest
I'm not super familiar with these operators and how they work, and I don't think they're very common, so I'm wondering if we should not recommend them and remove these notes. what do you think?

2022-06-24 20:27 UTC, kentdanas commented on guides/kubepod-operator.md
> +The `KubeConfig` file is how the KPO will connect to a Kubernetes cluster by running the awscli with the default profile, using the credentials you provided in step 1.
```suggestion
The `KubeConfig` file is how the KPO will connect to a Kubernetes cluster by running the `awscli` with the default profile, using the credentials you provided in Step 1.
```

2022-06-24 20:27 UTC, kentdanas commented on guides/kubepod-operator.md
> +### Step 3 Add a namespace and service account to the EKS Cluster
```suggestion
### Step 3: Add a namespace and service account to the EKS Cluster
```

2022-06-24 20:27 UTC, kentdanas commented on guides/kubepod-operator.md
> +It is best practice to use a new namespace for all Pods sent to the EKS cluster from the Airflow environment and a separate service account.
```suggestion
It is best practice to use a new namespace and separate service account for all pods sent to the EKS cluster from the Airflow environment.  
```

2022-06-24 20:27 UTC, kentdanas commented on guides/kubepod-operator.md
> +### Step 4 Adjust Airflow configuration files
```suggestion
### Step 4: Adjust the Airflow configuration files
```

2022-06-24 20:27 UTC, kentdanas commented on guides/kubepod-operator.md
> +For dockerized settings add the following line to your Dockerfile to copy your aws credentials from `/include` (or any other location) into the container:
```suggestion
If you are running Airflow with Docker, add the following line to your Dockerfile to copy your aws credentials from `/include` (or any other location) into the container:
```
Is this edit correct?

2022-06-24 20:27 UTC, kentdanas commented on guides/kubepod-operator.md
> +This step will differ depending on the Airflow setup. When running Airflow locally it is just necessary to make sure `awscli`, `apache-airflow-providers-cncf-kubernetes`,
```suggestion
This step will differ depending on the Airflow setup. When running Airflow locally, it is necessary to make sure `awscli`, `apache-airflow-providers-cncf-kubernetes`,
```

2022-06-24 20:27 UTC, kentdanas commented on guides/kubepod-operator.md
> +### Step 5 Add AWS connection ID
```suggestion
### Step 5: Add AWS connection ID
```

2022-06-24 20:27 UTC, kentdanas commented on guides/kubepod-operator.md
> +In the Airflow UI navigate to **Admin** -> **Connections** to set up the connection to the AWS account running the EKS. Chose a unique connection ID and use your `aws_access_key_id` as login and your
```suggestion
In the Airflow UI navigate to **Admin** -> **Connections** to set up the connection to the AWS account running the target EKS cluster. Chose a unique connection ID and use your `aws_access_key_id` as login and your `aws_secret_access_key` as password.
```

2022-06-24 20:27 UTC, kentdanas commented on guides/kubepod-operator.md
> +### Step 2 Retrieve the KubeConfig file from the EKS cluster
```suggestion
### Step 2: Retrieve the KubeConfig file from the EKS cluster
```

2022-06-24 20:27 UTC, kentdanas commented on guides/kubepod-operator.md
> +### Step 6 Add the DAG interacting with EKS
```suggestion
### Step 6: Create the DAG with the KPO 
```

2022-06-24 20:27 UTC, kentdanas commented on guides/kubepod-operator.md
> +The example DAG contains 5 consecutive tasks. The first one creates a Nodegroup according to the users' specifications and afterwards a sensor checks that the cluster is running correctly. The third
Can we bullet or number list the descriptions of the 5 tasks? I try to follow Jake's rule of listing any time there are more than 3 items :)

2022-06-27 17:49 UTC, TJaniF reviewed
I hope I did not miss a comment 😅. 

Some notes: 
- The bug fix for remote KPO launching is still in progress, so I am waiting on that fix to be deployed to test what steps of the examples wont be necessary anymore.
- I asked Jake and both Pod and Node should be capitalized according to the Google style guide, open source is lower case and there has been a mention of worker queues in a "Coming Soon" doc, but he will evaluate the note about it once he sees it, so I left it in for now.

2022-06-27 17:49 UTC, TJaniF commented on guides/kubepod-operator.md
> +> **Note**: If you are using [Google Kubernetes Engine](https://cloud.google.com/kubernetes-engine/) consider using [GKEStartPodOperator](https://registry.astronomer.io/providers/google/modules/gkest
Hmm... I am unsure what is best. I've not used the GKEStartPodOperator but tried to get the EksPodOperator to run and it keeps not recognizing the name of my cluster; as far as I can tell both are just supposed to make the connection easier but not adding any functionality.
 
I think from a user perspective the note is not really necessary because most will use the KPO unless the specifically are looking for a platform-specific Operator in the registry. I mostly added the note for internal consistency because of the "use the more specific operator if it exists"-rule and because Jeff pointed out that I could use the EksPodOperator. 😅 

Maybe a compromise between recommending and not mentioning would be to say something along the lines of "these two more specific operators exist if you want to check them out here are the links"?

2022-06-27 21:31 UTC, kentdanas commented on guides/kubepod-operator.md
> +```
Yes exactly :)

2022-06-27 21:33 UTC, kentdanas commented
> * I asked Jake and both Pod and Node should be capitalized according to the Google style guide, open source is lower case and there has been a mention of worker queues in a "Coming Soon" doc, but he will evaluate the note about it once he sees it, so I left it in for now.

Oh interesting, we probably have a bunch of other guides where 'Pod' should be capitalized then. Sorry for all the incorrect corrections!

2022-06-27 21:36 UTC, kentdanas commented on guides/kubepod-operator.md
> +> **Note**: If you are using [Google Kubernetes Engine](https://cloud.google.com/kubernetes-engine/) consider using [GKEStartPodOperator](https://registry.astronomer.io/providers/google/modules/gkest
I agree with your idea - fine to point out they exist, but we won't explicitly recommend them.

2022-06-28 21:29 UTC, TJaniF reviewed
Hey @jwitz, as threatened yesterday an update to the KPO guide 😅. 

@kentdanas I rewrote the section on the Kubernetes Connection and hope it is now clearer. Quite soon "namespace" will not be a required argument anymore, there is a PR open about that, so I was not sure if I should make a note or not about a feature that is not released. 
I also added a new note at the start of the last example for Astro customers about needing an extra line for new deployments and to provide CS for old deployments. The other thing on the list for hopefully changing soon. :)

2022-06-29 23:04 UTC, jwitz commented on guides/kubepod-operator.md
> +On AWS navigate to **Identity and Access Management (IAM)** -> **Roles** -> **Create role**. Select AWS service and `EKS` from the dropdown menu as well as `EKS - Cluster`. Make sure to give the role
```suggestion
To set up a new EKS cluster on AWS, first [create an EKS cluster IAM role](https://docs.aws.amazon.com/eks/latest/userguide/service_IAM_role.html#create-service-role) with a unique name and to the following permission policies: 

- `AmazonEKSWorkerNodePolicy`
- `AmazonEKS_CNI_Policy`
- `AmazonEC2ContainerRegistryReadOnly`
```

2022-06-29 23:05 UTC, jwitz commented on guides/kubepod-operator.md
> +Edit the trust policy (**IAM** -> **Roles** -> role name) of this new role to include your user and necessary AWS Services. This step ensures that the role can be assumed by your user.
```suggestion
[Update the trust policy](https://docs.aws.amazon.com/directoryservice/latest/admin-guide/edit_trust.html) of this new role to include your user and necessary AWS Services. This step ensures that the role can be assumed by your user.
```

2022-06-29 23:05 UTC, jwitz commented on guides/kubepod-operator.md
> +On AWS navigate to **Identity and Access Management (IAM)** -> **Roles** -> **Create role**. Select AWS service and `EKS` from the dropdown menu as well as `EKS - Cluster`. Make sure to give the role
I like to link out to documentation for 3rd party setup because you never know when the UI or buttons might change! This helps to future proof docs.

2022-06-29 23:08 UTC, jwitz commented on guides/kubepod-operator.md
> +Make sure your default credentials in `~/.aws/credentials` are using a valid and active key for your username (keys can be generated at **IAM** -> **Users** -> your user -> **Security Credentials**).
```suggestion
Make sure your default credentials include a valid and active key for your username (see the [AWS docs](https://docs.aws.amazon.com/kms/latest/developerguide/create-keys.html) for more information).
```

2022-06-29 23:09 UTC, jwitz commented on guides/kubepod-operator.md
> +Make a copy of `~/.aws` available to your Airflow environment (for Astro users: copy it into the `include` folder).
```suggestion
Make a copy of `~/.aws/credentials` available to your Airflow environment. If you run Airflow using the Astro CLI, copy this file into the `include` folder of your Astro project. 
```

2022-06-29 23:09 UTC, jwitz commented on guides/kubepod-operator.md
> +Make a copy of `~/.aws` available to your Airflow environment (for Astro users: copy it into the `include` folder).
Is this right?

2022-06-29 23:09 UTC, jwitz commented on guides/kubepod-operator.md
> +Lastly, create a new EKS cluster (**EKS** -> **Clusters** -> **Add cluster**) and assign the the newly created role to it. The cluster might take a few minutes to become active.
```suggestion
Lastly, [create a new EKS cluster](https://docs.aws.amazon.com/eks/latest/userguide/create-cluster.html) and assign the the newly created role to it. 
```

2022-06-29 23:10 UTC, jwitz commented on guides/kubepod-operator.md
> +To be able to remotely connect to the newly created EKS cluster the `KubeConfig` file is needed. It can be retrieved by running:
```suggestion
Use a `KubeConfig` file to remotely connect to your new EKS cluster. Retrieve it by running:
```

2022-06-29 23:11 UTC, jwitz commented on guides/kubepod-operator.md
> +aws eks --region region update-kubeconfig --name cluster_name
```suggestion
aws eks --region <your-region> update-kubeconfig --name <cluster-name>
```

2022-06-29 23:14 UTC, jwitz commented on guides/kubepod-operator.md
> +The command above will copy information relating to the new cluster into your existing `KubeConfig` file at `~/.kube/config`. Select the information pertaining to your EKS cluster and make it availab
```suggestion
This command copies information relating to the new cluster into your existing `KubeConfig` file at `~/.kube/config`. 

Check this file before making it available to Airflow. It should look like the following configuration. If any of the configurations listed here are missing, add them to the file. 
```

2022-06-29 23:16 UTC, jwitz commented on guides/kubepod-operator.md
> +The `KubeConfig` file is how the KPO will connect to a Kubernetes cluster by running the `awscli` with the default profile, using the credentials you provided in Step 1.
```suggestion
Once you confirm that the `KubeConfig` file is formatted properly, make it available to Airflow. If you're an Astro CLI user, you can do this by adding the file to the `include` directory of your Astro project.
```

2022-06-29 23:17 UTC, jwitz commented on guides/kubepod-operator.md
> +It is best practice to use a new namespace for all Pods sent to the EKS cluster from the Airflow environment.
```suggestion
It is best practice to use a new namespace for the Pods that Airflow spins up in your cluster. To create a namespace or your Pods, access the EKS cluster and run:  
```

2022-06-29 23:17 UTC, jwitz commented on guides/kubepod-operator.md
> +kubectl create namespace <your namespace name>
```suggestion
kubectl create namespace <your-namespace-name>
```

2022-06-29 23:20 UTC, jwitz commented on guides/kubepod-operator.md
> +If you are running Airflow with Docker, add the following line to your Dockerfile to copy your aws credentials from `/include` (or any other location) into the container:
```suggestion
#### Airflow on Docker with the Astro CLI

To access the cluster from Airflow using the Astro CLI, add the following line to your Dockerfile to copy your AWS credentials from into the container:
```
Again, does this have to be `.aws/config`?

2022-06-29 23:24 UTC, jwitz commented on guides/kubepod-operator.md
> +and `apache-airflow-providers-amazon` are installed correctly on the local machine.
```suggestion
This step will differ depending on the Airflow setup. 

#### Local Apache Airflow 

To access your cluster from local instance of Apache Airflow, install `awscli`, `apache-airflow-providers-cncf-kubernetes`, and `apache-airflow-providers-amazon` on the machine running Airflow.
```

2022-06-29 23:25 UTC, jwitz commented on guides/kubepod-operator.md
> +To be able to correctly authenticate yourself to the remote cluster it is also important to add the AWS command line tool (`awscli`) to your `packages.txt`, and the necessary provider packages to `re
```suggestion
To authenticate yourself to the remote cluster, add the following line to your `packages.txt` file:
```

2022-06-29 23:28 UTC, jwitz commented on guides/kubepod-operator.md
> +In the Airflow UI navigate to **Admin** -> **Connections** to set up the connection to the AWS account running the target EKS cluster. Chose a unique connection ID, the Connection Type 'Amazon Web Se
```suggestion
In the Airflow UI, go to **Admin** -> **Connections** to set up the connection to the AWS account running the target EKS cluster. Set the following configurations for the connection: 
- **Connection ID**: Any
- **Connection Type**: Amazon Web Services 
- **Login**: Your AWS access key ID
- **Password**: Your AWS secret access key
```

2022-06-29 23:31 UTC, jwitz commented on guides/kubepod-operator.md
> +If dynamic behavior of the EKS cluster is desired, e.g. Nodes get created with specifications for a task and deleted after the task has run, it is necessary to use several classes from the Amazon pro
```suggestion
The following DAG utilizes several classes from the Amazon provider package to dynamically spin up and delete Pods for each task in a newly created node group. If your remote Kubernetes cluster already has a node group available, you only need to define your task in the `KubernetesPodOperator` itself.
```

2022-06-30 11:17 UTC, TJaniF reviewed
Thank you Jake! I accepted most of your edits and added a few comments where I added new changes or changed your suggestion slightly. :)

2022-06-30 11:17 UTC, TJaniF commented on guides/kubepod-operator.md
> +Make sure your default credentials in `~/.aws/credentials` are using a valid and active key for your username (keys can be generated at **IAM** -> **Users** -> your user -> **Security Credentials**).
I changed the link here because yours links to the Key Management System docs which I think is a pretty advanced system (I never interacted with it so far). I used the easier way described here: https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html#access-keys-and-secret-access-keys.

2022-06-30 20:37 UTC, jwitz commented on guides/kubepod-operator.md
> +The KubernetesPodOperator launches any valid Docker image provided to it in a new Kubernetes Pod on a Kubernetes cluster. The KubernetesPodOperator supports arguments for some of the most common Pod
```suggestion
The KubernetesPodOperator launches any valid Docker image provided to it in a dedicated Kubernetes Pod on a Kubernetes cluster. The KubernetesPodOperator supports arguments for some of the most common Pod settings. For more advanced use cases, you can specify a [Pod template file](https://kubernetes.io/docs/concepts/workloads/pods/#pod-templates) that supports all possible Pod settings.
```

2022-06-30 20:37 UTC, jwitz commented on guides/kubepod-operator.md
> +- `pod_template_file`: Provides a way to specify the path to a YAML file defining Pod configurations.
```suggestion
- `pod_template_file`: The path to a Pod template file.
```

2022-06-30 20:37 UTC, jwitz commented on guides/kubepod-operator.md
> +- `labels`: Add key:value pairs to the Pod which can be used to logically group decoupled objects together.
```suggestion
- `labels`: A list of key/value pairs which can be used to logically group decoupled objects together.
```

2022-06-30 20:37 UTC, jwitz commented on guides/kubepod-operator.md
> +- `ports`: Provides the possibility to override default ports for the Pod.
```suggestion
- `ports`: Ports for the Pod.
```
When defining configurations, it's always best to strike at the exact thing the user has to define. If the user has to specify an object, the definition of the config should focus on that object.

2022-06-30 20:37 UTC, jwitz commented on guides/kubepod-operator.md
> +- `reattach_on_restart`: Defines how to handle losing the worker while the Pod is running, by default (`True`) the existing Pod will reattach to the worker on the next try. `False` creates a new Pod
```suggestion
- `reattach_on_restart`: Defines how to handle losing the worker while the Pod is running.  When set to `True`, the existing Pod reattaches to the worker on the next try. When set to `False`, a new Pod will be created for each try. The default is `True`.
```

2022-06-30 20:37 UTC, jwitz commented on guides/kubepod-operator.md
> +- `is_delete_operator_pod`: `True` by default, will delete the Pod when it reaches its final state or when the execution is interrupted.
```suggestion
- `is_delete_operator_pod`: Determines whether to delete the Pod when it reaches its final state or when the execution is interrupted. The default is `True`.
```

2022-06-30 20:37 UTC, jwitz commented on guides/kubepod-operator.md
> +- `get_logs`: Provides the `stdout` of the container as task-logs to the Airflow logging system.
```suggestion
- `get_logs`: Determines whether to use the `stdout` of the container as task-logs to the Airflow logging system.
```

2022-06-30 20:37 UTC, jwitz commented on guides/kubepod-operator.md
> +- `log_events_on_failure`: if set to `True` events will be logged in case the Pod fails (default: `False`).
```suggestion
- `log_events_on_failure`: Determines whether are logged in case the Pod fails. The default is `False`.
```

2022-06-30 20:37 UTC, jwitz commented on guides/kubepod-operator.md
> +- `env_vars`: Allows the user to specify individual environment variables for a Pod.
```suggestion
- `env_vars`: A list of environment variables for the Pod.
```

2022-06-30 20:37 UTC, jwitz commented on guides/kubepod-operator.md
> +- `resources`: Allows the user to pass a dictionary with resource requests (keys: `request_memory`, `request_cpu`) and limits (keys: `limit_memory`, `limit_cpu`, `limit_gpu`). See the [Kubernetes Doc
```suggestion
- `resources`: A dictionary with resource requests (keys: `request_memory`, `request_cpu`) and limits (keys: `limit_memory`, `limit_cpu`, `limit_gpu`). See the [Kubernetes Documentation on Resource Management for Pods and Containers](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/) for more information.
```

2022-06-30 20:37 UTC, jwitz commented on guides/kubepod-operator.md
> +- `volumes`: Can be used to pass in a modified `k8s.V1Volume`, see also the [Kubernetes example DAG from the Airflow documentation](https://airflow.apache.org/docs/apache-airflow-providers-cncf-kuber
```suggestion
- `volumes`: A list of `k8s.V1Volumes`, see also the [Kubernetes example DAG from the Airflow documentation](https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/_modules/tests/system/providers/cncf/kubernetes/example_kubernetes.html).
```

2022-06-30 20:37 UTC, jwitz commented on guides/kubepod-operator.md
> +- `affinity` and `tolerations` are ways to further specify rules for [Pod to Node assignment](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/). Like the `volumes` parameter t
```suggestion
- `affinity` and `tolerations`: Dictionaries of rules for [Pod to Node assignments](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/). Like the `volumes` parameter, these also require a `k8s` object.
```

2022-06-30 20:37 UTC, jwitz commented on guides/kubepod-operator.md
> +- `full_pod_spec`: Allows the user to specify Pod configurations using Python `k8s` objects.
```suggestion
- `full_pod_spec`: A complete Pod configuration formatted as a Python `k8s` object.
```

2022-06-30 20:37 UTC, jwitz commented on guides/kubepod-operator.md
> +The KPO launches any valid Docker Image provided to it (passed via the `image` parameter) in a new Kubernetes Pod on an existing Kubernetes cluster. The operator has many other parameters which speci
Ah yeah I forgot about Pod templates! Suggesting something along these lines for my next review

2022-06-30 20:39 UTC, jwitz commented on guides/kubepod-operator.md
> +A frequent use case for the KubernetesPodOperator is to run a Docker image containing a script for a task better described in a language other than Python in a Kubernetes Pod. To do this, you build a
```suggestion
A frequent use case for the KubernetesPodOperator is run a task in a language other than Python. To do this, you build a custom Docker image containing the script.
```

2022-06-30 20:40 UTC, jwitz commented on guides/kubepod-operator.md
> +A frequent use case for the `KubernetesPodOperator` is to run scripts for tasks better described in a language other than Python. For this purpose a custom Docker image has to be built and either run
I might have asked this question before I got full understanding myself later in my review. I actually think you were quite close the first time around - all you need to do is include the detail that the script is _in_ the Docker image.

2022-06-30 20:45 UTC, jwitz commented on guides/kubepod-operator.md
> +Make a copy of `~/.aws` available to your Airflow environment (for Astro users: copy it into the `include` folder).
If those are the only two files in the directory then it's probably fine to just add the directory.

2022-06-30 20:57 UTC, jwitz approved these changes
Looks great @TJaniF ! @kentdanas you might want to give this one more pass just in case I snuck in some unintended changes to meaning in any of my suggestions.

2022-06-30 20:57 UTC, jwitz commented on guides/kubepod-operator.md
> +Lastly, [create a new EKS cluster](https://docs.aws.amazon.com/eks/latest/userguide/create-cluster.html) and assign the the newly created role to it.
```suggestion
Lastly, [create a new EKS cluster](https://docs.aws.amazon.com/eks/latest/userguide/create-cluster.html) and assign the newly created role to it.
```

2022-06-30 20:57 UTC, jwitz commented on guides/kubepod-operator.md
> +To access your cluster from local instance of Apache Airflow, install `awscli`, `apache-airflow-providers-cncf-kubernetes`, and `apache-airflow-providers-amazon` on the machine running Airflow.
```suggestion
To access your cluster from a local instance of Apache Airflow, install `awscli`, `apache-airflow-providers-cncf-kubernetes`, and `apache-airflow-providers-amazon` on the machine running Airflow.
```

2022-06-30 20:57 UTC, jwitz commented on guides/kubepod-operator.md
> +- If a custom Docker image is passed to the Kubernetes executor's `base` container by providing it to either the `pod_template_file` or the `pod_override` key in the dictionary for the `executor_conf
```suggestion
- If a custom Docker image is passed to the Kubernetes executor's `base` container by providing it to either the `pod_template_file` or the `pod_override` key in the dictionary for the `executor_config` argument, it needs to have Airflow installed, otherwise the task will not run. A possible reason for customizing this Docker image would be to run a task in an environment with different versions of packages than other tasks running in your Airflow instance. This is not the case with the KubernetesPodOperator, which can run any valid Docker image.
```

2022-06-30 20:57 UTC, jwitz commented on guides/kubepod-operator.md
> +# instatiate the DAG
```suggestion
# instantiate the DAG
```

2022-06-30 20:57 UTC, jwitz commented on guides/kubepod-operator.md
> +- The Kubernetes executor runs a task defined in Airflow using any existing operator in a Kubernetes Pod without the user needing to specify a Docker image, while the KubernetesPodOperator requires a
```suggestion
- The KubernetesPodOperator requires a Docker image to be specified, while the Kubernetes executor doesn't.
```
Keeping parallel structure with the title. Also cut out some of the details that, while true, don't seem relevant to the main difference.

2022-06-30 20:57 UTC, jwitz commented on guides/kubepod-operator.md
> +- The KubernetesPodOperator defines one isolated Airflow task. In contrast the Kubernetes executor is implemented at the configuration level of the Airflow instance, which means _all_ tasks will each
```suggestion
- The KubernetesPodOperator defines one isolated Airflow task. In contrast, the Kubernetes executor is implemented at the configuration level of the Airflow instance, which means _all_ tasks run in their own Kubernetes Pod. This might be desired in some use cases to that require auto-scaling, but it's not ideal for environments with a high volume of shorter running tasks.
```

2022-06-30 20:57 UTC, jwitz commented on guides/kubepod-operator.md
> +- In comparison to the KubernetesPodOperator the Kubernetes executor has less abstraction over Pod configuration. All task-level configurations have to be passed in as a dictionary via the `BaseOpera
```suggestion
- In comparison to the KubernetesPodOperator, the Kubernetes executor has less abstraction over Pod configuration. All task-level configurations have to be passed in to the executor as a dictionary using the `BaseOperator's` `executor_config` argument, which is available to all operators.
```

2022-06-30 20:57 UTC, jwitz commented on guides/kubepod-operator.md
> +Below you can find the full DAG code. Remember to only turn on `do_xcom_push` if you have created the `airflow/xcom/return.json` within the Docker container run by the KubernetesPodOperator, otherwis
```suggestion
Below you can find the full DAG code. Remember to turn on `do_xcom_push` only if you have created the `airflow/xcom/return.json` within the Docker container run by the KubernetesPodOperator. Otherwise, the task will fail.
```

2022-06-30 20:57 UTC, jwitz commented on guides/kubepod-operator.md
> +        do_xcom_push=True #push the contents from xcom.json to xcoms
Worth repeating the note above in the comment here?

2022-06-30 20:57 UTC, jwitz commented on guides/kubepod-operator.md
> +The [KubernetesPodOperator](https://registry.astronomer.io/providers/kubernetes/modules/kubernetesPodoperator) (KPO) runs a Docker image in a Kubernetes Pod as an Airflow task. By abstracting calls t
```suggestion
The KubernetesPodOperator (KPO) runs an Airflow task as a Docker image in a dedicated Kubernetes Pod. By abstracting calls to the Kubernetes API, the KubernetesPodOperator enables you to start and run Pods from Airflow using DAG code.
```

2022-07-01 07:28 UTC, TJaniF commented on guides/kubepod-operator.md
> +The [`KubernetesPodOperator`](https://registry.astronomer.io/providers/kubernetes/modules/kubernetesPodoperator) (KPO) is an operator from the Kubernetes provider package designed to provide a straig
Hmm this might be me but I would still read this the wrong way around as "write your task in airflow and it will be put into a docker image to be run in a Pod". 
Actually maybe the "an Airflow task" is not really needed here? I assume people looking into the KPO know what an Operator is so we could just go with:  

> The KubernetesPodOperator (KPO) runs a Docker image in a dedicated Kubernetes Pod. 

? That way there is no ambiguity. What do you think? 😊

2022-07-01 07:41 UTC, TJaniF commented on guides/kubepod-operator.md
> +Make a copy of `~/.aws` available to your Airflow environment (for Astro users: copy it into the `include` folder).
They are the only two files I have in that directory but since it is AWS I assume there are many more files you could have in there if you play with other services and settings. So I think specifying the files makes sense :)

2022-07-01 14:50 UTC, jwitz commented on guides/kubepod-operator.md
> +The [`KubernetesPodOperator`](https://registry.astronomer.io/providers/kubernetes/modules/kubernetesPodoperator) (KPO) is an operator from the Kubernetes provider package designed to provide a straig
Brilliant! Yeah this makes sense in the context of what operators do - the Bash operator doesn't "Run a task in a bash script", it runs a bash script as a task.

2022-07-01 16:20 UTC, kentdanas approved these changes
@TJaniF great work on this!! It looks great to me, go ahead and merge when you're ready

2022-07-01 18:00 UTC, merged