Adding SQLColumnCheckOperator and SQLTableCheckOperator to the SQL Check guide.
astronomer/airflow-guides pull request #396
Opened 2022-07-15 16:25 UTC by TJaniF

Added the two new operators and an example for each. Very few changes to the rest of the text. 
To be merged once the operators are released.

2022-07-15 18:08 UTC, kentdanas requested changes
Thanks for adding these examples @TJaniF! Left a couple of comments, some of them will probably need @denimalpaca's guidance on. We can chat about it more next week!

2022-07-15 18:08 UTC, kentdanas commented on guides/airflow-sql-data-quality-tutorial.md
> +- **SQLColumnCheckOperator**: An operator capable of running multiple pre-defined data quality checks on multiple columns within the same task.
Somewhere in this guide we should reference the new provider. Where we do that might depend on whether we rewrite this section to _only_ talk about the provider, or keep the other operators mentioned.

2022-07-15 18:08 UTC, kentdanas commented on guides/airflow-sql-data-quality-tutorial.md
> +In the example below two checks are defined `my_row_count_check` and `my_column_sum_comparison_check` (the names can be freely chosen). The first check runs a SQL statement asserting that the table c
```suggestion
In the example below, two checks are defined `my_row_count_check` and `my_column_sum_comparison_check` (the names can be freely chosen). The first check runs a SQL statement asserting that the table contains at least 1000 rows, while the second check compares the sum of two columns.
```

2022-07-15 18:08 UTC, kentdanas commented on guides/airflow-sql-data-quality-tutorial.md
> +Under the hood the operator performs a `CASE WHEN` statement on each of the checks assinging `1` to the checks that passed and `0` to the checks that did not. Afterwards the operator looks for the mi
```suggestion
Under the hood, the operator performs a `CASE WHEN` statement on each of the checks, assigning `1` to the checks that passed and `0` to the checks that failed. Afterwards, the operator looks for the minimum of these results and marks the task as failed if the minimum is `0`.
```

2022-07-15 18:08 UTC, kentdanas commented on guides/airflow-sql-data-quality-tutorial.md
> +The `SQLColumnCheckOperator` uses a dictionary to define checks via the parameter `column_mapping`. The strength of this operator is the ability to run a multitude of checks within one task but still
Since you mention the benefit of visibility in the logs, maybe it would be helpful to include a screenshot showing the log output of one of these tasks?

2022-07-15 18:08 UTC, kentdanas commented on guides/airflow-sql-data-quality-tutorial.md
> +- "MY_DATE_COL" is checked to contain only _unique_ dates between 2017-01-01 and 2022-01-01.
```suggestion
- Check that "MY_DATE_COL" contains only _unique_ dates between 2017-01-01 and 2022-01-01.
```

2022-07-15 18:08 UTC, kentdanas commented on guides/airflow-sql-data-quality-tutorial.md
> +- "MY_TEXT_COL" is checked to have at least 10 distinct values and no `NULL` values present.
```suggestion
- Check that "MY_TEXT_COL" has at least 10 distinct values and no `NULL` values present.
```

2022-07-15 18:08 UTC, kentdanas commented on guides/airflow-sql-data-quality-tutorial.md
> +- "MY_NUM_COL" is checked to contain a maximum value between 90 and 110 (100 with a tolerance of 10).
```suggestion
- Check that "MY_NUM_COL" contains a maximum value between 90 and 110 (100 with a tolerance of 10).
```

2022-07-18 14:01 UTC, denimalpaca commented on guides/airflow-sql-data-quality-tutorial.md
>  - **[SQLValueCheckOperator](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/sql/index.html#airflow.operators.sql.SQLValueCheckOperator)**: A simpler operator that is usef
They're being replaced -- I think we should maybe just make mention of them, but we don't have to guide people on how to use them.

2022-07-18 14:04 UTC, denimalpaca commented on guides/airflow-sql-data-quality-tutorial.md
> +The `SQLColumnCheckOperator` uses a dictionary to define checks via the parameter `column_mapping`. The strength of this operator is the ability to run a multitude of checks within one task but still
Especially on a failure to se which specific tests failed and with what values!

2022-07-18 17:42 UTC, TJaniF commented on guides/airflow-sql-data-quality-tutorial.md
>  - **[SQLValueCheckOperator](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/sql/index.html#airflow.operators.sql.SQLValueCheckOperator)**: A simpler operator that is usef
That makes sense. I changed to focus to be on the two new operators but left in the SQLCheckOperator because I think it serves the purpose of jumping in when a check needs a WHERE or other additional statements or is across several tables, kind of as a catch all for specific use cases. Does that work?

2022-07-18 17:51 UTC, TJaniF commented on guides/airflow-sql-data-quality-tutorial.md
>  ## Examples
I agree (see my above comment). Since you have to specify the conn_id (unless your database is at "default_conn_id") I decided to put it in the examples to avoid people forgetting about it. I explained the arguments in the Connection to a database section. Hope that works 🙂

2022-07-19 18:59 UTC, kentdanas reviewed
Looks really good @TJaniF! A few minor comments, but once those are addressed let's double check everything with Benji before asking for Jake's review.

2022-07-19 18:59 UTC, kentdanas commented on guides/airflow-sql-data-quality-tutorial.md
> +Under the hood the operators use the information provided in the Airflow connection to get a [DbApiHook](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/hooks/dbapi/index.html#modu
Do you think this info will be relevant to most users? This seems pretty in the weeds to me, and I think we could take it out unless there's a practical application of that info. But I'll leave it up to you!

2022-07-19 18:59 UTC, kentdanas commented on guides/airflow-sql-data-quality-tutorial.md
> +In the example below 6 checks on 3 different columns are performed by the `SQLColumnCheckOperator`:
```suggestion
In the example below, we perform 6 checks on 3 different columns using the `SQLColumnCheckOperator`:
```

2022-07-19 18:59 UTC, kentdanas commented on guides/airflow-sql-data-quality-tutorial.md
> +### Observability
Wondering if we should move this section under the `SQLColumnCheckOperator` example, and then in the `SQLTableCheckOperator` section add a note saying the operator will produce logs similar to what we show above.

Since this observability piece doesn't apply to the `SQLCheckOperator` (I'm assuming), it seems a little odd to have it directly following that example.

2022-07-20 12:13 UTC, TJaniF commented on guides/airflow-sql-data-quality-tutorial.md
> +Under the hood the operators use the information provided in the Airflow connection to get a [DbApiHook](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/hooks/dbapi/index.html#modu
I think you are right, there isn't really a reason to interact with the Hook for most users (I didn't so far for the data quality dag).

2022-07-20 12:23 UTC, TJaniF commented on guides/airflow-sql-data-quality-tutorial.md
> +### Observability
That is true yeah. The SQLCheckOperator simply always puts the full SQL code and then if the test failed or passed, so it does look quite different.

2022-07-22 14:45 UTC, denimalpaca requested changes

2022-07-22 14:45 UTC, denimalpaca commented on guides/airflow-sql-data-quality-tutorial.md
> +- **`SQLTableCheckOperator`**: An operator to run multiple checks involving aggregate functions for one or more columns.
Link: https://airflow.apache.org/docs/apache-airflow-providers-common-sql/stable/operators.html#check-sql-table-values

2022-07-22 14:45 UTC, denimalpaca commented on guides/airflow-sql-data-quality-tutorial.md
> +- **`SQLColumnCheckOperator`**: An operator capable of running multiple pre-defined data quality checks on multiple columns within the same task.
Link: https://airflow.apache.org/docs/apache-airflow-providers-common-sql/stable/operators.html#check-sql-table-columns

2022-07-22 14:45 UTC, denimalpaca commented on guides/airflow-sql-data-quality-tutorial.md
> +- **[`SQLCheckOperator`](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/sql/index.html#airflow.operators.sql.SQLCheckOperator)**: A flexible operator that takes any SQL
I would also add a note that it only returns a _single_ row as a result.

2022-07-22 14:45 UTC, denimalpaca commented on guides/airflow-sql-data-quality-tutorial.md
> +- [`SQLIntervalCheckOperator`](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/sql/index.html#airflow.operators.sql.SQLIntervalCheckOperator): A time-based operator. Used
The functionality of the interval operator is not being replaced, and I have it on my docket to try and get it to emit lineage data.

2022-07-22 14:45 UTC, denimalpaca commented on guides/airflow-sql-data-quality-tutorial.md
> +The `SQLCheckOperator` and legacy SQL Check Operators are built into core Airflow and do not require a separate package installation.
I would just name them all here because they aren't actually legacy operators, they're still being maintained (I think that's the definition?)

2022-07-22 14:45 UTC, denimalpaca commented on guides/airflow-sql-data-quality-tutorial.md
> +The `SQLColumnCheckOperator` uses a dictionary to define checks via the parameter `column_mapping`. The strength of this operator is the ability to run a multitude of checks within one task but still
> ...checks within one task but still have observability on...
I would change to:
" ...checks within one task and have observability for..."

2022-07-22 14:45 UTC, denimalpaca commented on guides/airflow-sql-data-quality-tutorial.md
> +- Check that "MY_NUM_COL" contains a maximum value between 90 and 110 (100 with a tolerance of 10).
I think this should be:
Check that "MY_NUM_COL" contains a maximum value of 100 with a 10% tolerance, i.e. accepting values between 90 and 110.

2022-07-22 14:45 UTC, denimalpaca commented on guides/airflow-sql-data-quality-tutorial.md
> +        table=<your table>,
```
conn_id="example_conn",
table="example_table",
```

2022-07-22 14:45 UTC, denimalpaca commented on guides/airflow-sql-data-quality-tutorial.md
> +                "max": {"less_than": datetime.date(2022, 1, 1)},
It's awesome that these work, I just had to check in a python REPL because I hadn't thought to check dates like this. Can they be used with a tolerance, though? If not, would be worth mentioning in a note.

2022-07-22 14:45 UTC, denimalpaca commented on guides/airflow-sql-data-quality-tutorial.md
> +                "max": {"equal_to": 100, "tolerance": 10}
`tolerance` needs to be given as a decimal, this would be a 1000% tolerance 😂

2022-07-22 14:45 UTC, denimalpaca commented on guides/airflow-sql-data-quality-tutorial.md
> +If the resulting boolean value is `True` the check passes, otherwise it fails. Each individual check and its result will get logged into the Airflow [task logs](https://www.astronomer.io/guides/loggi
The set of returned records always gets logged to Airflow, but *only* the failed tests get logged with the check and result.

2022-07-22 14:45 UTC, denimalpaca commented on guides/airflow-sql-data-quality-tutorial.md
> +If the resulting boolean value is `True` the check passes, otherwise it fails. Each individual check and its result will get logged into the Airflow [task logs](https://www.astronomer.io/guides/loggi
I see you get into this further down, but would be good to clarify here as well.

2022-07-22 14:45 UTC, denimalpaca commented on guides/airflow-sql-data-quality-tutorial.md
> +All checks that fail will be listed at the end of the task log with their full SQL query and specific check that failed. The screenshot shows how the `TASK_DURATION` column failed the check to have a
The wording here is a bit convoluted in the second sentence, I think 2 sentences would make it easier to read:

> The screenshot shows how the `TASK_DURATION` column failed the check to have a minimum of greater than or equal 0 by having a minimum of -1251 instead.

Something like:
The screenshot shows how the `TASK_DURATION` column failed the check. Instead of a minimum that is greater than or equal to 0, it had a minimum of -1251.

2022-07-22 14:45 UTC, denimalpaca commented on guides/airflow-sql-data-quality-tutorial.md
> +The `SQLTableCheckOperator` provides a way to check the validity of SQL statements containing aggregates over the whole table. There is no limit to the amount of columns these statements can involve
They --> "The statements"

2022-07-22 14:45 UTC, denimalpaca commented on guides/airflow-sql-data-quality-tutorial.md
> +The `SQLTableCheckOperator` is useful for:
Also for row count checks on the table, and potentially schema checks as well. The fix to that aggregate-only bug should be out soon, although not released for a bit. Might just be worth putting a note in that in `1.0.0`, non-fully-aggregated statements should be in their own operator.

2022-07-22 14:45 UTC, denimalpaca commented on guides/airflow-sql-data-quality-tutorial.md
> +            "check_statement": "SUM(MY_COL_1) < SUM(MY_COL_2)"
So this can be `my_col_1 < my_col_2` as long as it's in its own operator. For now.

2022-07-22 14:49 UTC, TJaniF commented on guides/airflow-sql-data-quality-tutorial.md
> +                "max": {"equal_to": 100, "tolerance": 10}
Can I pretend like I intended to do that? 😂 thanks!

2022-07-22 15:34 UTC, TJaniF commented on guides/airflow-sql-data-quality-tutorial.md
> +The `SQLCheckOperator` and legacy SQL Check Operators are built into core Airflow and do not require a separate package installation.
Hmm I actually don't know the definition 😅 , but yes will change it!

2022-07-22 17:14 UTC, TJaniF commented on guides/airflow-sql-data-quality-tutorial.md
> +                "max": {"less_than": datetime.date(2022, 1, 1)},
I use that on all date columns in the data quality dag 😄 

You are right, it doesn't work with tolerance:

```
[2022-07-22, 15:56:06 UTC] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/providers/common/sql/operators/sql.py", line 130, in execute
    self.column_mapping[column][checks[idx]]["success"] = self._get_match(
  File "/usr/local/lib/python3.9/site-packages/airflow/providers/common/sql/operators/sql.py", line 148, in _get_match
    match_boolean = record >= check_values["geq_to"] * (1 - tolerance)
TypeError: unsupported operand type(s) for *: 'datetime.datetime' and 'int'
```

2022-07-22 17:18 UTC, kentdanas commented on guides/airflow-sql-data-quality-tutorial.md
> +- **`SQLTableCheckOperator`**: An operator to run multiple checks involving aggregate functions for one or more columns.
We should link to the registry for these wherever possible though...

2022-07-22 17:24 UTC, denimalpaca commented on guides/airflow-sql-data-quality-tutorial.md
> +- **`SQLTableCheckOperator`**: An operator to run multiple checks involving aggregate functions for one or more columns.
https://registry.astronomer.io/providers/common-sql/modules/sqlcolumncheckoperator

2022-07-22 17:24 UTC, denimalpaca commented on guides/airflow-sql-data-quality-tutorial.md
> +- **`SQLTableCheckOperator`**: An operator to run multiple checks involving aggregate functions for one or more columns.
https://registry.astronomer.io/providers/common-sql/modules/sqltablecheckoperator

2022-07-22 17:24 UTC, denimalpaca commented on guides/airflow-sql-data-quality-tutorial.md
> +- **`SQLColumnCheckOperator`**: An operator capable of running multiple pre-defined data quality checks on multiple columns within the same task.
https://registry.astronomer.io/providers/common-sql/modules/sqlcolumncheckoperator

2022-07-22 17:25 UTC, denimalpaca commented on guides/airflow-sql-data-quality-tutorial.md
> +                "max": {"less_than": datetime.date(2022, 1, 1)},
Alternatively, can always turn it into a timestamp and then tolerance would be... interesting, though possible.

2022-07-22 17:31 UTC, TJaniF commented on guides/airflow-sql-data-quality-tutorial.md
> +The `SQLTableCheckOperator` is useful for:
Ah interesting! I've been running into non-fully-aggregated statements suddenly not working, didn't realize that was because I added an aggregated one to the same operator. I added a note on it :)

2022-07-22 17:36 UTC, TJaniF commented on guides/airflow-sql-data-quality-tutorial.md
> +            "check_statement": "SUM(MY_COL_1) < SUM(MY_COL_2)"
I added a third example in its own operator to show non-aggregated statements :)

2022-07-22 17:42 UTC, TJaniF commented on guides/airflow-sql-data-quality-tutorial.md
> +                "max": {"less_than": datetime.date(2022, 1, 1)},
🤔 Yeah you could probably make a function that figures out what tolerance is with regards to that for x amount of days/hours etc... I try to mess with datetime as little as possible though 😅

2022-07-22 18:12 UTC, kentdanas approved these changes
Approving for content :)

2022-07-25 10:24 UTC, jwitz requested changes
Great update here @TJaniF ! Requesting changes only because of my questions related to the earlier versions of specific check operators, but otherwise LGTM!

2022-07-25 10:24 UTC, jwitz commented on guides/airflow-sql-data-quality-tutorial.md
> +The SQL Check Operators work with any database that can be queried using SQL. You simply have to define your [connection](https://www.astronomer.io/guides/connections/) in the Airflow UI and then pas
```suggestion
The SQL Check operators work with any database that can be queried using SQL. You simply have to define your [connection](https://www.astronomer.io/guides/connections/) in the Airflow UI and then pass the connection id to the operator's `conn_id` parameter.
```

2022-07-25 10:24 UTC, jwitz commented on guides/airflow-sql-data-quality-tutorial.md
> +The target table can be specified as a string using the `table` parameter for the `SQLColumnCheckOperator` and `SQLTableCheckOperator`. When using the `SQLCheckOperator` , you can override the databa
```suggestion
The target table can be specified as a string using the `table` parameter for the `SQLColumnCheckOperator` and `SQLTableCheckOperator`. When using the `SQLCheckOperator`, you can override the database defined in your Airflow connection as needed by passing a different value to the `database` argument. The target table for the `SQLCheckOperator` has to be given within the SQL statement.
```

2022-07-25 10:24 UTC, jwitz commented on guides/airflow-sql-data-quality-tutorial.md
> +The `SQLColumnCheckOperator` uses a dictionary to define checks via the parameter `column_mapping`. The strength of this operator is the ability to run a multitude of checks within one task and still
```suggestion
The `SQLColumnCheckOperator` has a `column_mapping` parameter which stores a dictionary of checks. Using this dictionary, it can run many checks within one task and still provide observability in the Airflow logs over which checks passed and which failed.
```

2022-07-25 10:24 UTC, jwitz commented on guides/airflow-sql-data-quality-tutorial.md
> +- "max" `"MAX(column) AS column_max"`
```suggestion
- "max": `"MAX(column) AS column_max"`
```

2022-07-25 10:24 UTC, jwitz commented on guides/airflow-sql-data-quality-tutorial.md
> +- "distinct_check" `"COUNT(DISTINCT(column)) AS column_distinct_check"`
```suggestion
- "distinct_check": `"COUNT(DISTINCT(column)) AS column_distinct_check"`
```

2022-07-25 10:24 UTC, jwitz commented on guides/airflow-sql-data-quality-tutorial.md
> +The resulting values then can be compared to a value input by the DAG author by using any of the qualifiers:
```suggestion
The resulting values can be compared to an expected value using any of the following qualifiers:
```

2022-07-25 10:24 UTC, jwitz commented on guides/airflow-sql-data-quality-tutorial.md
> +> **Note**: If you are dealing with floats or integers you can add a tolerance to the comparisons in form of a fraction (0.1 = 10% tolerance) as shown in the example above.
```suggestion
> **Note**: If you are dealing with floats or integers you can add a tolerance to the comparisons in form of a fraction (0.1 = 10% tolerance) as shown in the previous example.
```

2022-07-25 10:24 UTC, jwitz commented on guides/airflow-sql-data-quality-tutorial.md
> +If the resulting boolean value is `True` the check passes, otherwise it fails. [Airflow logs](https://www.astronomer.io/guides/logging/) the set of returned records for every check that passes and th
```suggestion
If the resulting boolean value is `True` the check passes, otherwise it fails. [Airflow generates logs](https://www.astronomer.io/guides/logging/) that show the set of returned records for every check that passes and the full query and result for checks that failed.
```

2022-07-25 10:24 UTC, jwitz commented on guides/airflow-sql-data-quality-tutorial.md
> +The screenshot below shows the output of 3 successful checks that ran on the `DATE` column of a table in Snowflake using `SQLColumnCheckOperator`. The checks concerned the minimum value, the maximum
```suggestion
The screenshot below shows the output of 3 successful checks that ran on the `DATE` column of a table in Snowflake using `SQLColumnCheckOperator`. The checks concerned the minimum value, the maximum value, and the amount of null values in the column.

```

2022-07-25 10:24 UTC, jwitz commented on guides/airflow-sql-data-quality-tutorial.md
> +![SQLColumnCheckOperator logging of passing checks](https://assets2.astronomer.io/main/guides/sql-data-quality-tutorial/column_checks_passed.png)
Sorry because this will be a lot of monotonous work 🙈 but I think logs like this should be in code blocks rather than screenshots. It makes the text more accessible and lets people copy and paste values. Plus it makes the logs searchable, so that anyone running into failed check information and searching about it might come across this guide!

2022-07-25 16:28 UTC, TJaniF commented on guides/airflow-sql-data-quality-tutorial.md
> +The functionality of the older `SQLValueCheckOperator` and `SQLThresholdCheckOperator` are being replaced by the newer `SQLColumnCheckOperator` and `SQLTableCheckOperator`.
I think I may have created the wrong impression by using "replaced" but I am not sure.

The two new operators are much more powerful than the old ones but not 1:1 with regards to taking over the functionality. Like for example the old operators could run checks involving several tables, which the two new ones cannot do (yet). 

So it isn't a full replacement but we want to encourage people to use the new operators over the old ones because they offer much cleaner code for the most common use cases and hopefully will fully replace the old ones one day.

Maybe something like:

> **Note**: We recommend the use of `SQLColumnCheckOperator` and `SQLTableCheckOperator` over the `SQLValueCheckOperator` and `SQLThresholdCheckOperator` whenever possible to improve code readability.

? 🙂

2022-07-25 16:35 UTC, TJaniF commented on guides/airflow-sql-data-quality-tutorial.md
> +- [`SQLThresholdCheckOperator`](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/sql/index.html#airflow.operators.sql.SQLThresholdCheckOperator): An operator with flexible
Yeah I think I let you astray by using "replace functionality", sorry about that 😅 . 

There are reasons to not use the new operators, e.g. if you want to run a check on several tables or use WHERE selections, subqueries etc. But all of those can be done using the `SQLCheckOperator` too. 
SQLValue and SQLThreshold just offer a little bit of abstraction over SQLCheck, not really anything more, while SQLColumn and SQLTable offer to clean up the code a ton and running several checks in one operator.  Hence why we try to steer people towards those two. 

Does that make sense?

2022-07-25 16:50 UTC, kentdanas commented on guides/airflow-sql-data-quality-tutorial.md
> +![SQLColumnCheckOperator logging of passing checks](https://assets2.astronomer.io/main/guides/sql-data-quality-tutorial/column_checks_passed.png)
Oooh being able to search for the log content in the guide is a really good point! We may have log screenshots in other guides that we want to update during the migration...

2022-07-25 17:29 UTC, TJaniF commented on guides/airflow-sql-data-quality-tutorial.md
> +![SQLColumnCheckOperator logging of passing checks](https://assets2.astronomer.io/main/guides/sql-data-quality-tutorial/column_checks_passed.png)
Yeah that is a great idea! (also solves the problem of can we show our internal table name in a guide 😉)

2022-07-25 18:13 UTC, TJaniF commented
Thank you @jwitz! I accepted all suggestions with one exception around the new operators replacing the old ones. I think the sentence was confusingly worded on my part, sry! 😅

2022-07-26 11:18 UTC, jwitz approved these changes
A few final comments here @TJaniF , I'll let you take this to the finish line but tag me again if you have any questions!

2022-07-26 11:18 UTC, jwitz commented on guides/airflow-sql-data-quality-tutorial.md
> +> **Note**: We recommend the use of the `SQLColumnCheckOperator` and `SQLTableCheckOperator` over the `SQLValueCheckOperator` and `SQLThresholdCheckOperator` whenever possible to improve code readabi
We start with an introductory sentence about what these two operators are, and move this sentence until after the definitions below.

2022-07-26 11:18 UTC, jwitz commented on guides/airflow-sql-data-quality-tutorial.md
> +- [`SQLThresholdCheckOperator`](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/sql/index.html#airflow.operators.sql.SQLThresholdCheckOperator): An operator with flexible
Got it, sounds like they're not deprecated enough to remove from the guide entirely. Per my suggestion above, let's write a quick introductory sentence explaining that these operators are legacy options and then explain what to use in place of them.

2022-07-26 11:18 UTC, jwitz commented on guides/airflow-sql-data-quality-tutorial.md
> +- **[`SQLColumnCheckOperator`](https://registry.astronomer.io/providers/common-sql/modules/sqlcolumncheckoperator)**: Runs multiple pre-defined data quality checks on multiple columns within the same
```suggestion
- **[`SQLColumnCheckOperator`](https://registry.astronomer.io/providers/common-sql/modules/sqlcolumncheckoperator)**: Runs multiple predefined data quality checks on multiple columns within the same task.
```

2022-07-26 11:18 UTC, jwitz commented on guides/airflow-sql-data-quality-tutorial.md
> +> **Note**: If you are dealing with floats or integers you can add a tolerance to the comparisons in form of a fraction (0.1 = 10% tolerance) as shown in the previous example.
```suggestion
> **Note**: If you are dealing with floats or integers you can add a tolerance to the comparisons in the form of a fraction (0.1 = 10% tolerance) as shown in the previous example.
```

2022-07-26 11:18 UTC, jwitz commented on guides/airflow-sql-data-quality-tutorial.md
> +> **Note**: In the provider version 1.0.0 you should non-fully aggregated statements into their own operator, separate from the fully aggregated ones! How to do this is shown in the example below.
```suggestion
> **Note**: You should partially aggregated statements into their own operator, separate from the fully aggregated ones. See the next example for how to do this.
```
- Looks like 1.0.0 is the only available version right now
- Should ___ partially aggregated statements? We're missing a word right now.

2022-07-26 11:39 UTC, TJaniF commented on guides/airflow-sql-data-quality-tutorial.md
> +> **Note**: In the provider version 1.0.0 you should non-fully aggregated statements into their own operator, separate from the fully aggregated ones! How to do this is shown in the example below.
Oh, I seem to have dropped a "put" there 😅

2022-07-26 11:59 UTC, TJaniF commented
Thank you Jake! @denimalpaca I think/hope I addressed all your comments 🙂

2022-07-26 13:32 UTC, denimalpaca approved these changes

2022-07-26 16:32 UTC, merged