Update airflow-scaling-workers.md
astronomer/airflow-guides pull request #399
Opened 2022-07-20 08:52 UTC by magdagultekin

Just a few cosmetic changes :)

2022-07-20 15:35 UTC, kentdanas requested changes
Thanks @magdagultekin! Most of these changes are great, just a few comments on the capitalization. I know in some cases Airflow docs use different styling, but we want to be consistent with our internal style guide.

2022-07-20 15:35 UTC, kentdanas commented on guides/airflow-scaling-workers.md
> +- **`max_active_runs_per_dag`:** This determines the maximum number of active DAG Runs (per DAG) that the Airflow Scheduler can create at any given time. In Airflow, a [DAG Run](https://airflow.apach
```suggestion
- **`max_active_runs_per_dag`:** This determines the maximum number of active DAG runs (per DAG) that the Airflow Scheduler can create at any given time. In Airflow, a [DAG run](https://airflow.apache.org/docs/apache-airflow/stable/dag-run.html) represents an instantiation of a DAG in time, much like a task instance represents an instantiation of a task. This parameter is most relevant if Airflow has to catch up from missed DAG runs, also known as backfilling. Consider how you want to handle these scenarios when setting this parameter.  By default, it's set to 16. 
```

I know Airflow docs often capitalize "Run", but our style guide has it as lower case. (e.g. we want to be consistent with our docs like this one https://docs.astronomer.io/astro/deployment-metrics#dag-runs). Thanks for catching the inconsistency though! Let's just update them to all be lower case.

2022-07-20 15:35 UTC, kentdanas commented on guides/airflow-scaling-workers.md
> +- **`max_dagruns_to_create_per_loop`:** This is the max number of DAGs to create DAG Runs for per scheduler loop. You can use this option to free up resources for scheduling tasks by decreasing the v
```suggestion
- **`max_dagruns_to_create_per_loop`:** This is the max number of DAGs to create DAG runs for per scheduler loop. You can use this option to free up resources for scheduling tasks by decreasing the value. The default value is 10 seconds. 
```

2022-07-20 15:35 UTC, kentdanas commented on guides/airflow-scaling-workers.md
> +  If you are utilizing `catchup` or `backfill` for your DAG, consider defining this parameter to ensure that you don't accidentally trigger a high number of DAG Runs.
```suggestion
  If you are utilizing `catchup` or `backfill` for your DAG, consider defining this parameter to ensure that you don't accidentally trigger a high number of DAG runs.
```

2022-07-20 15:35 UTC, kentdanas commented on guides/airflow-scaling-workers.md
> +- **`max_active_tasks`:** This is the total number of tasks that can run at the same time for a given DAG Run. It essentially controls the parallelism within your DAG. If this setting is not defined,
```suggestion
- **`max_active_tasks`:** This is the total number of tasks that can run at the same time for a given DAG run. It essentially controls the parallelism within your DAG. If this setting is not defined, the value of the environment-level setting `max_active_tasks_per_dag` is assumed.
```

2022-07-20 15:35 UTC, kentdanas commented on guides/airflow-scaling-workers.md
> +- **`concurrency`:** This is the maximum number of task instances allowed to run concurrently across all active DAG Runs for a given DAG. This allows you to set 1 DAG to be able to run 32 tasks at on
```suggestion
- **`concurrency`:** This is the maximum number of task instances allowed to run concurrently across all active DAG runs for a given DAG. This allows you to set 1 DAG to be able to run 32 tasks at once, while another DAG might only be able to run 16 tasks at once. If this setting is not defined, the value of the environment-level setting `max_active_tasks_per_dag` is assumed.
```

2022-07-20 15:35 UTC, kentdanas commented on guides/airflow-scaling-workers.md
> +- **`pool`:** This setting defines the amount of pools available for a task. Pools are a way to limit the number of concurrent instances of an arbitrary group of tasks. This setting is useful if you
```suggestion
- **`pool`:** This setting defines the amount of pools available for a task. Pools are a way to limit the number of concurrent instances of an arbitrary group of tasks. This setting is useful if you have a lot of workers or DAG runs in parallel, but you want to avoid an API rate limit or otherwise don't want to overwhelm a data source or destination. For more information, read our [Airflow Pools Guide](https://www.astronomer.io/guides/airflow-pools).
```

2022-07-20 15:35 UTC, kentdanas commented on guides/airflow-scaling-workers.md
> +The [Celery Executor](https://airflow.apache.org/docs/apache-airflow/stable/executor/celery.html) utilizes standing workers to run tasks. Scaling with the Celery Executor involves choosing both the n
```suggestion
The [Celery executor](https://airflow.apache.org/docs/apache-airflow/stable/executor/celery.html) utilizes standing workers to run tasks. Scaling with the Celery executor involves choosing both the number and size of the workers available to Airflow. The more workers you have available in your environment, or the larger your workers are, the more capacity you have to run tasks concurrently.
```

Same comment here, in our style guide we use lowercase for "executor". https://docs.astronomer.io/astro/runtime-image-architecture#executors

2022-07-20 15:35 UTC, kentdanas commented on guides/airflow-scaling-workers.md
> +You can also tune your **`worker_concurrency`** (environment variable: `AIRFLOW__CELERY__WORKER_CONCURRENCY`), which determines how many tasks each Celery worker can run at any given time. By default
```suggestion
You can also tune your **`worker_concurrency`** (environment variable: `AIRFLOW__CELERY__WORKER_CONCURRENCY`), which determines how many tasks each Celery worker can run at any given time. By default, the Celery executor will run a maximum of 16 tasks concurrently. If you increase `worker_concurrency`, you might also need to provision additional CPU and/or memory for your workers.   
```

2022-07-20 15:35 UTC, kentdanas commented on guides/airflow-scaling-workers.md
> +The [Kubernetes Executor](https://airflow.apache.org/docs/apache-airflow/stable/executor/kubernetes.html) launches a pod in a Kubernetes cluster for each task. Since each task runs in its own pod, re
```suggestion
The [Kubernetes executor](https://airflow.apache.org/docs/apache-airflow/stable/executor/kubernetes.html) launches a pod in a Kubernetes cluster for each task. Since each task runs in its own pod, resources can be specified on an individual task level.
```

2022-07-20 15:35 UTC, kentdanas commented on guides/airflow-scaling-workers.md
> +When performance tuning with the Kubernetes Executor, it is important to consider the supporting infrastructure of your Kubernetes cluster. Many users will enable auto-scaling on their cluster to ens
```suggestion
When performance tuning with the Kubernetes executor, it is important to consider the supporting infrastructure of your Kubernetes cluster. Many users will enable auto-scaling on their cluster to ensure they get the benefit of Kubernetes' elasticity.
```

2022-07-20 15:35 UTC, kentdanas commented on guides/airflow-scaling-workers.md
> +    - Try changing: If using the Kubernetes Executor, check that there are available resources in the namespace and check if `worker_pods_creation_batch_size` can be increased. If using the Celery Ex
```suggestion
    - Try changing: If using the Kubernetes executor, check that there are available resources in the namespace and check if `worker_pods_creation_batch_size` can be increased. If using the Celery executor, check if `worker_concurrency` can be increased.
```

2022-07-21 08:50 UTC, magdagultekin commented
Oh I wasn't aware of our internal styling guide, my apologies @kentdanas!!

2022-07-21 15:13 UTC, kentdanas approved these changes

2022-07-21 15:13 UTC, merged