Data quality overview guide
astronomer/airflow-guides pull request #409
Opened 2022-08-02 07:42 UTC by TJaniF

Since showing the draft I added some sections and made a few structural changes:

- added a short paragraph on flow control vs static control in "Data Quality Needs and Types of Data Quality Checks"
- added a "Choosing a tool" subsection under "Tools"
- added a "Logs" subsection for both SQL Check operators and GE
- added a "OpenLineage and Data Quality" section with screenshots from Marquez
- moved the example code to the end of the guide and restructured as a "these are the checks, here is the implementation in tool 1 vs tool 2"
- changed one check so that it can be shown using an expectation
- removed the Soda example (I'll PR that as a standalone guide and then later link to it)

I think this works to make the guide more concept focussed, though I am open to cutting down the examples section further if you think they are too detailed for an overview guide. Am on the fence between keeping those in because I like to show the same checks in two tools side by side but it also could make structural sense to only have a snippet of one check each and have everything else in their separate guides.

2022-08-03 19:03 UTC, denimalpaca requested changes
Lots and lots of little edits, but overall this is chock-full of great content. Really excited to see it cleaned up and released!

Also I know my comments can be a bit blunt or curt, so please add a "please" and "thank you" in your head before and after each one!

2022-08-03 19:03 UTC, denimalpaca commented on guides/data-quality.md
> +  GreatExpectationsOperator)
for the love of the almighty put that closing parenthesis on its own line!!!!

2022-08-03 19:03 UTC, denimalpaca commented on guides/data-quality.md
> +        do_xcom_push = False
remove spaces around `=`

2022-08-03 19:03 UTC, denimalpaca commented on guides/data-quality.md
> +Data quality is important which is reflected in growth of tools designed to perform data quality checks. In-depth planning and collaborative exploration of what kind of data quality needs your organi
in the growth of

2022-08-03 19:03 UTC, denimalpaca commented on guides/data-quality.md
> +Data quality is important which is reflected in growth of tools designed to perform data quality checks. In-depth planning and collaborative exploration of what kind of data quality needs your organi
what kind of data quality needs your organization --> what kind of data quality your organization needs

2022-08-03 19:03 UTC, denimalpaca commented on guides/data-quality.md
> +Data quality is important which is reflected in growth of tools designed to perform data quality checks. In-depth planning and collaborative exploration of what kind of data quality needs your organi
Second sentence is wordy, I'd re-work it

2022-08-03 19:03 UTC, denimalpaca commented on guides/data-quality.md
> +SQL Check operators offer a way to define your checks directly from within the DAG with no other tools necessary. If you run many checks on different databases you may profit from trialing a more com
capitalize operators!!

2022-08-03 19:03 UTC, denimalpaca commented on guides/data-quality.md
> +SQL Check operators offer a way to define your checks directly from within the DAG with no other tools necessary. If you run many checks on different databases you may profit from trialing a more com
profit --> benefit

2022-08-03 19:03 UTC, denimalpaca commented on guides/data-quality.md
> +SQL Check operators offer a way to define your checks directly from within the DAG with no other tools necessary. If you run many checks on different databases you may profit from trialing a more com
trialing --> using

2022-08-03 21:43 UTC, kentdanas requested changes
@TJaniF this looks really good! A couple high level content comments throughout, but overall I like the layout! We should double check on overall flow with Viraj, and after that I'll do a more detailed review and edit.

2022-08-03 21:43 UTC, kentdanas commented on guides/data-quality.md
> +To get the most out of this guide you should be familiar with basic Airflow concepts such as [operators](https://www.astronomer.io/guides/what-is-an-operator) and [connections](https://www.astronomer
I put an assumed knowledge section in the intro to dags rewrite, so let's wait to get Jake's input on formatting and then edit this one to match (I'm assuming we'll want to bullet format, but don't want to make you edit if Jake has another opinion and we'd have to change it).

2022-08-03 21:43 UTC, kentdanas commented on guides/data-quality.md
> +### Data Storage and Data Formats
This is obviously relevant here, but I'm wondering if this section is almost too high level for this guide (e.g. we can assume that anybody reading this already knows this part)? Open to other opinions here, but if we need to cut down on length at all I'd say going right into Data Quality Needs and Types of Data Quality Checks after the general steps would be fine.

2022-08-03 21:43 UTC, kentdanas commented on guides/data-quality.md
> +- **Flow Control**: monitors incoming data on a record-by-record basis and will sometimes prevent single records that fail certain data quality checks from entering the database. A well known tool fo
I agree, let's not call out Monte Carlo. Instead, I would just say something along the lines of "we're not covering flow control in this guide"

2022-08-03 21:43 UTC, kentdanas commented on guides/data-quality.md
> +Which tool to choose comes down to individual business needs and preferences. We recommend to use SQL Check operators if you want to:
Our style guide disagrees on this one: https://www.notion.so/astronomerio/Astronomer-Style-Guide-5d2389d462734e149d2e66a5cf606228#47360bdaf54a4f2190cf2faa61ff2236

Only capitalize when referring to a specific instance of an operator. (I'm still trying to learn all this stuff, but we're going to need to make everything consistent during the migration).

2022-08-03 21:43 UTC, kentdanas commented on guides/data-quality.md
> +- be able to use any existing SQL statement that returns a single row of booleans as a data quality check.
Somebody asked about this (sort of) in the LIVE we did yesterday. So it's relevant to at least one person!

2022-08-03 21:43 UTC, kentdanas commented on guides/data-quality.md
> +#### SQL Check operators: Requirements
I don't think we need a separate section for this. Let's add a sentence before the list of operators that says that they're part of the common SQL provider and link to the registry.

2022-08-03 21:43 UTC, kentdanas commented on guides/data-quality.md
> +#### SQL Check operators: Logs
Same comment here about not needing a separate section. I don't think it would hurt to briefly mention that check results can be found in the task logs, but for this overview guide I don't think we need actual log excerpts since we link to the more detailed implementation guide that goes through all of that.

2022-08-03 21:43 UTC, kentdanas commented on guides/data-quality.md
> +#### GreatExpectations: Requirements
Let's roll this into the ### level section above

2022-08-03 21:43 UTC, kentdanas commented on guides/data-quality.md
> +#### GreatExpectations: Logs
Same as for SQL checks, I think it's worth mentioning the logging since you're using that as a distinguishing factor between the two tools, but I don't know that we need a whole section or a screenshot (would reserve that level of detail for the GE-specific guide)

2022-08-03 21:47 UTC, kentdanas commented on guides/data-quality.md
> +#### SQL Check operators: Logs
Ah, just saw your comment about adding this section recently. Did somebody ask for this specifically (sorry if I'm just forgetting!)? If I'm telling you to take out something that somebody else asked you to include let me know and we can chat about it :)

2022-08-04 09:11 UTC, TJaniF commented on guides/data-quality.md
> +- How to chose a data quality check tool.
oops, thanks. (I can hear my old English teacher sigh in the distance)

2022-08-04 09:31 UTC, TJaniF commented on guides/data-quality.md
> +To get the most out of this guide you should be familiar with basic Airflow concepts such as [operators](https://www.astronomer.io/guides/what-is-an-operator) and [connections](https://www.astronomer
SInce it isn't a big change and I cannot imagine Jake being _against_ bullet format I changed it already 😅

2022-08-04 09:38 UTC, TJaniF commented on guides/data-quality.md
> +### Data Storage and Data Formats
That makes sense yeah, especially since we explicitly list Relational DBs as assumed knowledge. I'm leaving it in for   now but open to deleting it.

2022-08-04 09:58 UTC, TJaniF commented on guides/data-quality.md
> +- **Flow Control**: monitors incoming data on a record-by-record basis and will sometimes prevent single records that fail certain data quality checks from entering the database. A well known tool fo
Good points! removed Monte Carlo

2022-08-04 10:27 UTC, TJaniF commented on guides/data-quality.md
> +- write checks without needing to set up software additionally to Airflow.
this definitely did not prompt me to go back to change "Dbt" to "dbt" 👀

2022-08-04 10:32 UTC, TJaniF commented on guides/data-quality.md
> +- be able to use any existing SQL statement that returns a single row of booleans as a data quality check.
It was somewhat relevant for me to know that for the weirder checks I created (for example the one calculating percentile ranks and comparing values of the last day against that), but not in the sense of already having the SQL ready. 

I deleted the "existing", does that work?

2022-08-04 10:37 UTC, TJaniF commented on guides/data-quality.md
> +The SQL Check Operators work with any backend solution that accepts SQL queries and differ in what kind of data quality checks they can perform and how they are defined:
does "supports Airflow" work too? 🙂

2022-08-04 10:43 UTC, TJaniF commented on guides/data-quality.md
> +#### SQL Check operators: Logs
No, this wasn't specifically ask for. I added the section here to get symmetry between the subsections of the GE and SQL Check sections. Deleted the section in favor of a small sentence. 🙂

2022-08-04 10:45 UTC, TJaniF commented on guides/data-quality.md
> +```
True, though I followed Kenten's suggestion to not put logs here since it is redundant with the more in depth guide on SQL Check operators where we do show both a success and failure log. 🙂

2022-08-04 10:53 UTC, TJaniF commented on guides/data-quality.md
> +- Afterwards two `SQLTableCheckOperator`s perform one check each that involves several columns or the whole table respectively.
Yeah, I'll also try to remember that this needs an update probably soon! 🙂

2022-08-04 11:00 UTC, TJaniF commented on guides/data-quality.md
> +  GreatExpectationsOperator)
😅 

![image](https://user-images.githubusercontent.com/90063506/182831346-c4486b3b-d379-4426-8f58-33382679172a.png)

2022-08-04 11:06 UTC, TJaniF commented on guides/data-quality.md
> +        do_xcom_push = False
note to self: lint code that goes into guides

2022-08-04 11:14 UTC, TJaniF commented on guides/data-quality.md
> +Data quality is important which is reflected in growth of tools designed to perform data quality checks. In-depth planning and collaborative exploration of what kind of data quality needs your organi
I turned it into two sentences:

"Commitment to data quality requires in-depth planning and collaboration between data professionals. What kind of data quality your organization needs will depend on your unique use case, which you can explore using the steps outlined in this guide."

2022-08-04 11:19 UTC, TJaniF commented
Thank you for your reviews @denimalpaca and @kentdanas! I've addressed (hopefully all) comments. @virajmparekh do you agree with the overall flow? (this guide has become more high-level and streamlined and the soda content will get to live in its own guide) 🙂

2022-08-04 13:42 UTC, denimalpaca commented on guides/data-quality.md
> +  GreatExpectationsOperator)
😂 

Just run `black` on everything! No need to learn style when a machine will do it for you lol

2022-08-04 13:53 UTC, denimalpaca commented on guides/data-quality.md
> +Which tool to choose comes down to individual business needs and preferences. We recommend to use SQL Check operators if you want to:
My only hangup is that it is referencing a set of operators (that I think it looks bad I understand isn't a compelling argument), and may make more sense to then put them in a code block and reference them as `SQL*CheckOperator`s or something like that.

2022-08-04 15:27 UTC, kentdanas commented on guides/data-quality.md
> +Which tool to choose comes down to individual business needs and preferences. We recommend to use SQL Check operators if you want to:
yeah this is kind of an in-between case. can always see what Jake thinks

2022-08-08 18:25 UTC, kentdanas approved these changes
@TJaniF lots of little comments, but I'm approving now and I think we can move on to copy editing after all of these are addressed.

2022-08-08 18:25 UTC, kentdanas commented on guides/data-quality.md
> +> **Note**: You can find more information on how to use GreatExpectations with Airflow in the ['Integrating Airflow and Great Expectations'](https://www.astronomer.io/guides/airflow-great-expectation
```suggestion
> **Note**: You can find more information on how to use Great Expectations with Airflow in the ['Integrating Airflow and Great Expectations'](https://www.astronomer.io/guides/airflow-great-expectations/) guide.
```

2022-08-08 18:25 UTC, kentdanas commented on guides/data-quality.md
> +GreatExpectations is an open source data validation framework that allows the user to define data quality checks called Expectations Suites as a json file. The checks can be run in a DAG using the [`
```suggestion
Great Expectations is an open source data validation framework that allows the user to define data quality checks called Expectation Suites as a json file. The checks can be run in a DAG using the [`GreatExpectationsOperator`](https://registry.astronomer.io/providers/great-expectations/modules/greatexpectationsoperator).
```

2022-08-08 18:25 UTC, kentdanas commented on guides/data-quality.md
> +To use GreatExpectations you will need to install the open source GreatExpectations software and set up a GreatExpectations project with at least one instance of each of the following components:
```suggestion
To use Great Expectations, you will need to install the open source Great Expectations package and set up a Great Expectations project with at least one instance of each of the following components:
```

2022-08-08 18:25 UTC, kentdanas commented on guides/data-quality.md
> +The GreatExpectations documentation offers a [step-by-step tutorial](https://docs.greatexpectations.io/docs/tutorials/getting_started/tutorial_overview) for this setup. Additionally the [GreatExpecta
```suggestion
The Great Expectations documentation offers a [step-by-step tutorial](https://docs.greatexpectations.io/docs/tutorials/getting_started/tutorial_overview) for this setup. Additionally, to use Great Expectations with Airflow, the [Great Expectations provider package](https://registry.astronomer.io/providers/great-expectations) has to be installed.
```

2022-08-08 18:25 UTC, kentdanas commented on guides/data-quality.md
> +When using GreatExpectations, Airflow task logs will only show whether the suite passed or failed. To get a detailed report on the checks that were run and their results you can refer to the html fil
```suggestion
When using Great Expectations, Airflow task logs will only show whether the suite passed or failed. To get a detailed report on the checks that were run and their results, you can refer to the html files in `great_expecations/uncommitted/data_docs/local_site/validations`.
```

2022-08-08 18:25 UTC, kentdanas commented on guides/data-quality.md
> +## OpenLineage and Data Quality
Should we title this "Data lineage and data quality" to be more high level?

2022-08-08 18:25 UTC, kentdanas commented on guides/data-quality.md
> +In complex data ecosystems lineage can be a powerful addition to data quality checks, especially for investigating what data from which origins caused a check to fail.
```suggestion
In complex data ecosystems, lineage can be a powerful addition to data quality checks, especially for investigating what data from which origins caused a check to fail.
```

2022-08-08 18:25 UTC, kentdanas commented on guides/data-quality.md
> +> **Note**: For more information on Data Lineage and details on how to set up OpenLineage with Airflow please see the ['Open Lineage and Airflow' guide](https://www.astronomer.io/guides/airflow-openl
```suggestion
> **Note**: For more information on data lineage and details on how to set up OpenLineage with Airflow please see the ['Open Lineage and Airflow' guide](https://www.astronomer.io/guides/airflow-openlineage/).
```

2022-08-08 18:25 UTC, kentdanas commented on guides/data-quality.md
> +Both SQL Check operators and the GreatExpectationsOperator have Data Lineage extractors that work with OpenLineage and Marquez.
```suggestion
Both SQL Check operators and the GreatExpectationsOperator have OpenLineage extractors. If you are working with open source tools, you can view the resulting lineage from the extractors using Marquez.
```

2022-08-08 18:25 UTC, kentdanas commented on guides/data-quality.md
> +This example shows the steps necessary to perform the same set of data quality checks with SQL Check operators and with GreatExpectations.
```suggestion
This example shows the steps necessary to perform the same set of data quality checks with SQL Check operators and with Great Expectations.
```

2022-08-08 18:25 UTC, kentdanas commented on guides/data-quality.md
> +## Example: Comparing SQL Check operators and GreatExpectations
```suggestion
## Example: Comparing SQL Check operators and Great Expectations
```

2022-08-08 18:25 UTC, kentdanas commented on guides/data-quality.md
> +- First the `SQLColumnCheckOperator` is used to perform checks on several columns in the target table.
```suggestion
- First, the `SQLColumnCheckOperator` is used to perform checks on several columns in the target table.
```

2022-08-08 18:25 UTC, kentdanas commented on guides/data-quality.md
> +- Afterwards two `SQLTableCheckOperator`s perform one check each that involves several columns or the whole table respectively.
```suggestion
- Next, two `SQLTableCheckOperator`s perform one check each that involves several columns or the whole table respectively.
```

2022-08-08 18:25 UTC, kentdanas commented on guides/data-quality.md
> +- Lastly the `SQLCheckOperator` is used to make sure a categorical variable is set to one of 4 options.
```suggestion
- Finally, the `SQLCheckOperator` is used to make sure a categorical variable is set to one of 4 options.
```

2022-08-08 18:25 UTC, kentdanas commented on guides/data-quality.md
> +While this example shows all the checks being written within the python file defining the DAG, of course it is possible to modularize commonly used checks and SQL statements in separate files (for As
```suggestion
While this example shows all the checks being written within the Python file defining the DAG, it is possible to modularize commonly used checks and SQL statements in separate files (for Astro CLI users, those files can be put into the `/include` directory).
```

2022-08-08 18:25 UTC, kentdanas commented on guides/data-quality.md
> +The following example runs the same data quality checks as the SQL Check operators example against the same database. After setting up the GreatExpectations instance with all four components, the che
```suggestion
The following example runs the same data quality checks as the SQL Check operators example against the same database. After setting up the Great Expectations instance with all four components, the checks can be defined in JSON format to form one Expectation Suite.
```

2022-08-08 18:25 UTC, kentdanas commented on guides/data-quality.md
> +> **Note**: Running the same checks is possible because for each of the checks in this example an `Expectation` already exists. This is not always the case and especially for more complicated checks
```suggestion
> **Note**: For each of the checks in this example, an `Expectation` already exists. This is not always the case, and for more complicated checks you may need to define a [custom expectation](https://docs.greatexpectations.io/docs/guides/expectations/creating_custom_expectations/overview).
```

2022-08-08 18:25 UTC, kentdanas commented on guides/data-quality.md
> +The corresponding DAG code shows how all checks are run within one task using the `GreatExpectationsOperator`. Only the root directory of the data context and the checkpoint name have to be provided.
```suggestion
The corresponding DAG code shows how all checks are run within one task using the `GreatExpectationsOperator`. Only the root directory of the data context and the checkpoint name have to be provided. It is important to note that to use XComs with the `GreatExpectationsOperator` it is necessary to enable XCOM pickling as described in the more in-depth [Great Expectations](https://www.astronomer.io/guides/airflow-great-expectations/) guide.
```

2022-08-08 18:25 UTC, kentdanas commented on guides/data-quality.md
> +Data quality is important which is reflected in the growth of tools designed to perform data quality checks. Commitment to data quality requires in-depth planning and collaboration between data profe
```suggestion
The growth of tools designed to perform data quality checks reflect the importance of ensuring data quality in production workflows. Commitment to data quality requires in-depth planning and collaboration between data professionals. What kind of data quality your organization needs will depend on your unique use case, which you can explore using the steps outlined in this guide.
```

2022-08-08 18:25 UTC, kentdanas commented on guides/data-quality.md
> +SQL Check operators offer a way to define your checks directly from within the DAG with no other tools necessary. If you run many checks on different databases you may benefit from using a more compl
```suggestion
SQL Check operators offer a way to define your checks directly from within the DAG, with no other tools necessary. If you run many checks on different databases, you may benefit from using a more complex testing solution like Great Expectations or Soda.
```

2022-08-08 18:25 UTC, kentdanas commented on guides/data-quality.md
> +No matter which tool is used it is possible orchestrate the checks from within an Airflow DAG which makes downstream actions depending on the outcome of the checks possible.
```suggestion
No matter which tool is used, it is possible orchestrate the checks from within an Airflow DAG, which makes downstream actions depending on the outcome of the checks possible.
```

2022-08-09 09:48 UTC, TJaniF reviewed
Thank you Kenten! I accepted all changes 🙂 . I think this one is ready for you, once you are back @jwitz 🙂 

I have one general style question: In the style guide it says "Use sentence case for all titles and topics in documentation." Am I right to interpret this that we for example would not capitalize "Quality" in the guide title here? and use "Assumed knowledge" instead of "Assumed Knowledge" etc?

2022-08-09 09:48 UTC, TJaniF commented on guides/data-quality.md
> +- [Soda](https://docs.soda.io/): An open source data validation framework that uses YAML to define checks which can be kicked off using the `BashOperator`. Soda also offers the ability to write any c
Yeah I agree this one should be published first. I made a note to update the link once the soda guide is up 🙂

2022-08-09 09:48 UTC, TJaniF commented on guides/data-quality.md
> +- You prefer to write checks in JSON (GreatExpectations) or YAML (Soda) format.
Two words is consistent with their website 🙂

2022-08-10 10:32 UTC, jwitz reviewed
Looking great @TJaniF ! I just have a few questions throughout the guide that I would like you to answer before the full approval, but the general writing and structure LGTM

2022-08-10 10:32 UTC, jwitz commented on guides/data-quality.md
> +It is common practice to define further downstream actions depending on the results of data quality checks (`post_check_action_1` and `post_check_action_2`), or in [`callbacks`](https://airflow.apach
Are these downstream actions only triggered when an error occurs? We should be specific about that. Also can we be more Airflow specific and say "tasks" here?

2022-08-10 10:32 UTC, jwitz commented on guides/data-quality.md
> +These actions often include alerting data professionals via [error notifications](https://www.astronomer.io/guides/error-notifications-in-airflow/), for example with an email or in a Slack channel.
```suggestion
These tasks can alert data professionals with [error notifications](https://www.astronomer.io/guides/error-notifications-in-airflow/), such as an email or a Slack message.
```

2022-08-10 10:32 UTC, jwitz commented on guides/data-quality.md
> +When implementing data quality checks, consider how a check success or failure should influence downstream dependencies. [Trigger Rules](https://www.astronomer.io/guides/managing-dependencies/#trigge
```suggestion
When implementing data quality checks, consider how a check success or failure should influence downstream dependencies. [Trigger Rules](https://www.astronomer.io/guides/managing-dependencies/#trigger-rules) are especially useful for managing operator dependencies.
```

2022-08-10 10:32 UTC, jwitz commented on guides/data-quality.md
> +Good reasons to start thinking about data quality checks are:
```suggestion
You might need to implement data quality checks if:
```

2022-08-10 10:32 UTC, jwitz commented on guides/data-quality.md
> +## Tools
```suggestion
## Data quality tools
```

2022-08-10 10:32 UTC, jwitz commented on guides/data-quality.md
> +- **[Great Expectations](https://greatexpectations.io/)**: An open source data validation framework where checks are defined in JSON format. Airflow offers a provider package including the `GreatExpe
```suggestion
- **[Great Expectations](https://greatexpectations.io/)**: An open source data validation framework where checks are defined in JSON. Airflow offers a provider package including the `GreatExpectationsOperator` for easy integration.
```

2022-08-10 10:32 UTC, jwitz commented on guides/data-quality.md
> +- **[SQL Check operators](https://www.astronomer.io/guides/airflow-sql-data-quality-tutorial)**: A group of operators allowing the user to define data quality checks in Python dictionaries and SQL di
```suggestion
- **[SQL Check operators](https://www.astronomer.io/guides/airflow-sql-data-quality-tutorial)**: A group of operators that you can use to define data quality checks in Python dictionaries and SQL from within your DAGs.
```

2022-08-10 10:32 UTC, jwitz commented on guides/data-quality.md
> +- **[dbt test](https://docs.getdbt.com/docs/building-a-dbt-project/tests)**: dbt supports a testing framework on models using the `dbt test` CLI command, which can be run in Airflow with the `BashOpe
```suggestion
- **[dbt test](https://docs.getdbt.com/docs/building-a-dbt-project/tests)**: A testing framework for models using the `dbt test` CLI command, which you can run in Airflow with the `BashOperator` or `PythonOperator`.
```

2022-08-10 10:32 UTC, jwitz commented on guides/data-quality.md
> +- Write checks without needing to set up software additionally to Airflow.
```suggestion
- Write checks without needing to set up software in addition to Airflow.
```

2022-08-10 10:32 UTC, jwitz commented on guides/data-quality.md
> +- Be able to use any SQL statement that returns a single row of booleans as a data quality check.
```suggestion
- Use any SQL statement that returns a single row of booleans as a data quality check.
```

2022-08-10 10:32 UTC, jwitz commented on guides/data-quality.md
> +- Be able to have full observability of which checks failed from within Airflow task logs, including the full SQL statements of failed checks.
```suggestion
- Have full observability of which checks failed from within Airflow task logs, including the full SQL statements of failed checks.
```

2022-08-10 10:32 UTC, jwitz commented on guides/data-quality.md
> +- Most or all of your checks can be implemented by the predefined checks of the solution of your choice.
```suggestion
- Most or all of your checks can be implemented by the predefined checks in the solution of your choice.
```

2022-08-10 10:32 UTC, jwitz commented on guides/data-quality.md
> +- [`SQLColumnCheckOperator`](https://registry.astronomer.io/providers/common-sql/modules/sqlcolumncheckoperator): Allows quick definition of many checks on whole columns of a table using a Python dic
```suggestion
- [`SQLColumnCheckOperator`](https://registry.astronomer.io/providers/common-sql/modules/sqlcolumncheckoperator): Can quickly define checks on columns of a table using a Python dictionary.
```

2022-08-10 10:32 UTC, jwitz commented on guides/data-quality.md
> +Great Expectations is an open source data validation framework that allows the user to define data quality checks called Expectation Suites as a JSON file. The checks can be run in a DAG using the [`
```suggestion
Great Expectations is an open source data validation framework that allows the user to define data quality checks as a JSON file. The checks, also known as Expectation Suites, can be run in a DAG using the [`GreatExpectationsOperator`](https://registry.astronomer.io/providers/great-expectations/modules/greatexpectationsoperator).
```

2022-08-10 10:32 UTC, jwitz commented on guides/data-quality.md
> +The Great Expectations documentation offers a [step-by-step tutorial](https://docs.greatexpectations.io/docs/tutorials/getting_started/tutorial_overview) for this setup. Additionally, to use Great Ex
```suggestion
The Great Expectations documentation offers a [step-by-step tutorial](https://docs.greatexpectations.io/docs/tutorials/getting_started/tutorial_overview) for this setup. Additionally, to use Great Expectations with Airflow, you have to install the [Great Expectations provider package](https://registry.astronomer.io/providers/great-expectations).
```

2022-08-10 10:32 UTC, jwitz commented on guides/data-quality.md
> +When using Great Expectations, Airflow task logs will only show whether the suite passed or failed. To get a detailed report on the checks that were run and their results, you can refer to the html f
```suggestion
When using Great Expectations, Airflow task logs show only whether the suite passed or failed. To get a detailed report on the checks that were run and their results, you can view to the HTML files in `great_expecations/uncommitted/data_docs/local_site/validations`.
```
It's unclear how you actually run a local site to see this validation information. Is there a GE doc we can point to for this information instead?

2022-08-10 10:32 UTC, jwitz commented on guides/data-quality.md
> +The output from the `SQLColumnCheckOperator` will contain each individual check and whether or not it succeeded:
```suggestion
The output from the `SQLColumnCheckOperator` contains each individual check and whether or not it succeeded:
```

2022-08-10 10:32 UTC, jwitz commented on guides/data-quality.md
> +For the `GreatExpectationsOperator`, OpenLineage receives whether or not the whole Expectation suite succeeded or failed:
```suggestion
For the `GreatExpectationsOperator`, OpenLineage receives whether or not the whole Expectation Suite succeeded or failed:
```

2022-08-10 10:32 UTC, jwitz commented on guides/data-quality.md
> +- "MY_COL_3" contains only the values `val1`, `val2`, `val3` and `val4`
```suggestion
- "MY_DATE_COL" has only unique values.
- "MY_DATE_COL" has only values between 2017-01-01 and 2022-01-01.
- "MY_TEXT_COL" has no null values.
- "MY_TEXT_COL" has at least 10 distinct values.
- "MY_NUM_COL" has a minimum value between 90 and 110.
- `example_table` has at least 1000 rows.
- The value in each row of "MY_COL_1" plus the value of the same row in "MY_COL_2" is equal to 100.
- "MY_COL_3" contains only the values `val1`, `val2`, `val3` and `val4`.
```

2022-08-10 10:32 UTC, jwitz commented on guides/data-quality.md
> +- Finally, the `SQLCheckOperator` is used to make sure a categorical variable is set to one of 4 options.
```suggestion
- First, the`SQLColumnCheckOperator` is used to perform checks on several columns in the target table.
- Next, two `SQLTableCheckOperators` perform one check each. One operator checks several columns, while the other checks the entire table.
- Finally, the `SQLCheckOperator` is used to make sure a categorical variable is set to one of 4 options.
```

2022-08-10 10:32 UTC, jwitz commented on guides/data-quality.md
> +The example DAG below consists of 3 tasks:
```suggestion
The example DAG below consists of 4 tasks:
```

2022-08-10 10:32 UTC, jwitz commented on guides/data-quality.md
> +    )
Does this DAG need its dependencies defined?

2022-08-10 10:32 UTC, jwitz commented on guides/data-quality.md
> +The following example runs the same data quality checks as the SQL Check operators example against the same database. After setting up the Great Expectations instance with all four components, the ch
```suggestion
The following example runs the same data quality checks as the SQL Check operators example against the same database. After setting up the Great Expectations instance with all four components, the checks can be defined in a JSON file to form an Expectation Suite.
```

2022-08-10 10:32 UTC, jwitz commented on guides/data-quality.md
> +The corresponding DAG code shows how all checks are run within one task using the `GreatExpectationsOperator`. Only the root directory of the data context and the checkpoint name have to be provided.
```suggestion
The corresponding DAG code shows how all checks are run within one task using the `GreatExpectationsOperator`. Only the root directory of the data context and the checkpoint name have to be provided. It is important to note that to use XComs with the `GreatExpectationsOperator` you must enable XCOM pickling as described in the [Great Expectations](https://www.astronomer.io/guides/airflow-great-expectations/) guide.
```

2022-08-10 10:32 UTC, jwitz commented on guides/data-quality.md
> +## Conclusion
```suggestion
### Conclusion
```
This conclusion seems more specific to the "Tools" section vs. the entire guide.

2022-08-10 10:32 UTC, jwitz commented on guides/data-quality.md
> +No matter which tool is used, data quality checks can be orchestrated from within an Airflow DAG, which makes downstream actions depending on the outcome of the checks possible.
```suggestion
No matter which tool is used, data quality checks can be orchestrated from within an Airflow DAG, which makes it possible to trigger downstream actions depending on the outcome of your checks.
```

2022-08-11 14:16 UTC, TJaniF reviewed
Thank you for the review and questions @jwitz ! I tried to answer them and tagged Kenten on one of the questions for input. 🙂

2022-08-11 17:48 UTC, kentdanas commented on guides/data-quality.md
> +Data quality checks can be run at different times within a data pipeline or Airflow environment. It often makes sense to test them in their own DAG and later incorporate them into your ETL pipelines
Yes, that makes sense to me. We don't want to limit it to ETL only, but I think ETL is a great example that most users can relate to.

2022-08-12 09:50 UTC, TJaniF commented on guides/data-quality.md
> +Data quality checks can be run at different times within a data pipeline or Airflow environment. It often makes sense to test them in their own DAG and later incorporate them into your ETL pipelines
Made the changes 🙂

2022-08-12 12:32 UTC, jwitz commented on guides/data-quality.md
> +SQL Check operators execute a SQL statement that results in a set of booleans. A result of `True` leads to the check passing and the task being labelled as successful. A result of `False`, or any err
```suggestion
SQL Check operators execute a SQL statement that results in a set of booleans. A result of `True` leads to the check passing and the task being labeled as successful. A result of `False`, or any error when the statement is executed, leads to a failure of the task. Before using any of the operators, you need to define the [connection](https://www.astronomer.io/guides/connections/) to your data storage from the Airflow UI or via an external secrets manager.
```
Today I learned another discrepancy between US English and rest-of-the-world English! Since we are using US spelling in our content, I'm making this suggestion even though it's technically correct.

2022-08-12 12:33 UTC, jwitz approved these changes
Lookin good!!

2022-08-12 14:38 UTC, TJaniF commented on guides/data-quality.md
> +SQL Check operators execute a SQL statement that results in a set of booleans. A result of `True` leads to the check passing and the task being labelled as successful. A result of `False`, or any err
Yeah I had no idea about that either. The versions are a mess already in my head because learning rest of the world English in school but mostly consuming US media, I end up googling "s or z" a lot 😅

2022-08-12 17:49 UTC, TJaniF reviewed
Last proofread edits

2022-08-12 17:49 UTC, TJaniF commented on guides/data-quality.md
> +6. Choose a data quality tool (see the "Tools" section of this guide for more information).
```suggestion
6. Choose a data quality tool (see the "Data quality tools" section of this guide for more information).
```

2022-08-12 17:49 UTC, TJaniF commented on guides/data-quality.md
> +It is also important to distinguish between the two types of data integrity control:
```suggestion
It is also important to distinguish between the two types of control in data quality:
```

2022-08-12 17:49 UTC, TJaniF commented on guides/data-quality.md
> +3. Determine the quality checks to run on each level of data.
```suggestion
3. Determine the quality checks to run different components of the dataset.
```

2022-08-12 17:49 UTC, TJaniF commented on guides/data-quality.md
> +Data quality checks can be run on different levels:
```suggestion
Data quality checks can be run on different components of the dataset:
```

2022-08-12 17:49 UTC, TJaniF commented on guides/data-quality.md
> +When using Great Expectations, Airflow task logs show only whether the suite passed or failed. To get a [detailed report](https://docs.greatexpectations.io/docs/terms/data_docs/) on the checks that w
```suggestion
When using Great Expectations, Airflow task logs show only whether the suite passed or failed. To get a [detailed report](https://docs.greatexpectations.io/docs/terms/data_docs/) on the checks that were run and their results, you can view the HTML files located in the `great_expecations/uncommitted/data_docs/local_site/validations` directory in any browser.
```

2022-08-12 17:49 UTC, TJaniF commented on guides/data-quality.md
> +> **Note**: Currently only SQL Check operators and Great Expectations offer data lineage extraction.
```suggestion
> **Note**: Currently only SQL Check operators and the `GreatExpectationsOperator` offer data lineage extraction.
```

2022-08-12 17:54 UTC, TJaniF commented on guides/data-quality.md
> +date: 2022-07-12T00:00:00.000Z
```suggestion
description: "Check the quality of your data using Airflow"
date: 2022-08-12T00:00:00.000Z
```

2022-08-12 18:02 UTC, TJaniF commented on guides/data-quality.md
> +date: 2022-08-12T00:00:00.000Z
```suggestion
date: 2022-08-10T00:00:00.000Z
```

2022-08-12 18:03 UTC, merged