Standalone Soda Core guide
astronomer/airflow-guides pull request #410
Opened 2022-08-02 17:52 UTC by TJaniF

Base PR for a potential standalone soda guide (to link to from the data quality overview guide) to make it easier to collaborate on.

2022-08-02 19:29 UTC, denimalpaca requested changes
Looks pretty good overall, left comments about changes. Great work!

2022-08-02 19:29 UTC, denimalpaca commented on guides/soda_guide.md
> +- runs the `soda scan` command on `MY_DATASOURCE` using the configuration files.
I think these should be updated to not have to install the package (or even enter the virtual environment). The bash script on a worker machine in Airflow should be lighter weight.

2022-08-02 19:29 UTC, denimalpaca commented on guides/soda_guide.md
> +After creation of the YAML files write a bash script that will be executed by the BashOperator in your Airflow environment. It is considered best practice to use Soda Core in a virtual environment.
Do we have a reference on where it says to use Soda Core in a virtual env? IIRC it was to install it in one, but given that we're just spinning up and down a worker node, it shouldn't matter because the env will be clean every time. And the lib should be installed in the Airflow instance's python path anyway.

2022-08-02 19:29 UTC, denimalpaca commented on guides/soda_guide.md
> +> **Note** It is important to make this script executable by running `chmod +x filepath/soda_script.sh` before providing it to your Airflow environment. For more information on using bash scripts wit
`filepath` --> `<filepath>`

2022-08-02 19:29 UTC, denimalpaca commented on guides/soda_guide.md
> +soda scan -d MY_DATASOURCE -c configuration.yml checks.yml
With the `-c` flag in the soda scan command, you can specify the full file path. I think it would be better practice to specify a `SODA_PATH` env var in the Dockerfile and use that var in the command here. The `checks.yml` file should also be able to take a full file path.

Additionally, the `pip install` should happen in the `requirements.txt` file, or otherwise outside the script.

2022-08-02 19:29 UTC, denimalpaca commented on guides/soda_guide.md
> +    )
Make sure to add the task below the operator so it actually gets added to the DAG graph!

2022-08-04 12:11 UTC, TJaniF commented on guides/soda_guide.md
> +- [Offers check configurations](https://docs.soda.io/soda-cl/optional-config.html) that can add a warn state for a check. For example having values > 10 in a column might warrant a warning, while a v
True. I changed it to:

```markdown
- Lets you define checks as YAML configuration with many predefined metrics available.
- If there is no metric available for your use case you can provide any SQL query within the YAML file and check against its returned value.
- Easy to set up a large amount a data quality checks.
```

2022-08-04 12:26 UTC, TJaniF commented on guides/soda_guide.md
> +      valid regex: (((20)?(1[7-9]|2[0-1]))[-](0?[0-9]|1[012])[-](0?[0-9]|[12][0-9]|3[01])|2022[-]01[-]01)
thank you! 😅  I will be changing that check because it would only work if the date column is defined as TEXT which I hope for most users it would not be. I'll show of regex support with a less wieldy example.

2022-08-04 12:32 UTC, TJaniF commented on guides/soda_guide.md
> +After creation of the YAML files write a bash script that will be executed by the BashOperator in your Airflow environment. It is considered best practice to use Soda Core in a virtual environment.
Yes, you are right, their documentation shows venv for local installation. I had issues at first running soda scan directly even though I had the lib installed at the OS level (the error I got was that the command `soda scan` was not available), but since it is working now I'll change it to not need a script at all. One less step 🙂

2022-08-04 13:05 UTC, TJaniF commented on guides/soda_guide.md
> +> **Note** It is important to make this script executable by running `chmod +x filepath/soda_script.sh` before providing it to your Airflow environment. For more information on using bash scripts wit
Deleted this Note but was able to use that comment later :)

2022-08-04 13:57 UTC, denimalpaca commented on guides/soda_guide.md
> +      valid regex: (((20)?(1[7-9]|2[0-1]))[-](0?[0-9]|1[012])[-](0?[0-9]|[12][0-9]|3[01])|2022[-]01[-]01)
An easier regex example might be looking for a certain website address or even just that a US postal code is formatted correctly.

(The regex is also still wrong in terms of date-checking because it does not conditionally check that a month is given an appropriate day, so it would assume the date `2021-02-30` is correct!)

2022-08-04 14:22 UTC, TJaniF commented on guides/soda_guide.md
> +      valid regex: (((20)?(1[7-9]|2[0-1]))[-](0?[0-9]|1[012])[-](0?[0-9]|[12][0-9]|3[01])|2022[-]01[-]01)
Yeah, also they do offer a whole list of shorthands including one for valid dates and postal codes: https://docs.soda.io/soda-cl/validity-metrics.html#list-of-valid-formats

The only reason this was a regex was because I ran a date bounds check on a date column in TEXT format because I   like to make my life harder apparently. 

certain website address is a good idea, I'll use that :)

2022-08-04 14:30 UTC, TJaniF commented on guides/soda_guide.md
> +- [Offers check configurations](https://docs.soda.io/soda-cl/optional-config.html) that can add a warn state for a check. For example having values > 10 in a column might warrant a warning, while a v
Good point, thanks! :)

2022-08-05 19:14 UTC, kentdanas commented on guides/soda_guide.md
> +> **Note**: For a general overview on how to approach data quality and of different tools available to run data quality checks using Airflow see the 'Data Quality and Airflow' guide.
```suggestion
> **Note**: For a general overview on how to approach data quality, and of different tools available to run data quality checks using Airflow, see the 'Data Quality and Airflow' guide.
```

2022-08-05 19:14 UTC, kentdanas commented on guides/soda_guide.md
> +
Let's add an "In this guide, we'll cover how to use Soda Core with Airflow" type sentence here at the end of the overview.

2022-08-05 19:25 UTC, kentdanas commented on guides/soda_guide.md
> +description: "Use Soda Core for data quality checks with Airflow"
```suggestion
description: "Using Soda Core to implement data quality checks in Airflow DAGs"
```

2022-08-05 19:28 UTC, kentdanas commented on guides/soda_guide.md
> +slug: "data-quality"
The slug should be the same as the name of the file - so "soda_guide" in this case. Maybe we should make the name soda-data-quality or airflow-soda or something like that, to be a bit more consistent with the other ones (not that they all follow a convention, but there are a few patterns we tend to use...)

2022-08-05 19:28 UTC, kentdanas commented on guides/soda_guide.md
> +- Airflow Operators
```suggestion
- Airflow operators
```

2022-08-05 19:29 UTC, kentdanas commented on guides/soda_guide.md
> +- What Airflow is and when to use it
I think we can leave this out of assumed knowledge sections for everything other than the "101" type guides. I tend to think if it would be in every single one then it isn't super meaningful

2022-08-05 19:30 UTC, kentdanas commented on guides/soda_guide.md
> +- Airflow Operators
Once we have the update published, let's actually change this to the Airflow BashOperator specifically since we don't talk about any others, and then link to that guide.

2022-08-05 19:30 UTC, kentdanas commented on guides/soda_guide.md
> +- [Introduction to Apache Airflow](Introduction to Apache Airflow)
```suggestion
```
Same comment as above, let's remove this one.

2022-08-05 19:31 UTC, kentdanas commented on guides/soda_guide.md
> +Soda Core uses the SodaCL to run data quality checks defined in a YAML file. In this section we will highlight different types of checks. For a full overview please refer to the [Soda CL documentatio
```suggestion
Soda Core uses the SodaCL to run data quality checks defined in a YAML file. In this section, we will highlight different types of checks you can implement with Soda Core. For a full overview please refer to the [Soda CL documentation](https://docs.soda.io/soda-cl/soda-cl-overview.html).
```

2022-08-05 19:32 UTC, kentdanas commented on guides/soda_guide.md
> +## Features of Soda Core
I think it would make sense somewhere in this section to add something about _why_ you would want to use Soda with Airflow

2022-08-05 19:32 UTC, kentdanas commented on guides/soda_guide.md
> +It is possible to add optional check configurations like naming a check or configure warning vs failing conditions:
```suggestion
It is possible to add optional check configurations like naming a check or configure warning versus failing conditions:
```

2022-08-05 19:34 UTC, kentdanas commented on guides/soda_guide.md
> +How a metric is defined can be further specified using a:
```suggestion
How a metric is defined can be specified using any one of the following methods:
```

2022-08-05 19:44 UTC, kentdanas commented on guides/soda_guide.md
> +Two more unique features are freshness checks, schema checks and reference checks:
```suggestion
Two more unique features of Soda Core are freshness checks, schema checks and reference checks:
```
Shouldn't this say "three" more unique features? Or are "schema checks and reference checks" meant to be a single feature?

2022-08-05 19:45 UTC, kentdanas commented on guides/soda_guide.md
> +Standard check metrics offer the ability to run checks on individual columns:
Can we be a bit more explicit about what "metrics" are in this context?

2022-08-05 19:46 UTC, kentdanas commented on guides/soda_guide.md
> +To use Soda Core, the Soda Core package for the database backend needs to be installed and configured. The [Soda documentation provides a list of supported databases](https://docs.soda.io/soda-core/c
```suggestion
To use Soda Core, the Soda Core package for the database backend needs to be installed and configured. The [Soda documentation provides a list of supported databases](https://docs.soda.io/soda-core/configuration.html) and how to configure them.
```

Is this a general requirement, or specific to using Soda Core with Airflow?

2022-08-05 19:49 UTC, kentdanas commented on guides/soda_guide.md
> +For the DAG code no additional providers or packages need to be installed since the `BashOperator` is part of the Airflow core.
Here we say no additional packages need to be installed, but in the section below one of the steps is to install the `soda-core-snowflake` package. Maybe we don't need a separate reqs section and we can just add a note somewhere that using Soda Core requires setting something up against your database?

2022-08-05 19:50 UTC, kentdanas commented on guides/soda_guide.md
> +- Create the DAG code running the `soca scan` command using the `BashOperator`.
```suggestion
- Run the checks from a DAG by running the `soca scan` command using the `BashOperator`.
```

2022-08-05 19:51 UTC, kentdanas commented on guides/soda_guide.md
> +## Example: Run Soda Core checks on a Snowflake database
```suggestion
## Example: Run Soda Core checks from Airflow
```

I think we should generally update the language in this section to be a bit more focused on Airflow.

2022-08-05 19:52 UTC, kentdanas commented on guides/soda_guide.md
> +The configuration file needed to connect to Snowflake can be created from the template in the Soda documentation as shown below.
```suggestion
First we need to create a configuration file to connect to Snowflake. The easiest way to create the file is to use the template in the Soda documentation as shown below.
```

2022-08-05 19:52 UTC, kentdanas commented on guides/soda_guide.md
> +You can define your data quality checks using the [many checks available for Soda CL](https://docs.soda.io/soda-cl/soda-cl-overview.html). If you cannot find a predefined metric or check that works f
```suggestion
You can define your data quality checks using the [many checks available for Soda CL](https://docs.soda.io/soda-cl/soda-cl-overview.html). If you cannot find a predefined metric or check that works for your use case, you can create a user-defined check using SQL as shown below.
```

2022-08-05 19:53 UTC, kentdanas commented on guides/soda_guide.md
> +> **Note**: You need to make both YAML files available to your Airflow environment. Users of the Astro CLI can simply put them into the `/include` folder.
I was looking for this comment a bit earlier, so let's clearly state in both sections where to put the YAML files.

2022-08-05 19:55 UTC, kentdanas commented on guides/soda_guide.md
> +The DAG code itself stays very simple with one task using the `BashOperator` to execute the `soda scan` command. Of course it is possible to incorporate data quality checks using Soda Core in differe
```suggestion
In a DAG, Soda Core checks are executed by using the `BashOperator` to run the `soda scan` command. The DAG below shows how to reference the configuration and checks YAML files in the command.
```

2022-08-05 19:56 UTC, kentdanas commented on guides/soda_guide.md
> +```
```suggestion
```

Of course it is possible to incorporate data quality checks using Soda Core in different locations within your DAG, and to use the results of those checks to control the flow of data within your pipeline.  
```

2022-08-05 19:58 UTC, kentdanas commented on guides/soda_guide.md
> +    )
I'm confused by this...unless you're using taskflow, instantiating an operator is enough to register it in the DAG. So you shouldn't need the `soda_test` line below, unless I'm missing something here...

2022-08-05 19:58 UTC, kentdanas commented on guides/soda_guide.md
> +The logs from the Soda Core checks can be found in the Airflow task logs. They will list all checks that ran with their result.
```suggestion
The logs from the Soda Core checks can be found in the Airflow task logs. The logs will list all checks that ran along with their result.
```

2022-08-05 19:59 UTC, kentdanas commented on guides/soda_guide.md
> +In case of failure of a check, the logs will show which check failed and what the `check_value` was that caused the failure.
```suggestion
In the case of a check failure, the logs will show which check failed and the `check_value` that caused the failure.
```

2022-08-08 16:04 UTC, TJaniF reviewed
Addressed the comments 🙂 . I also changed the first check in the example to not be a regex since the option to use regex is now shown in the features section and since regex only works on TEXT columns I don't think many users would need to run that on dates.

2022-08-08 16:04 UTC, TJaniF commented on guides/soda_guide.md
> +> **Note**: You need to make both YAML files available to your Airflow environment. Users of the Astro CLI can simply put them into the `/include` folder.
put it into requirements too 🙂

2022-08-08 16:04 UTC, TJaniF commented on guides/soda_guide.md
> +    )
no, not missing anything. Benji and I were confused there 😅

2022-08-08 16:59 UTC, kentdanas commented on guides/soda_guide.md
> +
Yeah I think in general the more we can be consistent with the new templates the better, but I'll leave this one up to you however you prefer it.

2022-08-08 17:15 UTC, kentdanas approved these changes
Looks great @TJaniF! A couple of minor comments, but otherwise we're good to move this forward to copy edit.

2022-08-08 17:15 UTC, kentdanas commented on guides/soda-data-quality.md
> +- [Operators 101](Operators 101)
Update to the link to the guide here

2022-08-08 17:15 UTC, kentdanas commented on guides/soda-data-quality.md
> +- List of valid values.
I think we don't need the periods at the end of these bullet points since they aren't full sentences

2022-08-08 17:15 UTC, kentdanas commented on guides/soda-data-quality.md
> +When using Soda Core with Airflow the Soda Core package needs to be installed in your Airflow environment. Additionally, both YAML files, `configuration.yml`, which contains the connection informatio
```suggestion
When using Soda Core with Airflow, the Soda Core package needs to be installed in your Airflow environment. Additionally, two YAML files need to be made available to the Airflow environment: `configuration.yml`, which contains the connection information for the database backend, and `checks.yml`, which contains the data quality checks.
```

2022-08-08 17:15 UTC, kentdanas commented on guides/soda-data-quality.md
> +
Let's add a sentence here that says something like "Paste the text above into a file called `configuration.yml` and place it in your `include/` directory"

2022-08-08 17:15 UTC, kentdanas commented on guides/soda-data-quality.md
> +> **Note**: You need to make both YAML files available to your Airflow environment. Users of the Astro CLI can simply put them into the `/include` folder.
Same comment here as above - instead of having a note about this, let's add an explicit sentence in both sections saying to put the text in a file called xyz and put it somewhere where it will be available to Airflow e.g. include/

2022-08-09 10:28 UTC, TJaniF reviewed
Thank you! :) @jwitz this guide was kinda unplanned and happened because I wrote too much Soda content for the general data quality guide 😅 . Has the lowest priority of the reviews. 🙂

2022-08-09 10:28 UTC, TJaniF commented on guides/soda-data-quality.md
> +- [Operators 101](Operators 101)
I could have sworn I did correct that... weird. Sorry! 😅

2022-08-10 13:23 UTC, jwitz approved these changes
LGTM! Just a few minor suggestions

2022-08-10 13:23 UTC, jwitz commented on guides/soda-data-quality.md
> +Astro CLI users can simply put `soda-core-<database>` in `requirements.txt` and provide the YAML files in `/include`.
```suggestion
If you use the Astro CLI, you can add `soda-core-<database>` to `requirements.txt` and your YAML files to `/include` in your Astro project.
```

2022-08-10 13:23 UTC, jwitz commented on guides/soda-data-quality.md
> +When using Soda Core with Airflow, the Soda Core package needs to be installed in your Airflow environment. Additionally, two YAML files need to be made available to the Airflow environment: `configu
```suggestion
When using Soda Core with Airflow, the Soda Core package needs to be installed in your Airflow environment. Additionally, two YAML files need to be made available to the Airflow environment: `configuration.yml`, which contains the connection information for the database backend, and `checks.yml`, which contains the data quality checks.

```

2022-08-10 13:23 UTC, jwitz commented on guides/soda-data-quality.md
> +This example shows one possible way to set up data quality checks on a Snowflake database using Soda Core from within Airflow.
```suggestion
This example shows one possible way to run data quality checks on a Snowflake database using Soda Core from within Airflow.
```

2022-08-10 13:23 UTC, jwitz commented on guides/soda-data-quality.md
> +Save the YAML instructions above in a filed called `configuration.yml` and make it available to your Airflow environment. Astro CLI users can place the file into the `/include` directory.
```suggestion
Save the YAML instructions above in a filed called `configuration.yml` and make it available to your Airflow environment. If you use the Astro CLI, you can do this by placing the file into the `/include` directory of your Astro project.
```

2022-08-10 13:23 UTC, jwitz commented on guides/soda-data-quality.md
> +You can define your data quality checks using the [many checks available for Soda CL](https://docs.soda.io/soda-cl/soda-cl-overview.html). If you cannot find a predefined metric or check that works f
```suggestion
You can define your data quality checks using the [many preset checks available for Soda CL](https://docs.soda.io/soda-cl/soda-cl-overview.html). If you cannot find a preset metric or check that works for your use case, you can create a custom check using SQL as shown below.
```
Still confused about metric vs. check here

2022-08-10 13:23 UTC, jwitz commented on guides/soda-data-quality.md
> +Save the YAML instructions above in a filed called `checks.yml` and make it available to your Airflow environment. Astro CLI users can place the file into the `/include` directory.
```suggestion
Save the YAML instructions above in a filed called `checks.yml` and make it available to your Airflow environment. If you use the Astro CLI, you can place this file in your `/include` directory.
```

2022-08-10 13:23 UTC, jwitz commented on guides/soda-data-quality.md
> +The `soda-core-snowflake` package needs to be installed in your Airflow environment. Astro CLI users can add the following line to the `requirements.txt` file:
```suggestion
The `soda-core-snowflake` package needs to be installed in your Airflow environment. If you use the Astro CLI, you can do this by adding the following line to the `requirements.txt` file:
```

2022-08-10 13:23 UTC, jwitz commented on guides/soda-data-quality.md
> +The logs from the Soda Core checks can be found in the Airflow task logs. The logs will list all checks that ran along with their result.
```suggestion
Because Soda Core runs through the BashOperator, you can run your checks in any part of your DAG and trigger tasks with your results like you would with other Airflow operators.

The logs from the Soda Core checks can be found in the Airflow task logs. The logs list all checks that ran and their results.
```

2022-08-10 13:23 UTC, jwitz commented on guides/soda-data-quality.md
> +Below an example of the logs in the case of 3 checks passing:
```suggestion
The following is an example of how your logs might look if all 3 checks pass:
```

2022-08-10 13:23 UTC, jwitz commented on guides/soda-data-quality.md
> +In the case of a check failure, the logs will show which check failed and the `check_value` that caused the failure.
```suggestion
In the case of a check failure, the logs show which check failed and the `check_value` that caused the failure:
```

2022-08-10 13:23 UTC, jwitz commented on guides/soda-data-quality.md
> +Of course it is possible to incorporate data quality checks using Soda Core in different locations within your DAG, and to use the results of those checks to control the flow of data within your pipe
```suggestion
```
If you want to keep this sentence, I think it's better to add it before the DAG code above. It feels a bit like a cliffhanger here.

2022-08-10 17:34 UTC, janet-can commented
Hi @TJaniF  - I'm the Tech Writer at Soda and I'm really excited to see your work putting together this material for Astronomer users. I don't know if it would be useful to you, but I would be very happy to collaborate on any of the details, or to address anything in our own documentation that warrants further clarification or expansion. Please do reach out if I can help! janet@soda.io

2022-08-11 14:49 UTC, TJaniF reviewed
Thank you for the comments @jwitz! And happy to hear your thoughts @janet-can 🙂 !

2022-08-11 14:49 UTC, TJaniF commented on guides/soda-data-quality.md
> +- Define checks as YAML configuration with many predefined metrics available.
No, you are correct, metric is the property of the dataset that the check is run on. Thanks for catching that 😅

2022-08-11 14:49 UTC, TJaniF commented on guides/soda-data-quality.md
> +- Relational Databases. See [Relational database on Wikipedia](https://en.wikipedia.org/wiki/Relational_database).
True! I wasn't sure what our policy is with linking to resources on general concepts from companies, that is why I went with wikipedia, but yours is better.

2022-08-11 14:49 UTC, TJaniF commented on guides/soda-data-quality.md
> +You can define your data quality checks using the [many checks available for Soda CL](https://docs.soda.io/soda-cl/soda-cl-overview.html). If you cannot find a predefined metric or check that works f
Yeah, that is on me, sorry! I misread something and and thought things like missing_count or duplicate_count were called metrics and other checks were called checks. But as I said above metrics are the property of the data that is being checked. I'll change it in the text. 🙂

2022-08-11 14:49 UTC, TJaniF commented on guides/soda-data-quality.md
> +Of course it is possible to incorporate data quality checks using Soda Core in different locations within your DAG, and to use the results of those checks to control the flow of data within your pipe
🧗

2022-08-11 21:51 UTC, janet-can commented
I had a read-through of the guide and it's terrific! I don't really have a whole lot to add, but I made a few notes for your consideration.

- Potentially add [How Soda Core works](https://docs.soda.io/soda-core/how-core-works.html) to the list of Assumed Knowledge items, in case it's easy to have a quick ref for what Soda is and does.
- In the first paragraph under Features of Soda Core, "Soda Core uses SodaCL to run data quality checks..."  It might be helpful to expand the acronym on first mention, "Soda Checks Language (SodaCL)".
- In the fifth paragraph under Features of Soda Core, "Data can be filtered according to validity criteria..." Hmmm, this isn't really a filter. The invalid check counts all rows with contents that do not match the valid values listed and returns that count in the check result, for example; and the missing check counts everything that doesn't match an IP address format and returns that count in the check result.  Maybe just as simple as replacing the word "filtered" with "checked". (This is a nit-picky detail, I know!)
- In the Step 2 example, a very minor detail: in a valid values list, only numeric values need to be wrapped in single-quotes; strings can just be a plain comma-separated list. 
```# checks that all entries in MY_COL_3 are part of a set or possible values
  - invalid_count(MY_COL_3) = 0:
      valid values: ['val1', 'val2', 'val3', 'val4']
```  

Marvellous work, if I may say so!  When you publish this, I'd love to announce it in our community Slack channel, if that's OK with you. More eyes on it will be a good thing :)

2022-08-12 10:42 UTC, TJaniF commented
Thank you for the notes and feedback @janet-can, highly appreciate your help! 🙂 

Those are all great suggestions. I didn't realize that you needed quotes only for numeric values (I see it now in your docs but somehow I must have missed that line previously 😅 ), to point it out I added another valid values check for numeric values right underneath the existing check in the Features section (line 76-83). 

And yes of course you can announce the published guide in your Slack! Always happy to reach more people! 🙂 

@kentdanas I think this guide is ready to be published after the data quality overview one, if you agree with the latest changes. 🙂 (I'd dismiss Benjis review since I addressed his comments and I don't think we need to wait for the end of his vacation)

2022-08-12 18:10 UTC, TJaniF commented on guides/soda-data-quality.md
> +- How to design a data quality approach. See Data Quality and Airflow.
```suggestion
- How to design a data quality approach. See [Data Quality and Airflow](https://www.astronomer.io/guides/data-quality).
```

2022-08-12 18:10 UTC, TJaniF commented on guides/soda-data-quality.md
> +> **Note**: For a general overview on how to approach data quality, and of different tools available to run data quality checks using Airflow, see the 'Data Quality and Airflow' guide.
```suggestion
> **Note**: For a general overview on how to approach data quality, and of different tools available to run data quality checks using Airflow, see the '[Data quality and Airflow](https://www.astronomer.io/guides/data-quality)' guide.
```

2022-08-12 18:12 UTC, TJaniF commented on guides/soda-data-quality.md
> +description: "Using Soda Core to implement data quality checks in Airflow DAGs"
```suggestion
description: "Using Soda Core to implement data quality checks in Airflow DAGs."
```

2022-08-12 18:12 UTC, TJaniF commented on guides/soda-data-quality.md
> +date: 2022-08-02T00:00:00.000Z
```suggestion
date: 2022-08-11T00:00:00.000Z
```

2022-08-12 18:13 UTC, TJaniF commented on guides/soda-data-quality.md
> +tags: ["Soda", "Data Quality"]
```suggestion
tags: ["Soda", "Data quality"]
```

2022-08-12 18:16 UTC, TJaniF commented on guides/soda-data-quality.md
> +  # all names listed in MY_TABLE_1's MY_NAMES column have to also exists
```suggestion
  # all names listed in MY_TABLE_1's MY_NAMES column have to also exist
```

2022-08-12 18:19 UTC, TJaniF commented on guides/soda-data-quality.md
> +
```suggestion
```

2022-08-12 18:20 UTC, TJaniF commented on guides/soda-data-quality.md
> +Save the YAML instructions above in a filed called `configuration.yml` and make it available to your Airflow environment. If you use the Astro CLI, you can do this by placing the file into the `/incl
```suggestion
Save the YAML instructions above in a file called `configuration.yml` and make it available to your Airflow environment. If you use the Astro CLI, you can do this by placing the file into the `/include` directory of your Astro project.
```

2022-08-12 18:21 UTC, TJaniF commented on guides/soda-data-quality.md
> +You can define your data quality checks using the [many preset checks available for Soda CL](https://docs.soda.io/soda-cl/soda-cl-overview.html). If you cannot find a preset check that works for your
```suggestion
You can define your data quality checks using the [many preset checks available for SodaCL](https://docs.soda.io/soda-cl/soda-cl-overview.html). If you cannot find a preset check that works for your use case, you can create a custom one using SQL as shown below.
```

2022-08-12 18:26 UTC, TJaniF commented on guides/soda-data-quality.md
> +The following is an example of how your logs might look if all 3 checks pass:
```suggestion
This is an example of what your logs might look like if all 3 checks pass:
```

2022-08-12 18:29 UTC, merged