Managing your Connections in Airflow - Guide update
astronomer/airflow-guides pull request #423
Opened 2022-08-15 17:31 UTC by TJaniF

Added a few new chapters:
- Airflow connection essentials: Was on the fence on whether this section is needed but it also felt like too much information for the intro paragraph. I'm linking out to the Hooks guide here for more advanced users, but am open to deleting that part if we don't want to go into depth
- Define connections in the UI: This now has only one example (Amazon S3) I deleted the other example connection configurations.
- Define connections via environment variables: This is a short overview highlighting the JSON format that was added in 2.3.0. Linking out to Airflow docs for in depth explanations, including custom connections.
- Example: Configuring the SnowflakeToSlackOperator: I was thinking a transfer operator is perfect to show different connections. 

I modified the existing chapter on programmatic access to connections to explain access to the session first in a small example in a full DAG and then explain the provided function for looping over information from a secrets manager in more depth. 🙂

2022-08-16 21:01 UTC, kentdanas requested changes
Great start @TJaniF! A couple of comments/questions throughout, let me know if you want to chat about any of them.

2022-08-16 21:01 UTC, kentdanas commented on guides/connections.md
> +## Define connections via environment variables
Somewhere in one of these examples I think we should highlight how to use the `extras` field for connection params that aren't in the form. And how those values are obfuscated (or not) depending on their name. There's an Airflow env var you can modify to treat certain words/phrases as secret, that I can't remember the name of off the top of my head...

2022-08-17 20:06 UTC, TJaniF reviewed
Made the adjustments. The biggest change is shortening the section on programmatic access to connections. 🙂

2022-08-17 20:06 UTC, TJaniF commented on guides/connections.md
> +Knowing that connection information is programmatically accessible it is possible to build functions which are able to modify connection information. A possible use case is to synchronize information
Yeah, that does make sense, it would be odd to have to do this whenever using a secrets backend. I asked about it on slack and the use case seems to be for migrating larger amounts of connection information. (I cc'ed you on the thread). I adjusted the example and made the section a lot shorter. 

The question is if we want this to be here at all? It is a bit of a niche use case but maybe useful for some people (I found one question on stackoverflow from 3 years ago on this 😅 )

2022-08-18 21:40 UTC, kentdanas approved these changes
Looks great @TJaniF! A couple of small edits and comments throughout, but I'm approving now and we can move on to copy edit once those are addressed.

2022-08-18 21:40 UTC, kentdanas commented on guides/connections.md
> +## Airflow connection essentials
```suggestion
## Airflow connection basics
```

Updating to be consistent with bullet in the overview

2022-08-18 21:40 UTC, kentdanas commented on guides/connections.md
> +Airflow connections can be defined in multiple ways, using:
```suggestion
Airflow connections can be created by using one of the following methods:
```

2022-08-18 21:40 UTC, kentdanas commented on guides/connections.md
> +A connection in Airflow is a set of configurations containing the information necessary to send requests to the API of an external tool. The information a connection needs to contain will vary based
```suggestion
A connection in Airflow is a set of configurations containing the information necessary to send requests to the API of an external tool. The information contained in a connection will vary based on the requirements of the external tool. In most cases, a connection will require login credentials or a private key in order to authenticate Airflow to the external tool.
```

2022-08-18 21:40 UTC, kentdanas commented on guides/connections.md
> +- **The Airflow UI**: The most straightforward way to add connections directly from the UI.
```suggestion
- The Airflow UI
```
I think these are self explanatory enough that we can leave off the descriptions.

2022-08-18 21:40 UTC, kentdanas commented on guides/connections.md
> +- **Environment variables**: Add connections that are completely hidden from the UI.
```suggestion
- Environment variables
```

2022-08-18 21:40 UTC, kentdanas commented on guides/connections.md
> +- **The [Airflow REST API](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#tag/Connection)**: Add a connection using an API call.
```suggestion
- The [Airflow REST API](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#tag/Connection)
```

2022-08-18 21:40 UTC, kentdanas commented on guides/connections.md
> +- **The Airflow UI**: The most straightforward way to add connections directly from the UI.
Are there relevant links to add to these others, like you do for the REST API?

2022-08-18 21:40 UTC, kentdanas commented on guides/connections.md
> +- **A secrets backend**: Integrate Airflow with a secrets backend solution that can store credentials and sensitive values to be used by Airflow.
```suggestion
- A secrets backend (a system for managing secrets external to Airflow)
```

2022-08-18 21:40 UTC, kentdanas commented on guides/connections.md
> +- The `airflow.cfg` file: Add connections by modifying a configuration file.
```suggestion
- The `airflow.cfg` file
```

2022-08-18 21:40 UTC, kentdanas commented on guides/connections.md
> +- The Airflow CLI: Add connections by running a CLI command.
```suggestion
- The Airflow CLI
```

2022-08-18 21:40 UTC, kentdanas commented on guides/connections.md
> +In this guide we will cover adding connections using the Airflow UI and environment variables. For more in-depth information on configuring connections in other ways see the REST API documentation, a
```suggestion
In this guide we will show how to add connections using the Airflow UI and environment variables methods. For more in-depth information on configuring connections using the other methods, see the REST API documentation, as well as ['Managing Connections'](https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html) and ['Secrets Backend'](https://airflow.apache.org/docs/apache-airflow/stable/security/secrets/secrets-backend/index.html) in the Airflow documentation.

Each connection is associated with a unique `conn_id`, which can be provided to operators and hooks requiring a connection.
```

2022-08-18 21:40 UTC, kentdanas commented on guides/connections.md
> +To discover which information to provide to which field you can search for the relevant provider in the [Astronomer Registry](https://registry.astronomer.io/) and click on the `Docs` button to find d
```suggestion
Under the hood, Airflow [hooks](https://www.astronomer.io/guides/what-is-a-hook/) use connections to authenticate to external systems in order to send API requests. Most hooks that require connections are part of provider packages.

There are a couple of ways you can find what information needs to be provided for a particular connection type:

- Search for the relevant provider in the [Astronomer Registry](https://registry.astronomer.io/), and click on the `Docs` button to find documentation for provider. Most commonly used providers will have documentation on each of their associated `Connection types`. For example, you can find information on how to set up different connections to Azure on the [Connection Types page of the Azure provider](https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/stable/connections/index.html).
- Check the documentation of the external tool you are connecting to and see if it offers guidance on how to authenticate.
- Refer to the source code of the hook that is being used by your operator.
```

2022-08-18 21:40 UTC, kentdanas commented on guides/connections.md
> +> **Note**: If you cannot find the relevant information in the Apache Airflow documentation on the external tool you are trying to connect to, see if the documentation of the external tool offers gui
```suggestion
```

2022-08-18 21:40 UTC, kentdanas commented on guides/connections.md
> +Under the hood, Airflow [hooks](https://www.astronomer.io/guides/what-is-a-hook/) use connections to authenticate to external systems in order to send API requests. Most hooks that require connection
```suggestion
```

2022-08-18 21:40 UTC, kentdanas commented on guides/connections.md
> +For example, the `S3Hook`, which is part of the [Amazon provider](https://registry.astronomer.io/providers/amazon), requires a connection of the type `Amazon S3`.
Can we add a sentence here after that describes whcih method above you would use to find the S3 conn info needed?

2022-08-18 21:40 UTC, kentdanas commented on guides/connections.md
> +Each connection is associated with a unique `conn_id`, which can be provided to operators and hooks requiring a connection.
```suggestion
```

Reorg'ed the paragraphs in this section a bit. If you don't agree with anything flow-wise let me know and we can look again :)

2022-08-18 21:40 UTC, kentdanas commented on guides/connections.md
> +The most common way of defining a connection is using the Airflow UI. Click on the **Admin** in the navigation bar and select **Connections**.
```suggestion
The most common way of defining a connection is using the Airflow UI. Click on the **Admin** tab in the navigation bar and select **Connections**.
```

2022-08-18 21:40 UTC, kentdanas commented on guides/connections.md
> +For most connections it is not necessary to specify all fields. The example below shows a connection made to an Amazon S3 bucket using the AWS access key ID as `login` and the AWS secret access key a
```suggestion
For most connections it is not necessary to specify all fields. The example below shows a connection made to an Amazon S3 bucket using the AWS access key ID as `login` and the AWS secret access key as `password` (See the [AWS documentation](https://docs.aws.amazon.com/powershell/latest/userguide/pstools-appendix-sign-up.html) for how to retrieve your AWS access key ID and AWS secret access key).
```

2022-08-18 21:40 UTC, kentdanas commented on guides/connections.md
> +It is possible to pass additional configuration parameters to a connection by providing them to the `Extra` field as a JSON. For example it would be possible to add the [ARN of a role](https://docs.a
```suggestion
Any required parameters that do not have specific fields in the connection form can be provided to the `Extra` field as a JSON dictionary. For example, you can add the [ARN of a role](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html) to assume when logging into AWS by entering `{"role_arn":"arn:aws:iam::123456789012:role/my_role_name"}` in the `Extra` field. To learn more about additional parameters for a specific connection type, refer to the documentation of the relevant provider package.
```

2022-08-18 21:40 UTC, kentdanas commented on guides/connections.md
> +In Airflow version 2.2+ some connection types offer the possibility to test the connection from the Airflow UI. A message either confirming a successful connection or providing an error message will
```suggestion
In Airflow version 2.2+, you can test some connection types from the Airflow UI with the `Test` button. After running a connection test, a message will appear on the top of the screen either confirming a successful connection or providing an error message.
```

2022-08-18 21:40 UTC, kentdanas commented on guides/connections.md
> +Connections often contain sensitive credentials. By default Airflow will hide the connection password, both in the UI and in the Airflow logs. Values from the Connection's `Extra` field will also be
```suggestion
Connections often contain sensitive credentials. By default, Airflow will hide the connection password, both in the UI and in the Airflow logs. Values from the connection's `Extra` field will also be hidden if their key contains any of the words listed in the environment variable `AIRFLOW__CORE__SENSITIVE_VAR_CONN_NAMES`, as long as `AIRFLOW__CORE__HIDE_SENSITIVE_VAR_CONN_FIELDS` is set to `True`. You can find more information on masking, including a list of the default values in this environment variable, in the Airflow documentation on [Masking sensitive data](https://airflow.apache.org/docs/apache-airflow/stable/security/secrets/mask-sensitive-values.html).
```

2022-08-18 21:40 UTC, kentdanas commented on guides/connections.md
> +Connections often contain sensitive credentials. By default Airflow will hide the connection password, both in the UI and in the Airflow logs. Values from the Connection's `Extra` field will also be
This section looks great! I'm wondering if we should make it a high level section, since it isn't specifically related to UI connections...Maybe after the env var section, before the example?

2022-08-18 21:40 UTC, kentdanas commented on guides/connections.md
> +> **Note**: If you are synchronizing your project using a public remote repository, make sure not to save sensitive information in the Dockerfile. In this case using either a secrets backend, Airflow
```suggestion
> **Note**: If you are synchronizing your project to a remote repository, don't save sensitive information in your Dockerfile. In this case, using either a secrets backend, Airflow connections defined in the UI, or `.env` locally are preferred so as to not expose secrets in plain text.
```

2022-08-18 21:40 UTC, kentdanas commented on guides/connections.md
> +URI (Uniform Resource Identifier) is a format designed to contain all necessary connection information in one string, starting with the connection type followed by login, password and host. In many c
```suggestion
URI (Uniform Resource Identifier) is a format designed to contain all necessary connection information in one string, starting with the connection type, followed by login, password and host. In many cases a specific port, schema, and additional parameters will be added.
```

I actually didn't know what URI stood for :) Is there a link to some general URI doc that would be helpful here?

2022-08-18 21:40 UTC, kentdanas commented on guides/connections.md
> +In Airflow 2.3+, connections can alternatively be provided as a JSON (in this example defined from `.env`).
```suggestion
In Airflow 2.3+, connections can alternatively be provided as a JSON dictionary (in this example defined in `.env`).
```

I think the noun version of JSON would be "a JSON dictionary", but worth confirming....just "a JSON" sounds odd to me, but maybe I just haven't seen it written that way before...

2022-08-18 21:40 UTC, kentdanas commented on guides/connections.md
> +Note that connections that are defined using environment variables will not show up in the list of connections in the Airflow UI and which parameters to specify can very for different connection type
```suggestion
Note that connections that are defined using environment variables will not show up in the list of connections in the Airflow UI.
```
I think we've already covered the second part of that sentence above.

2022-08-18 21:40 UTC, kentdanas commented on guides/connections.md
> +In this example, we will configure the `SnowflakeToSlackOperator`, which requires connections to Snowflake and Slack. We will define the connections using the Airflow UI.
```suggestion
In this example, we configure the `SnowflakeToSlackOperator`, which requires connections to Snowflake and Slack. We define the connections using the Airflow UI.
```

2022-08-18 21:40 UTC, kentdanas commented on guides/connections.md
> +In the Airflow UI, we can navigate to the list of connections and add a connection of the 'Connection Type' `Snowflake`. The following parameters are required:
```suggestion
In the Airflow UI, we navigate to the list of connections and add a connection of the 'Connection Type' `Snowflake`. The following parameters are required:
```

2022-08-18 21:40 UTC, kentdanas commented on guides/connections.md
> +The last step is writing the DAG using the `SnowflakeToSlackOperator` to run a SQL query on a Snowflake table and post the result as a message to a Slack channel. The `SnowflakeToSlackOperator` needs
```suggestion
The last step is writing the DAG using the `SnowflakeToSlackOperator` to run a SQL query on a Snowflake table and post the result as a message to a Slack channel. The `SnowflakeToSlackOperator` requires both the connection id for the Snowflake connection (`snowflake_conn_id`) and the connection id for the Slack connection (`slack_conn_id`).
```

2022-08-19 17:33 UTC, TJaniF commented on guides/connections.md
> +To discover which information to provide to which field you can search for the relevant provider in the [Astronomer Registry](https://registry.astronomer.io/) and click on the `Docs` button to find d
Ahhh I missed a list opportunity 😅

2022-08-19 17:46 UTC, TJaniF commented on guides/connections.md
> +URI (Uniform Resource Identifier) is a format designed to contain all necessary connection information in one string, starting with the connection type followed by login, password and host. In many c
The wikipedia page is actually pretty good. They link to some in depth resources that are very in depth. Other higher level explanations I found are all on corporate sites. So I would vote to use the wiki link? :)

2022-08-19 17:47 UTC, TJaniF commented on guides/connections.md
> +In Airflow 2.3+, connections can alternatively be provided as a JSON (in this example defined from `.env`).
I think you are right. I have been calling it "a JSON" in my head but I might be the only one 😅

2022-08-19 17:54 UTC, TJaniF commented on guides/connections.md
> +A connection in Airflow is a set of configurations containing the information necessary to send requests to the API of an external tool. The information contained in a connection will vary based on t
We have 3 sentences here ending in "external tool" but I am also hesitant to use a synonym like "other software" because it could be confusing. Happily taking suggestions of how to make this less repetitive. 🙂

2022-08-19 18:26 UTC, kentdanas commented on guides/connections.md
> +A connection in Airflow is a set of configurations containing the information necessary to send requests to the API of an external tool. The information contained in a connection will vary based on t
Hmm, yes good point. Maybe the middle sentence isn't actually necessary and we can remove it? I don't think it's adding much now that I read the whole thing.

2022-08-19 19:25 UTC, kentdanas commented
@jwitz think we're ready for your review here. Should be getting to the tail end of these legacy updates :)

2022-08-22 12:33 UTC, jwitz requested changes
Major improvement to the existing guide @TJaniF ! Only requesting changes because I think we can improve how we describe the process for checking required connection values

2022-08-22 12:33 UTC, jwitz commented on guides/connections.md
> +For most connections it is not necessary to specify all fields. The example below shows a connection made to an Amazon S3 bucket. Referencing the [Airflow AWS provider documentation](https://airflow.
```suggestion
You don't have to specify every field on most connections. However, the values marked as required in the Airflow UI can be misleading. For example, the following example is a connection for an Amazon S3 bucket. We need to reference the [Airflow AWS provider documentation](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/connections/aws.html) to learn that the connection requires the AWS access key ID as `login` and the AWS secret access key as `password`.
```
This doesn't seem quite right to me.. when you go to the docs it shows both of those values as "Optional" because you can leave them blank for an IAM role. Is there a better connection type that we can use for this example?

2022-08-22 12:33 UTC, jwitz commented on guides/connections.md
> +Any required parameters that do not have specific fields in the connection form can be provided to the `Extra` field as a JSON dictionary. For example, you can add the [ARN of a role](https://docs.aw
```suggestion
Any required parameters that do not have specific fields in the connection form can be provided to the **Extra** field as a JSON dictionary. For example, you can add the [ARN of a role](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html) to assume when logging into AWS by specifying `{"role_arn":"arn:aws:iam::123456789012:role/my_role_name"}` in the **Extra** field.
```
I always use **bold** styling for UI elements and `code` styling for user inputs.

2022-08-22 12:33 UTC, jwitz commented on guides/connections.md
> +In Airflow version 2.2+, you can test some connection types from the Airflow UI with the `Test` button. After running a connection test, a message will appear on the top of the screen either confirmi
```suggestion
Starting in Airflow 2.2, you can test some connection types from the Airflow UI with the **Test** button. After running a connection test, a message appears on the top of the screen showing either a success confirmation or an error message.
```

2022-08-22 12:33 UTC, jwitz commented on guides/connections.md
> +Connections can also be defined using environment variables. Astro CLI users can use the `.env` file for local development, or specify environment variables in the Dockerfile.
```suggestion
Connections can also be defined using environment variables. If you use the Astro CLI, you use the `.env` file for local development or specify environment variables in your project's Dockerfile.
```

2022-08-22 12:33 UTC, jwitz commented on guides/connections.md
> +The environment variable used for the connection needs to be in the form of `AIRFLOW_CONN_YOURCONNID` and can be provided either in URI or, starting with Airflow 2.3, in JSON format.
```suggestion
The environment variable used for the connection must be formatted as `AIRFLOW_CONN_YOURCONNID` and can be provided either as a Uniform Resource Identifier (URI) or, starting in Airflow 2.3, in JSON.
```

2022-08-22 12:33 UTC, jwitz commented on guides/connections.md
> +[URI (Uniform Resource Identifier)](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier) is a format designed to contain all necessary connection information in one string, starting with the co
```suggestion
[URI](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier) is a format designed to contain all necessary connection information in one string, starting with the connection type, followed by login, password and host. In many cases a specific port, schema, and additional parameters must be added.
```

2022-08-22 12:33 UTC, jwitz commented on guides/connections.md
> +# the general format of a URI connection
```suggestion
# the general format of a URI connection that is defined in your Dockerfile
```

2022-08-22 12:33 UTC, jwitz commented on guides/connections.md
> +In Airflow 2.3+, connections can alternatively be provided as a JSON dictionary (in this example defined in `.env`).
```suggestion
In Airflow 2.3+, connections can be provided to an environment variable as a JSON dictionary:
```

2022-08-22 12:33 UTC, jwitz commented on guides/connections.md
> +AIRFLOW_CONN_MYCONNID='{
```suggestion
```text
# example of a connection defined as a JSON file in your `.env` file
AIRFLOW_CONN_MYCONNID='{
```

2022-08-22 12:33 UTC, jwitz commented on guides/connections.md
> +Note that connections that are defined using environment variables will not show up in the list of connections in the Airflow UI.
```suggestion
Note that connections that are defined using environment variables do not appear in the Airflow UI's list of available connections.
```

2022-08-22 12:33 UTC, jwitz commented on guides/connections.md
> +Connections often contain sensitive credentials. By default, Airflow will hide the connection password, both in the UI and in the Airflow logs. Values from the connection's `Extra` field will also be
```suggestion
Connections often contain sensitive credentials. By default, Airflow hides the `password` field, both in the UI and in the Airflow logs. If `AIRFLOW__CORE__HIDE_SENSITIVE_VAR_CONN_FIELDS` is set to `True`, values from the connection's `Extra` field are also hidden if their keys contain any of the words listed in  `AIRFLOW__CORE__SENSITIVE_VAR_CONN_NAMES`. You can find more information on masking, including a list of the default values in this environment variable, in the Airflow documentation on [Masking sensitive data](https://airflow.apache.org/docs/apache-airflow/stable/security/secrets/mask-sensitive-values.html).
```

2022-08-22 12:33 UTC, jwitz commented on guides/connections.md
> +Before starting Airflow, we need to install both the [Snowflake](https://registry.astronomer.io/providers/snowflake) and the [Slack provider](https://registry.astronomer.io/providers/slack). Astro CL
```suggestion
Before starting Airflow, we need to install both the [Snowflake](https://registry.astronomer.io/providers/snowflake) and the [Slack provider](https://registry.astronomer.io/providers/slack). If you use the Astro CLI, you can can add install the packages by adding the following lines to your Astro project's `requirements.txt` file:
```

2022-08-22 12:33 UTC, jwitz commented on guides/connections.md
> +In the Airflow UI, we navigate to the list of connections and add a connection of the 'Connection Type' `Snowflake`. The following parameters are required:
```suggestion
Open the Airflow UI and create a new connection. Set the **Connection Type** to `Snowflake`. This connection type requires the following parameters:
```

2022-08-22 12:33 UTC, jwitz commented on guides/connections.md
> +- Connection Id: `snowflake_conn` (or another string that has not been used for a different connection already)
```suggestion
- Connection Id: `snowflake_conn` or any other string that is not already in use by an existing connection
```

2022-08-22 12:33 UTC, jwitz commented on guides/connections.md
> +- Account: Your Snowflake account in the format xy12345.region
```suggestion
- Account: Your Snowflake account in the format `xy12345.region`
```

2022-08-22 12:33 UTC, jwitz commented on guides/connections.md
> +Next we set up a connection to Slack. To post a message to a Slack channel, you will need to create a Slack app for your server and configure incoming webhooks. A step-by-step explanation of this pro
```suggestion
Next we set up a connection to Slack. To post a message to a Slack channel, you need to create a Slack app for your server and configure incoming webhooks. See the [Slack Documentation](https://api.slack.com/messaging/webhooks) for setup steps.
```

2022-08-22 12:33 UTC, jwitz commented on guides/connections.md
> +- Password: The second part of the Webhook URL. It will have the format `T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX`
```suggestion
- Password: The second part of your Webhook URL in the format `T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX`
```

2022-08-22 12:33 UTC, jwitz commented on guides/connections.md
> +- Host: `https://hooks.slack.com.services` (the first part of the Webhook URL)
```suggestion
- Host: `https://hooks.slack.com.services`, or the the first part of your Webhook URL
```

2022-08-23 14:17 UTC, TJaniF reviewed
Thank you for the review @jwitz ! I changed the UI example from AWS to PostgreSQL I hope it is clearer now what is actually required 🙂

2022-08-31 09:32 UTC, jwitz approved these changes
Looks great! Just a few minor suggestions but this is good to go

2022-08-31 09:32 UTC, jwitz commented on guides/connections.md
> +You don't have to specify every field on most connections. However, the values marked as required in the Airflow UI can be misleading. For example to set up a connection to a PostgreSQL database, we
```suggestion
You don't have to specify every field on most connections. However, the values marked as required in the Airflow UI can be misleading. For example to set up a connection to a PostgreSQL database, we need to reference the [PostgreSQL provider documentation](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/connections/postgres.html) to learn that the connection requires a `Host`, a user name as `login`, and a password in the `password` field.
```

2022-08-31 09:32 UTC, jwitz commented on guides/connections.md
> +Any parameters that do not have specific fields in the connection form can be provided to the **Extra** field as a JSON dictionary. For example, you can add the `sslmode` or a client `sslkey` in the
```suggestion
Any parameters that don't have specific fields in the connection form can be defined in the **Extra** field as a JSON dictionary. For example, you can add the `sslmode` or a client `sslkey` in the **Extra** field of your PostgreSQL connection.
```

2022-08-31 09:32 UTC, jwitz commented on guides/connections.md
> +```text
```suggestion
```json
```

2022-08-31 09:32 UTC, jwitz commented on guides/connections.md
> +## Masking sensitive information
```suggestion
## Masking sensitive information
```

2022-08-31 09:32 UTC, jwitz commented on guides/connections.md
> +## Define connections via environment variables
```suggestion
## Defining connections with environment variables
```

2022-08-31 09:32 UTC, jwitz commented on guides/connections.md
> +## Define connections in the UI
```suggestion
## Defining connections in the UI
```

2022-08-31 09:32 UTC, jwitz commented on guides/connections.md
> +![Connections seen from the DAG view](https://assets2.astronomer.io/main/guides/connections/DAGview_connections.png)
Sorry this is super nitpicky but can we crop this screenshot so that we don't have all of the empty space at the bottom? It will help readers focus on the menu element

2022-08-31 10:19 UTC, TJaniF commented on guides/connections.md
> +![Connections seen from the DAG view](https://assets2.astronomer.io/main/guides/connections/DAGview_connections.png)
Good idea, thanks! :)

2022-08-31 11:07 UTC, merged