2.4 Update to Dynamic Tasks
astronomer/airflow-guides pull request #426
Opened 2022-08-19 15:11 UTC by TJaniF

Added a section on mapping over multiple parameters with the three methods:
- cross product
- expand kwargs
- zip

One of the examples for expanding kwargs is not implemented yet, but TP said he is planning on doing it. 🙂

I showed what zip does in comments in the code example, am on the fence on adding a small zip(["a","b","c"], [1,2,3]) -> [("a",1),("b",2),("c",3)] into the text. Might be a bit much, depends whether we expect people to know the concept. 🤔

2022-08-19 21:59 UTC, kentdanas requested changes
Thanks for this @TJaniF! Love the new sections and layout, I think that's perfect. Couple of comments/questions throughout, let me know if you want to chat through them next week.

2022-08-19 21:59 UTC, kentdanas commented on guides/dynamic-tasks.md
> +## Cross-Product
```suggestion
### Cross-Product
```

2022-08-19 21:59 UTC, kentdanas commented on guides/dynamic-tasks.md
> +- **Cross-Product**: Map over 2 or more parameters and get a mapped task instance for each possible combination of inputs.
```suggestion
- **Cross-Product**: Mapping over 2 or more parameters results in a mapped task instance for each possible combination of inputs.
```

2022-08-19 21:59 UTC, kentdanas commented on guides/dynamic-tasks.md
> +- **Sets of keyword arguments**: Map over 2 or more sets of one or more keyword arguments. Get a mapped task instance for every set.
```suggestion
- **Sets of keyword arguments**: Mapping over 2 or more sets of one or more keyword arguments results in a mapped task instance for every set.
```

2022-08-19 21:59 UTC, kentdanas commented on guides/dynamic-tasks.md
> +- **Zip**: Use Python's built-in `zip()` function to create sets of arguments for one parameter that is to be mapped over. Get one mapped task for every set of arguments.
```suggestion
- **Zip**: Mapping over a set of arguments created with Python's built-in `zip()` results in one mapped task for every set of arguments.
```

2022-08-19 21:59 UTC, kentdanas commented on guides/dynamic-tasks.md
> +The default behavior of the `expand()` function is to create a mapped task instance for every possible combination of all provided inputs. For example, if you were to map over 3 keyword arguments and
```suggestion
The default behavior of the `expand()` function is to create a mapped task instance for every possible combination of all provided inputs. For example, if you map over 3 keyword arguments and provide 2 options to the first, 4 options to the second, and 5 options to the third, you would create 2x4x5=40 mapped task instances. One common use case for this method is tuning model hyperparameters.
```

2022-08-19 21:59 UTC, kentdanas commented on guides/dynamic-tasks.md
> +The task definition below maps over 3 options for `bash_command` and 3 options for `env` variables. This will result in 3x3=9 mapped task instances. Each bash command runs with each definition for th
```suggestion
The task definition below maps over 3 options for  the `bash_command` parameter and 3 options for the `env` parameter. This will result in 3x3=9 mapped task instances. Each bash command runs with each definition for the environment variable `WORD`.
```

2022-08-19 21:59 UTC, kentdanas commented on guides/dynamic-tasks.md
> +To expand over sets of inputs to two or more keyword arguments (kwargs) you can use the `expand_kwargs()` function. The two tasks below show how you can provided sets of parameters as a list containi
```suggestion
To map over sets of inputs to two or more keyword arguments (kwargs), you can use the `expand_kwargs()` function. The two tasks below show how you can provide sets of parameters as a list containing a dictionary or as an XComArg. Each operator has 3 sets of commands resulting in 3 mapped task instances.
```

2022-08-19 21:59 UTC, kentdanas commented on guides/dynamic-tasks.md
> +To expand over sets of inputs to two or more keyword arguments (kwargs) you can use the `expand_kwargs()` function. The two tasks below show how you can provided sets of parameters as a list containi
Can we add something to clarify when you would want to use this? Overall it seems like essentially the same thing as using zip, but I think not everything can be passed as a kwarg?

2022-08-19 21:59 UTC, kentdanas commented on guides/dynamic-tasks.md
> +To provide sets of configurations to the same parameter, for example as arguments to a Python function, you can leverage the built-in Python function [`zip()`](https://docs.python.org/3/library/funct
I do think it would be helpful here to add your general zip example from your comment in the text.

2022-08-19 21:59 UTC, kentdanas commented on guides/dynamic-tasks.md
> +
Would zip not work with the Bash example used in the previous two sections? Seems like ideally we would use the same example in all three to help people understand the difference.

2022-08-22 18:13 UTC, TJaniF commented on guides/dynamic-tasks.md
> +To expand over sets of inputs to two or more keyword arguments (kwargs) you can use the `expand_kwargs()` function. The two tasks below show how you can provided sets of parameters as a list containi
I was also not fully clear on when to use what either (and I didn't realize that there is a .zip method too) ... 

I played around with it some more and the difference is that zip bundles together positional arguments in a zippy way to be provided to only one kwarg of the operator. So for example to op_args of the PythonOperator, which then gets unpacked in the python function. 
Meanwhile expand_kwargs allows to iterate in a zippy way over different sets of keyword arguments. 

I tried to make this clearer in the intro to the section and in the zip-section.

2022-08-22 18:48 UTC, TJaniF reviewed
Made some changes to the multiple parameters section trying to clarify which of the 3 options does what (after clarifying it in my head 😅). 

While playing around with mapping I noticed that it isn't always super intuitive how to pass XComs from one task to be mapped over by another task especially if one of the tasks does not use the TaskFlowAPI. I decided to add a section on this, but if it makes the guide too long am of course open to deleting it. I gathered the examples in a DAG in our 2.4 dags repo, so there is the option of just linking to that DAG too. 🙂

2022-08-22 18:48 UTC, TJaniF commented on guides/dynamic-tasks.md
> +
Yes, I agree. I tried to make it work but none of the BashOperator parameters takes positional arguments. 🤔 It seems when zipping all the things that get zipped have to be provided to one kwarg of the operator because .expand() does not allow any other input... 
I think the main use for zipping is really for the PythonOperator and -decorator. Unless I am grossly misunderstanding something. 👀

2022-08-25 23:22 UTC, kentdanas reviewed
@TJaniF this looks great! Agree with adding the additional section, I think it's helpful. I made some comments throughout on potentially simplifying the examples, but after that let's move on to copy editing.

2022-08-25 23:22 UTC, kentdanas commented on guides/dynamic-tasks.md
> +To map over sets of inputs to two or more keyword arguments (kwargs), you can use the `expand_kwargs()` function. The two tasks below show how you can provide sets of parameters as a list containing
```suggestion
To map over sets of inputs to two or more keyword arguments (kwargs), you can use the `expand_kwargs()` function. The two tasks below show how you can provide sets of parameters as a list containing a dictionary or as an `XComArg`. Each operator has 3 sets of commands, resulting in 3 mapped task instances.
```

2022-08-25 23:22 UTC, kentdanas commented on guides/dynamic-tasks.md
> +# input sets of kwargs directly as a list[dict] PENDING IMPLEMENTATION!
Just a reminder to remove the PENDING IMPLEMENTATION note when ready - I would totally forget to do this :)

2022-08-25 23:22 UTC, kentdanas commented on guides/dynamic-tasks.md
> +# input sets of kwargs generated by another task as an XComArg object
Now that you've added a section on mapping on the results of another task, do you think we still need this t2 here? If not I think the example would be more straight forward with a single task...

2022-08-25 23:22 UTC, kentdanas commented on guides/dynamic-tasks.md
> +The code snippet below shows how a list of zipped arguments can be provided to the `expand()` function in order to create mapped tasks over sets of positional arguments. Each set of positional argume
Let's update this example to be only TaskFlow, and decorate the `add_numbers` function. Astronomer is recommending taskflow over regular PythonOperator now, and zip is basically the same for both so I think we can simplify.

2022-08-25 23:22 UTC, kentdanas commented on guides/dynamic-tasks.md
> +> **Note**: To get as many tuples as there are elements in the *longest* list provided you can use the [`zip_longest()`](https://docs.python.org/3/library/itertools.html#itertools.zip_longest) functi
I take it from the text below that you don't actually use `zip_longest` in the context of task mapping (instead you would use `fillvalue`)? If that's the case I would remove this note.

2022-08-25 23:22 UTC, kentdanas commented on guides/dynamic-tasks.md
> +> **Note**: Mixing direct inputs of iterables with inputs via XComs in the `zip()` function is currently not supported.
I find this a bit confusing as it's currently worded - maybe something like "Zipping inputs defined in your DAG script with inputs pulled from XCom is not currently supported"? If I'm reading it right...

2022-08-25 23:22 UTC, kentdanas commented on guides/dynamic-tasks.md
> +It is also possible to 'zip' XComArg objects by using their `.zip()` method to combine them with one or more other XComArg objects. If the upstream task has been defined using the TaskFlowAPI simply
```suggestion
It is also possible to zip `XComArg` objects. If the upstream task has been defined using the TaskFlow API, simply provide the function call. If the upstream task used a traditional operator, provide the `XComArg(task_object)`. Below you can see an example of the results of two TaskFlowAPI tasks and one traditional operator being zipped together to form the same `zipped_arguments` (`[(1,10,100), (2,20,200), (3,30,300)]`) as in the previous example.
```

2022-08-28 14:41 UTC, TJaniF reviewed
Thank you for the review! I think the examples are much easier to follow now. I also divided the ### Zip section into two subsections one for the Python builtin function, one for the XComArg method. I hope this makes the distinction clearer :) 

@jwitz I think the update is ready for you 🙂

2022-08-28 14:41 UTC, TJaniF commented on guides/dynamic-tasks.md
> +> **Note**: Mixing direct inputs of iterables with inputs via XComs in the `zip()` function is currently not supported.
What I was trying to say is that both 

```Python 
zipped_arguments = list(zip(one_two_three(), [10,20,30))
``` 

does not work (the error is " 'XComArg' object is not iterable"); 

and

```Python
zipped_arguments = one_two_three().zip(
        [10,20,30],
        XComArg(one_two_three_hundred_task),
        fillvalue=1000
    )
```

doesn't work. It fails with the error "'list' object has no attribute 'iter_references'". That is what I meant with "no mixing" 😅 

Yeah it is confusing. I think I actually need to make the distinction clearer when introducing zip() and .zip()... I ended up putting the two in different subsections and contrasting them at the start of the "zip" section. I hope this makes more sense. :)

2022-08-29 10:25 UTC, jwitz approved these changes
Looks good! Nice job on breaking down some very complex concepts and implementations. I tried making the guide slightly easier to read by adding some more headers, but feel free to play around with my wording there and in other suggestions!

2022-08-29 10:25 UTC, jwitz commented on guides/dynamic-tasks.md
> +
```suggestion
### Map inputs to an operator-defined task from a TaskFlow API-defined task.

```

2022-08-29 10:25 UTC, jwitz commented on guides/dynamic-tasks.md
> +Passing data from an upstream task defined using the TaskFlowAPI to a downstream traditional operator works in a very similar fashion. Note that the format of the mapping information returned by the
```suggestion
Passing data from an upstream task defined using the TaskFlowAPI to a downstream traditional operator works in a very similar fashion. Note that the format of the mapping information returned by the upstream TaskFlow API task might need to be modified to be accepted by the `op_args` argument of the traditional PythonOperator.
```

2022-08-29 10:25 UTC, jwitz commented on guides/dynamic-tasks.md
> +Passing data from an upstream task defined using the TaskFlowAPI to a downstream traditional operator works in a very similar fashion. Note that the format of the mapping information returned by the
Is the last sentence specific to the PythonOperator or does that advice apply to all traditional operators?

2022-08-29 10:25 UTC, jwitz commented on guides/dynamic-tasks.md
> +
```suggestion

### Map inputs to  TaskFlow API-defined task from an operator-defined task.

```

2022-08-29 10:25 UTC, jwitz commented on guides/dynamic-tasks.md
> +If you are mapping over the results of a traditional operator, you need to extract the return value using the `XComArg` object.
```suggestion
If you are mapping over the results of a traditional operator, you need to format the argument for `expand()` using the `XComArg` object.
```

2022-08-29 10:25 UTC, jwitz commented on guides/dynamic-tasks.md
> +
```suggestion

### Map inputs when both tasks are defined with traditional operators


```

2022-08-29 10:25 UTC, jwitz commented on guides/dynamic-tasks.md
> +- **Cross-Product**: Mapping over 2 or more *keyword* arguments results in a mapped task instance for each possible combination of inputs. This type of mapping uses the `expand()` function.
```suggestion
- **Cross-product**: Mapping over 2 or more *keyword* arguments results in a mapped task instance for each possible combination of inputs. This type of mapping uses the `expand()` function.
```

2022-08-29 10:25 UTC, jwitz commented on guides/dynamic-tasks.md
> +- **Sets of keyword arguments**: Mapping over 2 or more sets of one or more *keyword* arguments results in a mapped task instance for every set. This type of mapping uses the `expand_kwargs()` functi
```suggestion
- **Sets of keyword arguments**: Mapping over 2 or more sets of one or more keyword arguments results in a mapped task instance for every defined set, rather than every combination of individual inputs. This type of mapping uses the `expand_kwargs()` function.
```

2022-08-29 10:25 UTC, jwitz commented on guides/dynamic-tasks.md
> +The nine mapped task instance of the task `cross_product_example` run all possible combinations of the bash command with the env variable:
```suggestion
The nine mapped task instances of the task `cross_product_example` run all possible combinations of the bash command with the `env` variable:
```

2022-08-29 10:25 UTC, jwitz commented on guides/dynamic-tasks.md
> +In Airflow 2.4+ you can provide sets of positional arguments to the same keyword argument, for example to the `op_args` keyword argument of the `PythonOperator`. You can use the built-in Python funct
```suggestion
In Airflow 2.4+ you can provide sets of positional arguments to the same keyword argument, such as the `op_args` argument of the PythonOperator. You can use the built-in [`zip()`] function(https://docs.python.org/3/library/functions.html#zip) Python function if your inputs are in the form of iterables such as tuples, dictionaries, or lists. If your inputs come from XCom objects, you can use the `.zip()` method of the `XComArg` object.
```

2022-08-29 10:25 UTC, jwitz commented on guides/dynamic-tasks.md
> +> **Note**: It is currently not possible to provide XComArg objects to the built-in Python function `zip()` or to directly provide iterables to the `.zip()` method of the XComArg object.
```suggestion
```

I think this is evident from the text above

2022-08-29 10:25 UTC, jwitz commented on guides/dynamic-tasks.md
> +- `zip(["a", "b", "c"], [1, 2, 3], ["hi", "bye", "tea"])` will result in a zip object containing: `("a", 1, "hi"), ("b", 2, "bye"), ("c", 3, "tea")`
```suggestion
- `zip(["a", "b", "c"], [1, 2, 3], ["hi", "bye", "tea"])` results in a zip object containing: `("a", 1, "hi"), ("b", 2, "bye"), ("c", 3, "tea")`.
```

2022-08-29 10:25 UTC, jwitz commented on guides/dynamic-tasks.md
> +- `zip(["a", "b"], [1], ["hi", "bye"], [19, 23], ["x", "y", "z"])` will result in a zip object containing only one tuple: `("a", 1, "hi", 19, "x")` because the shortest list provided only contains on
```suggestion
- `zip(["a", "b"], [1], ["hi", "bye"], [19, 23], ["x", "y", "z"])` results in a zip object containing only one tuple: `("a", 1, "hi", 19, "x")`. This is because the shortest list provided only contains one element.
```

2022-08-29 10:25 UTC, jwitz commented on guides/dynamic-tasks.md
> +- It is also possible to zip together different types of iterables: `zip(["a", "b"], {"hi", "bye"}, (19, 23))` will result in a zip object containing: `('a', 'hi', 19), ('b', 'bye', 23)`.
```suggestion
- It is also possible to zip together different types of iterables. `zip(["a", "b"], {"hi", "bye"}, (19, 23))` results in a zip object containing: `('a', 'hi', 19), ('b', 'bye', 23)`.
```

2022-08-29 10:25 UTC, jwitz commented on guides/dynamic-tasks.md
> +The code snippet below shows how a list of zipped arguments can be provided to the `expand()` function in order to create mapped tasks over sets of positional arguments. Each set of positional argume
```suggestion
The code snippet below shows how a list of zipped arguments can be provided to the `expand()` function in order to create mapped tasks over sets of positional arguments. Each set of positional arguments is passed in the keyword argument `zipped_x_y_z`.
```

2022-08-29 10:25 UTC, jwitz commented on guides/dynamic-tasks.md
> +The task `add_numbers` will have three mapped task instances each performing one calculation with the results being:
```suggestion
The task `add_numbers` will have three mapped task instances for each possible combination of positional arguments:
```

2022-08-29 10:25 UTC, jwitz commented on guides/dynamic-tasks.md
> +#### Built-in Python function zip()
```suggestion
#### Provide positional arguments with the built-in Python zip()
```

2022-08-29 10:25 UTC, jwitz commented on guides/dynamic-tasks.md
> +#### .zip() method of the XComArg object
```suggestion
#### Provide positional arguments XComArg object zip()
```

2022-08-29 10:25 UTC, jwitz commented on guides/dynamic-tasks.md
> +To mimic the behavior of the [`zip_longest()`](https://docs.python.org/3/library/itertools.html#itertools.zip_longest) function from the `itertools` package, you can add an optional keyword argument
```suggestion
To mimic the behavior of the [`zip_longest()`](https://docs.python.org/3/library/itertools.html#itertools.zip_longest) function, you can add the optional `fillvalue` keyword argument to the `.zip()` method. If you specify a default value with `fillvalue`, the method produces as many tuples as the longest input has elements and fills in missing elements with the default value. If `fillvalue` was not specified in the example below, `zipped_arguments` would only contain one tuple `[(1,10,100)]` since the shortest list provided to the `.zip()` method is only one element long.
```

2022-08-29 17:11 UTC, kentdanas approved these changes

2022-08-31 10:06 UTC, TJaniF commented
DO NOT MERGE until conforming that the example on line 216 has been implemented and take out the warning comment. :) (other than that proofreading is done and ready to merge)

2022-09-19 09:03 UTC, TJaniF reviewed
@jwitz I have no idea how I didn't see your review the last time I read through a week ago 🤔 . Sorry about that and thank you! 

Other than your edits I took out the "pending implementation" and switched out a screenshot to the 2.4 version (showing mapped task instances in the grid view). Ready to merge!

2022-09-19 15:47 UTC, TJaniF commented on guides/dynamic-tasks.md
>  In this guide, we'll explain the concept of dynamic task mapping and provide example implementations for common use cases.
```suggestion
In this guide, we'll explain the concept of dynamic task mapping and provide an example implementation for a common use case.
```

2022-09-19 15:53 UTC, merged