2.4 datasets guide
astronomer/airflow-guides pull request #427
Opened 2022-08-25 21:20 UTC by kentdanas

@jwitz I have this new 2.4 Datasets concept guide mostly ready to go - will need to add a few links to Airflow docs and release notes, but it's ready for review when you have time. Will want to publish as soon as 2.4 is released if possible.

@TJaniF feel free to take a look and comment/add anything if there's anything you see missing as you play around with the new feature.

2022-08-26 12:18 UTC, jwitz requested changes
Shoot this is a cool feature @kentdanas ! I am requesting changes based on a few of the ways we describe the new feature:

- Is a dataset really an Airflow "concept", or is this just Airflow's implementation of a wider understanding of datasets? I'm cautious about introducing it as a "new concept" when there might be a more direct way of explaining what's going on here.
- From what I can tell, these new classes and parameters are basically metadata tags that can be triggered and listened to by other DAGs. There's not really anything connecting these to the data itself right? I think we should be much more explicit about that before we start jumping into examples. The `s3` example string adds to the confusion here, as it looks like a proper connection to a database.
- Should we keep consistent with the Airflow and use "producing tasks" instead of "producing DAGs"? That might make the triggering behavior make more sense.

2022-08-26 12:18 UTC, jwitz commented on guides/airflow-datasets.md
> +Then you can reference the dataset in a task by providing it to the `outlets` parameter. `outlets` is part of the `BaseOperator`, so it is available to every Airflow operator. Defining an outlet tell
```suggestion 
You can reference the dataset in a task by passing it to the `outlets` parameter. `outlets` is part of the `BaseOperator`, so it's available to every Airflow operator. Defining an `outlet` tells Airflow that the task updates the given dataset.
```
The behavior here is a bit confusing to me. What does it mean that the task "Updates" the dataset, given that there's no actual operations to the dataset in the DAG? Which action actually triggers the consumer DAGs listening for these updates?

2022-08-26 12:18 UTC, jwitz commented on guides/airflow-datasets.md
> +Once a dataset is defined in one or more producer DAGs, any consumer DAGs in your Airflow environment can be configured to run when that dataset is updated, rather than running on a schedule. For exa
```suggestion
When you define a dataset in a DAG, it is considered a "producer" DAG. Once a dataset is defined in one or more producer DAGs, a "consumer" DAG in your Airflow environment listen to the producer DAG and run whenever the defined dataset is updated, rather than running on a time-based schedule. For example, if you have a DAG that should run when `dag1_dataset` and `dag2_dataset` are updated, you define the DAG's scheduler using the names of the datasets.
```

2022-08-26 12:18 UTC, jwitz commented on guides/airflow-datasets.md
> +- Datasets can only be used by DAGs in the *same* Airflow environment.
```suggestion
- Datasets can only be used by DAGs in the same Airflow environment.
```

2022-08-26 12:18 UTC, jwitz commented on guides/airflow-datasets.md
> +- For now, Airflow only monitors datasets within the context of DAGs and tasks. It does not monitor updates to datasets within an external system that occur outside of Airflow.
```suggestion
- Airflow monitors datasets only within the context of DAGs and tasks. It does not monitor updates to datasets that occur outside of Airflow.
```

2022-08-26 12:18 UTC, jwitz commented on guides/airflow-datasets.md
> +- Consumer DAGs that are scheduled on a dataset will be triggered every time that dataset is updated. For example, if `DAG1` and `DAG2` both produce `dataset_a`, a consumer DAG of `dataset_a` will ru
```suggestion
- Consumer DAGs that are scheduled on a dataset are triggered every time that dataset is updated. For example, if `DAG1` and `DAG2` both produce `dataset_a`, a consumer DAG of `dataset_a` runs twice: First when `DAG1` completes, and again when `DAG2` completes.
```
Should we clarify that a DAG will run twice if you specify multiple datasets to listen to, even if they come from one producer DAG? It's a bit confusing that we're explaining that the consumer DAGS are listening to producer DAGs, when what they're really listening to is the datasets themselves.

2022-08-26 12:18 UTC, jwitz commented on guides/airflow-datasets.md
> +- Consumer DAGs scheduled on a dataset will be triggered as soon as the first *task* with that dataset as an outlet finishes, even if there are downstream tasks in the producer DAG that also operate
```suggestion
- Consumer DAGs scheduled on a dataset are triggered as soon as the first *task* with that dataset as an outlet finishes, even if there are downstream tasks in the producer DAG that also operate on the dataset.
```
If multiple outlets are defined for a single dataset, will a consumer DAG run multiple times for each outlet?

2022-08-26 12:18 UTC, jwitz commented on guides/airflow-datasets.md
> +## Example Implementation
```suggestion
## Example implementation
```

2022-08-28 16:05 UTC, TJaniF approved these changes
Looks great! 🙂  I didn't have much to add to Jake's comments. A few suggestions and some code formatting in the example (I ran it through flake8).

2022-08-29 08:59 UTC, TJaniF commented on guides/airflow-datasets.md
> +Airflow's datasets feature allows you to define datasets in your Airflow environment and use them to create dependencies between DAGs. You can define a dataset by instantiating the `Dataset` class an
I just read the WIP airflow docs on datasets that Ash tagged us on in Slack and it contains this:

```markdown
There are three restrictions on the dataset identifier:
    1. It must be a valid URI, which means it must only be composed of only ASCII characters.
    2. The URI scheme cannot be airflow (this is reserved for possible future use).
    3. It must be unique (although the case is sensitive, so “example_dataset” and “Example_Dataset” are considered different).
```

As far as I can tell only the ASCII character restriction is enforced (I'm getting an error when trying non-ASCII characters but having the dataset name "a" twice does not throw an error). 

So maybe we should add something like for future Airflow version compatibility follow these naming conventions: ... ?

2022-08-29 09:07 UTC, TJaniF commented on guides/airflow-datasets.md
> +- Consumer DAGs scheduled on a dataset will be triggered as soon as the first *task* with that dataset as an outlet finishes, even if there are downstream tasks in the producer DAG that also operate
```suggestion
- Consumer DAGs scheduled on a dataset will be triggered as soon as the first *task* with that dataset as an outlet finishes successfully, even if there are downstream tasks in the producer DAG that also operate on the dataset.
```

2022-08-29 15:24 UTC, kentdanas commented on guides/airflow-datasets.md
> +Then you can reference the dataset in a task by providing it to the `outlets` parameter. `outlets` is part of the `BaseOperator`, so it is available to every Airflow operator. Defining an outlet tell
Yeah this part is a bit confusing at first - right now, Airflow has no idea what the dataset actually is or what is happening to it. So it's up to the DAG author to specify the dataset as an `outlet` if they know that particular task does something to the dataset. But just because you specify an `outlet` doesn't mean that task actually does anything to the dataset (the examples with the BashOperator highlight this - we create the dependency, but Bash doesn't actually do anything). The completion of the task with the `outlet` specified is the trigger for the consumer DAG. 

So you can kind of think of it as like a more sophisticated external task sensor in how it behaves right now - except we don't want to describe it that way because this is very much a starting point for the broader data awareness feature and it will get smarter with future releases.

2022-08-29 15:25 UTC, kentdanas commented on guides/airflow-datasets.md
> +- Consumer DAGs scheduled on a dataset will be triggered as soon as the first *task* with that dataset as an outlet finishes, even if there are downstream tasks in the producer DAG that also operate
Yes, I can add a bullet to clarify that

2022-08-29 15:30 UTC, kentdanas commented on guides/airflow-datasets.md
> +In this example, a data engineering team has a DAG that publishes data to S3. Then a data science team has another DAG that uses that data to train a Sagemaker model and publish the results to Redshi
Yeah that's fair :)

2022-08-29 15:33 UTC, kentdanas commented on guides/airflow-datasets.md
> +The release of [Airflow 2.4](link release notes!) includes a new concept of datasets and data dependencies. This means that DAGs that touch the same data will have explicit, visible relationships, an
I guess it's both - datasets are shown along with the DAGs in the dependencies graph in the UI

2022-08-29 15:41 UTC, kentdanas commented on guides/airflow-datasets.md
> +Airflow's datasets feature allows you to define datasets in your Airflow environment and use them to create dependencies between DAGs. You can define a dataset by instantiating the `Dataset` class an
I was having a hard time describing this part of the feature in its current state - they designed the `Datasets` class to be defined by a URI, presumably because eventually Airflow might actually track that dataset where it is. But right now, it's just a name identifier - so Airflow only knows "these tasks/DAGs are connected because this name is defined as an outlet in one and a schedule in another". It has no concept yet of what the dataset actually is/contains or whether it has been changed.

2022-08-29 15:48 UTC, kentdanas commented on guides/airflow-datasets.md
> +- Consumer DAGs that are scheduled on a dataset will be triggered every time that dataset is updated. For example, if `DAG1` and `DAG2` both produce `dataset_a`, a consumer DAG of `dataset_a` will ru
They're not really listening to the 'datasets' themselves, because Airflow doesn't actually know what those datasets are yet. They're listening for a task or set of task instances completing, and they know which tasks to care about based on the datasets you define.

If the DAG listens to multiple datasets, it will only run once all of them have been updated (so it wouldn't run twice as you're describing, I think).

2022-08-29 15:51 UTC, kentdanas commented on guides/airflow-datasets.md
> +dataset_uri = 's3://' + test_s3_key
Yeah I took this DAG directly from the registry and didn't want to update the comments too much in case people actually cared about the substance. Could always update the keys I guess to something shorter if it looks weird after we publish.

2022-08-29 16:32 UTC, kentdanas commented
Thanks for the review @jwitz @TJaniF! I made some changes in the concepts section to try to clarify the confusing parts, let me know if these help. 

And Jake, to answer your high level questions:

- I guess you're right that datasets aren't a concept unique to Airflow. Sort of in the same way that I think of "Airflow scheduling" as a concept, even though scheduling is obviously a broader concept with an Airflow application. But it does mean something unique in the application to Airflow specifically. I suppose the new concept here is really "data awareness", but since 2.4 is starting small with this we don't really talk about it. Not sure if that helps, but all of that to say, I think your updates to the language are fine. Let me know if you think there are other places we need to clarify this though.
- You are correct - datasets are just metadata tags that can be used cross-DAG to create dependencies. I tried to add some language to be more explicit about that, but let me know if we still need more. I think everybody, myself included, has been confused about this when first learning about the feature - a side effect of them setting up usage for future work that hasn't been implemented yet - so we definitely want to reduce that if possible.
- Good call on "producing tasks" - updated the language throughout

2022-08-30 10:18 UTC, jwitz commented on guides/airflow-datasets.md
> +You can define datasets in your Airflow environment and use them to create dependencies between DAGs. To define a dataset, instantiate the `Dataset` class and provide a name for the dataset. The name
```suggestion
You can define datasets in your Airflow environment and use them to create dependencies between DAGs. To define a dataset, instantiate the `Dataset` class and provide a string to identify the location of the dataset. This string must be in the form of a valid Uniform Resource Identifier (URI). 

In 2.4, Airflow does not use this URI to connect to an external system and has no awareness of the content or location of the dataset. However, using this naming convention helps you to easily identify the datasets that your DAG accesses and ensures compatibility with future Airflow features.
```
I think "name" could be confusing because the dataset has its own name as well as the string you pass it, so I tried to be more explicit

2022-08-30 10:18 UTC, jwitz commented on guides/airflow-datasets.md
> +You can reference the dataset in a task by passing it to the `outlets` parameter. `outlets` is part of the `BaseOperator`, so it's available to every Airflow operator. Defining an `outlet` tells Airf
```suggestion
You can reference the dataset in a task by passing it to the task's `outlets` parameter. `outlets` is part of the `BaseOperator`, so it's available to every Airflow operator. Defining an `outlet` tells Airflow that the task updates the given dataset. Note that it is up to the DAG author to figure out which tasks should be considered producer tasks for a dataset. You can define an `outlet` dataset on any task, even if that task doesn't actually operate on a dataset (for example, the sleeping BashOperator examples below).
```

2022-08-30 10:23 UTC, jwitz commented on guides/airflow-datasets.md
> +This DAG has a single task, `upload_data_to_s3`, that publishes the data. An outlet dataset is defined in the `@task` decorator: `outlets=Dataset(dataset_uri)` (where the dataset URI is defined at th
```suggestion
This DAG has a single task, `upload_data_to_s3`, that publishes the data. An outlet dataset is defined in the `@task` decorator using `outlets=Dataset(dataset_uri)` (where the dataset URI is defined at the top of the DAG script).
```

2022-08-30 10:27 UTC, jwitz commented on guides/airflow-datasets.md
> +Then the data science team can provide that same dataset URI to the schedule parameter in their DAG:
```suggestion 
The data science team can then provide that same dataset URI to the schedule parameter in their DAG:
```

2022-08-30 10:28 UTC, jwitz commented on guides/airflow-datasets.md
> +This dependency between the two DAGs is simple to implement and is easily viewed in the Airflow UI.
```suggestion
This dependency between the two DAGs is simple to implement and is can be viewed alongside the dataset in the Airflow UI.
```

2022-08-30 10:31 UTC, jwitz approved these changes
Nice job with both simplifying and clarifying on this edit! My only other thought is that it might be helpful to be even more explicit with the known limitations of this feature. We currently say that the URI is in place to ensure "compatibility" with future Airflow releases, but can we also say how it might be used and for what features? If we can't make any promises or allusions to those features yet then it's fine as is, but providing that context might help people make more sense of the datasets feature in this early stage.

2022-08-30 15:17 UTC, kentdanas commented
Thanks @jwitz! I'm hesitant to talk about future work here because I'm not entirely sure if it has been decided on yet. But maybe can add some details down the line once that work has started.

2022-09-01 10:37 UTC, TJaniF commented on guides/airflow-datasets.md
> +![Datasets View](https://assets2.astronomer.io/main/guides/data-driven-scheduling/datasets_view.png)
Putting a reminder comment here to update the datasets view once we know the final format (and potentially include the datasets details view, if those will still be separate) 🙂

2022-09-08 22:46 UTC, mikeshwe commented on guides/airflow-datasets.md
> +
```suggestion
As long as a task is scheduled via a `Dataset`, Airflow considers it a consumer task even if that task doesn't technically consume the referenced dataset. In other words, it is up to the DAG author of the consumer DAG to correctly reference and use the `Dataset` that the consumer DAG is scheduled on.
```

As a parallel for the clarifying comment you have for the provider DAG. Also, I think it's important to clarify that you essentially have to reference that `Dataset` at least twice in the consuming code-- once for scheduling and then once when you actually consume it.

BTW, do you think we should treat `Dataset` as a reserved word, and provide the usual affordances thereof, e.g, calling it out as a code word with the reverse apostrophes?>

2022-09-08 22:46 UTC, mikeshwe commented on guides/airflow-datasets.md
> +
Looks great! I made a little suggestion.

2022-09-13 20:45 UTC, kentdanas commented on guides/airflow-datasets.md
> +
Thanks @mikeshwe! I think it makes sense to add this clarification. 

As far as "datasets" go, Jake and I discussed earlier and decided that it doesn't need to be a reserved word because a dataset is a concept that exists outside of Airflow as well. Similar to how we would treat "schedule" or "pool" or something like that.

2022-09-13 20:47 UTC, kentdanas commented on guides/airflow-datasets.md
> +As long as a task is scheduled via a `Dataset`, Airflow considers it a consumer task even if that task doesn't technically consume the referenced dataset. In other words, it is up to the DAG author o
```suggestion

As long as a task is scheduled via a dataset, Airflow considers it a consumer task even if that task doesn't technically consume the referenced dataset. In other words, it is up to you as the DAG author to correctly reference and use the dataset that the consumer DAG is scheduled on.

```

2022-09-19 09:23 UTC, TJaniF reviewed
Just adding links to the release notes and the new data-aware scheduling docs :)

2022-09-19 09:23 UTC, TJaniF commented on guides/airflow-datasets.md
> +The release of [Airflow 2.4](link release notes!) introduces datasets and data dependencies. This means that DAGs which access the same data now have explicit, visible relationships, and that DAGs ca
```suggestion
The release of [Airflow 2.4](https://airflow.apache.org/docs/apache-airflow/2.4.0/release_notes.html#airflow-2-4-0-2022-09-19) introduces datasets and data dependencies. This means that DAGs which access the same data now have explicit, visible relationships, and that DAGs can be scheduled based on updates to these datasets. This feature is a big step forward in making Airflow data-aware and vastly expands Airflow's scheduling capabilities beyond time-based methods like Cron.
```

2022-09-19 09:23 UTC, TJaniF commented on guides/airflow-datasets.md
> +LINK HERE TO AIRFLOW DOCS
```suggestion
> **Note**: You can find more information on datasets in the [Airflow documentation page on data-aware scheduling](https://airflow.apache.org/docs/apache-airflow/2.4.0/concepts/datasets.html). 
```

2022-09-19 12:11 UTC, jwitz commented on guides/airflow-datasets.md
> +title: "Datasets and Data Driven Scheduling in Airflow"
```suggestion
title: "Datasets and Data-Aware Scheduling in Airflow"
```
Should we match Airflow's use of "data-aware"? https://airflow.apache.org/docs/apache-airflow/2.4.0/concepts/datasets.html

If you think so, we should update all uses of "data driven"/ "data-driven" in this guide

2022-09-19 14:47 UTC, kentdanas commented on guides/airflow-datasets.md
> +title: "Datasets and Data Driven Scheduling in Airflow"
Yes we should, I'll update that today

2022-09-19 14:57 UTC, merged