2.4 update to the Scheduling guide
astronomer/airflow-guides pull request #429
Opened 2022-08-28 23:30 UTC by TJaniF

- added a new short section on data driven scheduling
- changed `schedule_interval` to `schedule` where appropriate
- updated the screenshots in the parameter example 
- updated some links and styles

I didn't touch the timetables section other than some style things. My main question on that would be if timetables are still considered plugins? I'm a little confused why the `UnevenIntervalsTimetablePlugin` class is necessary 🤔

2022-08-29 18:26 UTC, kentdanas requested changes
Thanks for the update @TJaniF! This guide is a behemoth :) left a couple of questions on how we should talk about things with the new updates - let's discuss tomorrow. Otherwise this should be pretty good to go.

2022-08-29 18:26 UTC, kentdanas commented on guides/scheduling-in-airflow.md
> +Airflow 2.4 introduced the concept of Datasets and with it the ability to schedule your DAG depending on other DAGs touching specific data objects. A more in-depth explanation on these features can b
```suggestion
Additionally, Airflow 2.4 introduced datasets and the ability to schedule your DAGs on updates to a dataset rather than a time-based schedule. A more in-depth explanation on these features can be found in the [Datasets and Data Driven Scheduling in Airflow](https://www.astronomer.io/guides/airflow-datasets/) guide.
```

2022-08-29 18:26 UTC, kentdanas commented on guides/scheduling-in-airflow.md
> +- The concept and parameters of an Airflow DAG. See [Introduction to Airflow DAGs](https://www.astronomer.io/guides/dags/).
```suggestion
- Parameters of Airflow DAGs. See [Introduction to Airflow DAGs](https://www.astronomer.io/guides/dags/).
```

2022-08-29 18:26 UTC, kentdanas commented on guides/scheduling-in-airflow.md
> +- How to interact with date and time in Python3. See the [Python documentation on the `datetime` package](https://docs.python.org/3/library/datetime.html).
```suggestion
- Date and time modules in Python3. See the [Python documentation on the `datetime` package](https://docs.python.org/3/library/datetime.html).
```

2022-08-29 18:26 UTC, kentdanas commented on guides/scheduling-in-airflow.md
> +- **`schedule`**: A parameter that can be set at the DAG level to define when that DAG will be run. In Airflow 2.3 or older, this parameter is called `schedule_interval`. It accepts cron expressions,
```suggestion
- **`schedule`**: A parameter that can be set at the DAG level to define when that DAG will be run. In Airflow 2.3 or older, this parameter is called `schedule_interval`. It accepts cron expressions, timedelta objects, timetables, and lists of datasets.
```

I'm taking out the note about everything being converted to timetables under the hood, because I'm guessing that's not actually true of datasets (also a potentially confusing thing that users probably don't actually need to know about).

2022-08-29 18:26 UTC, kentdanas commented on guides/scheduling-in-airflow.md
> +- **`timetable`**: A parameter that can be set at the DAG level to define its timetable (either custom or built-in). Timetables can be defined explicitly within the DAG (more on this below), or will
I think that this parameter is actually going away in favor of the combined `schedule`, so we should remove this bullet entirely.

2022-08-29 18:26 UTC, kentdanas commented on guides/scheduling-in-airflow.md
> +For pipelines with basic schedules, you can define a `schedule` in your DAG. For versions of Airflow prior to 2.2, this (with the parameter being named `schedule_interval`) is the *only* mechanism fo
```suggestion
For pipelines with basic schedules, you can define a `schedule` in your DAG. For versions of Airflow prior to 2.2, this (with the parameter being named `schedule_interval`) is the *only* mechanism for defining a DAG's schedule.
```
I think we should put a "> Note:" somewhere about the schedule_interval to schedule change, and then probably don't need to mention it every time.

2022-08-29 18:26 UTC, kentdanas commented on guides/scheduling-in-airflow.md
> +### Setting a schedule interval
Think we should update this to "Setting a schedule"?

2022-08-29 18:26 UTC, kentdanas commented on guides/scheduling-in-airflow.md
> +### Schedule limitations
Since "schedule" now applies to everything, I wonder if we need to rename this section and some of the language a bit. Like..."Cron schedule limitations"....?

2022-08-29 18:26 UTC, kentdanas commented on guides/scheduling-in-airflow.md
> +Going forward, timetables will become the primary method for scheduling in Airflow. You can still define a `schedule`, but Airflow converts this to a timetable behind the scenes. And if a cron expres
Wonder if we should just remove this comment? I think with the simplification to one parameter this is maybe less relevant (or maybe always just added confusion)?

2022-08-29 18:26 UTC, kentdanas commented on guides/scheduling-in-airflow.md
> +Airflow 2.4 introduced the concept of Datasets and data driven cross-DAG dependencies. In short, this means that you can make Airflow aware of the fact that a task in a DAG updated a data object, for
```suggestion
Airflow 2.4 introduced the concept of datasets and data driven cross-DAG dependencies. In short, this means that you can make Airflow aware of the fact that a task in a DAG updated a data object. Using that awareness, other DAGs can be scheduled depending on these updates to datasets. To do so, you simply pass the names of the datasets a list to the `schedule` parameter.
```

2022-08-29 18:26 UTC, kentdanas commented on guides/scheduling-in-airflow.md
> +The DAG defined above will only run, once both `dataset1` and `dataset2` have been flagged as updated. These updates can occur by different tasks in different DAGs as long as they are located in the
```suggestion
The DAG defined above will only run once both `dataset1` and `dataset2` have been updated. These updates can occur by different tasks in different DAGs as long as they are located in the same Airflow environment.
```

2022-08-29 18:26 UTC, kentdanas commented on guides/scheduling-in-airflow.md
> +In the Airflow UI the schedule of the DAG will be shown as `Dataset` and the Next Run column informs you how many datasets the DAG depends on and how many of them have been updated already.
```suggestion
In the Airflow UI, the schedule of the DAG will be shown as `Dataset` and the Next Run column informs you how many datasets the DAG depends on and how many of them have been updated already.
```

2022-08-29 18:26 UTC, kentdanas commented on guides/scheduling-in-airflow.md
> +To learn more about Datasets and data driven scheduling check out the [Datasets and Data Driven Scheduling in Airflow](https://www.astronomer.io/guides/airflow-datasets/) guide.
```suggestion
To learn more about datasets and data driven scheduling, check out the [Datasets and Data Driven Scheduling in Airflow](https://www.astronomer.io/guides/airflow-datasets/) guide.
```

2022-08-30 14:25 UTC, TJaniF reviewed
Thank you for the review @kentdanas 🙂 ! I made some adjustments to section headers and put a note about former parameters/parameter names in the parameters section.

2022-08-30 19:54 UTC, kentdanas approved these changes
LGTM @TJaniF! Thanks for helping clarify things in here. I think we're good to move on to copy editing, which will hopefully be straight forward :)

2022-08-30 19:54 UTC, kentdanas commented on guides/scheduling-in-airflow.md
> +In the sections below, we'll walk through how to use the `schedule` parameter or timetables to schedule your DAG.
```suggestion
In the sections below, we'll walk through how to use cron-based schedule, timetables, or datasets to schedule your DAG.
```

2022-08-30 19:54 UTC, kentdanas commented on guides/scheduling-in-airflow.md
> +- a cron expression
```suggestion
- A cron expression
```

2022-08-30 19:54 UTC, kentdanas commented on guides/scheduling-in-airflow.md
> +- a cron preset
```suggestion
- A cron preset
```

2022-08-30 19:54 UTC, kentdanas commented on guides/scheduling-in-airflow.md
> +- a timedelta object
```suggestion
- A timedelta object
```

2022-08-30 19:54 UTC, kentdanas commented on guides/scheduling-in-airflow.md
> +The DAG defined above will only run once both `dataset1` and `dataset2` have been updated. These updates can occur by different tasks in different DAGs as long as they are located in the same Airflow
```suggestion
The DAG defined above will only run once both `dataset1` and `dataset2` have been updated. These updates can occur by tasks in different DAGs as long as they are located in the same Airflow environment.
```

2022-09-01 13:02 UTC, TJaniF commented
Thank you! @jwitz I hope this one wont take too long. The main adjustments were the parameter change from "schedule_interval" to "schedule" and changing some language around that and timetables plus a small new section explaining the concepts of datasets and linking out to the new guide 🙂

2022-09-02 11:20 UTC, jwitz approved these changes
Just a few minor suggestions, otherwise LGTM! Feel free to ignore some of the edits I made about traditional scheduling since that's outside of the scope of this review, but I wanted to get the thoughts down somewhere.

2022-09-02 11:20 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +One of the most fundamental features of Apache Airflow is the ability to schedule jobs. Historically, Airflow users could schedule their DAGs by specifying a `schedule` with a cron expression, a time
```suggestion
One of the fundamental features of Apache Airflow is the ability to schedule jobs. Historically, Airflow users could schedule their DAGs by specifying a `schedule` with a cron expression, a timedelta object, or a preset Airflow schedule.
```

2022-09-02 11:20 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +- What Airflow is and when to use it. See [Introduction to Apache Airflow](https://www.astronomer.io/guides/intro-to-airflow).
```suggestion
- Basic Airflow concepts. See [Introduction to Apache Airflow](https://www.astronomer.io/guides/intro-to-airflow).
```

2022-09-02 11:20 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +- Parameters of Airflow DAGs. See [Introduction to Airflow DAGs](https://www.astronomer.io/guides/dags/).
```suggestion
- Configuring Airflow DAGs. See [Introduction to Airflow DAGs](https://www.astronomer.io/guides/dags/).
```

2022-09-02 11:20 UTC, jwitz commented on guides/scheduling-in-airflow.md
>  ### Terms
```suggestion
```

2022-09-02 11:20 UTC, jwitz commented on guides/scheduling-in-airflow.md
```suggestion
```

2022-09-02 11:20 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +> Note: in this guide we do not cover the `execution_date` concept, which has been deprecated as of Airflow 2.2. If you are using older versions of Airflow, review [this doc](https://airflow.apache.o
```suggestion
> Note: In this guide we do not cover the `execution_date` concept, which has been deprecated as of Airflow 2.2. If you are using older versions of Airflow, review [this doc](https://airflow.apache.org/docs/apache-airflow/stable/faq.html#faq-what-does-execution-date-mean) for more on `execution_date`.
```

2022-09-02 11:20 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +> **Note** In Airflow 2.3 or older, the `schedule` parameter was called `schedule_interval` and only accepted cron expressions or timedelta objects. Timetables had to be passed to Airflow using the n
```suggestion
> **Note** In Airflow 2.3 or older, the `schedule` parameter is called `schedule_interval` and only accepts cron expressions or timedelta objects. Additionally, timetables have to be passed using the `timetable` parameter, which is deprecated in Airflow 2.4+. In versions of Airflow 2.2 and earlier, specifying `schedule_interval` is the only way to define a DAG's schedule.
```
I tried rewriting this note to make 2.3 sound less past-tense, as there will still be plenty of people using that version who might look to this guide for guidance.

2022-09-02 11:20 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +If we look at the next run in the UI, the logical date is `2022-08-28 22:42:33`. This is 5 minutes after the previous logical date, and the same as the `data_interval_end` of the last DAG run since t
```suggestion
If we look at the next DAG run in the UI, the logical date is `2022-08-28 22:42:33`. This is 5 minutes after the previous logical date, and the same as the **Data interval end** of the last DAG run because there are no gaps in the schedule. If we hover over **Next Run**, we can see that **Run After**, which is the date and time that the next DAG run is scheduled for, is also the same as the current DAG run's **Data interval end**:
```

2022-09-02 11:20 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +As a simple example of how these concepts work together, say we have a DAG that is scheduled to run every 5 minutes. Taking the most recent DAG run, the logical date is `2022-08-28 22:37:33`, which i
```suggestion
As a simple example of how these concepts work together, say we have a DAG that is scheduled to run every 5 minutes. Looking at the most recent DAG run, the logical date is `2022-08-28 22:37:33`, which is the same as the **Data interval start** shown in the bottom right corner of in the screenshot below. The **Data interval end** is 5 minutes later.
```

2022-09-02 11:20 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +If we look at the next run in the UI, the logical date is `2022-08-28 22:42:33`. This is 5 minutes after the previous logical date, and the same as the `data_interval_end` of the last DAG run since t
For some reason, extending this example so that it extends across 3 DAG runs is really confusing to me. I think it's because I was trying to understand something new about the schedule from the second example, when in reality it's a repeat of the example before. Maybe we should keep this to a single example?

I understand that this is sort of out of the scope of the 2.4 edits, so feel free to ignore and we can update this at another time.

2022-09-02 11:20 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +- A timedelta object
```suggestion
- A cron expression.
- A cron preset.
- A timedelta object.
```

2022-09-02 11:20 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +Airflow was originally developed for ETL under the expectation that data is constantly flowing in from some source and then will be summarized on a regular interval. If you want to summarize Monday's
```suggestion
Airflow was originally developed for ETL under the expectation that data is constantly flowing in from some source and then will be summarized on a regular interval. If you want to summarize Monday's data, you can only do it after Monday is over (Tuesday at 12:01 AM). However, this assumption has turned out to be ill-suited to the many other things Airflow is being used for now. This discrepancy is what led to Timetables, which were introduced in Airflow 2.2.
```

2022-09-02 11:20 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +Airflow 2.4 introduced the concept of datasets and data driven cross-DAG dependencies. In short, this means that you can make Airflow aware of the fact that a task in a DAG updated a data object. Usi
```suggestion
Airflow 2.4 introduced the concept of datasets and data-driven DAG dependencies. You can now make Airflow detect when a task in a DAG updates a data object. Using that awareness, other DAGs can be scheduled depending on updates to these datasets. To create a dataset-based schedule, you simply pass the names of the datasets as a list to the `schedule` parameter.
```

2022-09-02 11:20 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +The DAG defined above will only run once both `dataset1` and `dataset2` have been updated. These updates can occur by tasks in different DAGs as long as they are located in the same Airflow environme
```suggestion
This DAG runs only when both `dataset1` and `dataset2` have been updated. These updates can occur by tasks in different DAGs as long as they are located in the same Airflow environment.
```
Does it have to be both? I must not have caught that in the datasets guide! Is there a syntax for running the DAG when _either_ dataset runs?

2022-09-02 11:20 UTC, jwitz commented on guides/scheduling-in-airflow.md
> +In the Airflow UI, the schedule of the DAG will be shown as `Dataset` and the Next Run column informs you how many datasets the DAG depends on and how many of them have been updated already.
```suggestion
In the Airflow UI, the DAG now has a schedule of **Dataset** and the **Next Run** column shows how many datasets the DAG depends on and how many of them have been updated.
```

2022-09-06 08:38 UTC, TJaniF reviewed
Thank you for the review Jake! 🙂 Accepted all suggestions and made some changes to the example to hopefully make it clearer.

2022-09-06 08:38 UTC, TJaniF commented on guides/scheduling-in-airflow.md
> +If we look at the next run in the UI, the logical date is `2022-08-28 22:42:33`. This is 5 minutes after the previous logical date, and the same as the `data_interval_end` of the last DAG run since t
I think the reason why the example is confusing is because it is a bit vague about how many DAG runs and which of them it is talking about at any point. (I want to write "almost wrong" in the explanation of **Run After** which... not a great sign if I can't definitively say if it is right or wrong 😅) Yeah, I may have muddled this when editing it with new times or the meaning of "Run After" and "Next Run" changed between versions. 🤔 

I edited it to only talk about 2 DAG runs and list them explicitly again at the end including all their timestamps. That way it is hopefully clearer but we still explain what **Next Run** and **Run after** are. @kentdanas and @jwitz what do you think? 🙂

2022-09-06 16:08 UTC, kentdanas commented on guides/scheduling-in-airflow.md
> +As a simple example of how these concepts work together, say we have a DAG that is scheduled to run every 5 minutes. Looking at the most recent DAG run, the logical date is `2022-08-28 22:37:33` (sho
```suggestion
As a simple example of how these concepts work together, say we have a DAG that is scheduled to run every 5 minutes. Looking at the most recent DAG run, the logical date is `2022-08-28 22:37:33` (shown below **Run** next to the DAG name in the UI), which is the same as the **Data interval start** shown in the bottom right corner of in the screenshot below. The logical date is also the timestamp that will be incorporated into the **Run ID** of the DAG run which is how the DAG run is identified in the Airflow metadata database. The **Data interval end** is 5 minutes later.
```

2022-09-06 16:13 UTC, kentdanas commented on guides/scheduling-in-airflow.md
> +In summary we've described 2 DAG runs:
@TJaniF this summary is helpful, thanks for adding it! These concepts are super confusing in general, but I think this is as good a way I can think of for clarifying them.

2022-09-19 14:47 UTC, merged