2.4 updated of the cross-DAG dependencies guide
astronomer/airflow-guides pull request #430
Opened 2022-08-29 08:19 UTC by TJaniF

- added assumed knowledge section 
- added Dataset driven scheduling section 
- added a second screenshot to the section on the DAG dependencies view
- small changes throughout to mention datasets where appropriate and updated/added some links

2022-08-29 18:02 UTC, kentdanas requested changes
Thanks for this @TJaniF, looks good! A couple of high level thoughts in addition to my comments:

- I think that given planned future work, we should make dataset driven dependencies kind of front and center in this guide. So maybe let's put that section first.
- Related, I think we should add a bit of context on when to use datasets vs triggerdagrun or externaltasksensor, because there's definitely some overlap there. I think we should position it as datasets first (and maybe add an extra sentence or two on use cases for datasets), and then in the triggerdagrun and externaltasksensor sections, be explicit about using those when datasets aren't appropriate (we can chat through what those cases would be in our 1:1 if that would be helpful)

2022-09-01 13:58 UTC, TJaniF commented on guides/cross-dag-dependencies.md
>  ## Cross-Deployment Dependencies
As discussed the feature is only in the early stages of being made possible so I'm going to resolve the comment :)

2022-09-01 20:09 UTC, kentdanas approved these changes
Looks great @TJaniF! My only additional comment would be that we could update the external task sensor example to show a DAG that branches, just to highlight the use case we're suggesting. I think that would be helpful, but let me know if you think it's not worth the effort.

Otherwise I think we can move on to copy edit :)

2022-09-01 20:09 UTC, kentdanas commented on guides/cross-dag-dependencies.md
> +In Airflow 2.4+, you can use datasets to create data driven dependencies between DAGs. This means that DAGs which access the same data can have explicit, visible relationships, and that DAGs can be s
```suggestion
In Airflow 2.4+, you can use datasets to create data-driven dependencies between DAGs. This means that DAGs which access the same data can have explicit, visible relationships, and that DAGs can be scheduled based on updates to these datasets. Downstream DAGs can be made dependent on an arbitrary number of datasets to be updated.
```

2022-09-01 20:09 UTC, kentdanas commented on guides/cross-dag-dependencies.md
> +This method is useful when a downstream DAG should only run after one or more datasets have been updated by one or more upstream DAGs, especially if those updates can be very irregular. Additionally,
```suggestion
You should use this method if you have a downstream DAG that should only run after one or more datasets have been updated by one or more upstream DAGs, especially if those updates can be very irregular. Additionally, you will have increased observability into the dependencies between your DAGs and datasets in the Airflow UI (see the 'DAG dependencies View' section).
```

2022-09-01 20:09 UTC, kentdanas commented on guides/cross-dag-dependencies.md
> +A common use case is that the upstream DAG fetches new testing data for a machine learning pipeline, runs and tests a model and then publishes the model's prediction. In case of the model underperfor
```suggestion
A common use case for this implementation is when an upstream DAG fetches new testing data for a machine learning pipeline, runs and tests a model, and publishes the model's prediction. In case of the model underperforming, the `TriggerDagRunOperator` is used to kick off a separate DAG that retrains the model, while the upstream DAG waits. Once the model is retrained and tested by the downstream DAG, the upstream DAG resumes and goes on to publish the new model's results.
```

2022-09-01 20:09 UTC, kentdanas commented on guides/cross-dag-dependencies.md
> +The `TriggerDagRunOperator` is ideal for situations in which you want one upstream DAG to run up to a specific task, trigger a downstream DAG and then continue running the next task in the upstream D
```suggestion
The `TriggerDagRunOperator` is ideal for situations in which you want to trigger a downstream DAG in the middle of the upstream DAG, and then continue running the next task in the upstream DAG as soon as the downstream DAG has finished running. This behavior can be achieved by setting the parameters `wait_for_completion` of the `TriggerDagRunOperator` to `True` (`False` by default).
```

2022-09-01 20:09 UTC, kentdanas commented on guides/cross-dag-dependencies.md
> +This method of creating cross-DAG dependencies is especially useful when you have a downstream DAG with different branches that depend on different tasks in one or more upstream DAGs to have succeede
```suggestion
This method of creating cross-DAG dependencies is especially useful when you have a downstream DAG with different branches that depend on different tasks in one or more upstream DAGs. Instead of defining an entire DAG as being downstream of another DAG like with datasets, you can define specific tasks in a downstream DAG as having to wait for a specific task to finish in an upstream DAG.
```

2022-09-01 20:09 UTC, kentdanas commented on guides/cross-dag-dependencies.md
> +Note that f your dependent DAG requires a config input or a specific execution date, these can be specified in the operator using the `conf` and `execution_date` params respectively.
```suggestion
Note that if your dependent DAG requires a config input or a specific execution date, these can be specified in the operator using the `conf` and `execution_date` params respectively.
```

2022-09-02 09:44 UTC, TJaniF commented
That is a great idea @kentdanas! I changed the example to have 3 branches 🙂. 
 @jwitz another one that needed some updates for 2.4 😅. The main change was adding a datasets section at the start and being more specific with the use cases for each method.

2022-09-19 10:23 UTC, TJaniF commented on guides/cross-dag-dependencies.md
> +![DAG Dependencies View Datasets](https://assets2.astronomer.io/main/guides/cross-dag-dependencies/2_4_CrossGuide_Dependencies.png)
```suggestion
![DAG Dependencies View Datasets](https://assets2.astronomer.io/main/guides/cross-dag-dependencies/2_4_CrossGuide_Dependencies.png)

In Airflow 2.4 an additional **Datasets** tab was added, which shows all dependencies between datasets and DAGs.
![DAG Dependencies View Datasets](https://assets2.astronomer.io/main/guides/cross-dag-dependencies/2_4_Datasets.png)
```

2022-09-19 10:29 UTC, TJaniF commented on guides/cross-dag-dependencies.md
> +In Airflow 2.4 an additional **Datasets** tab was added, which shows all dependencies between datasets and DAGs.
```suggestion
In Airflow 2.4 an additional **Datasets** tab was added, which shows all dependencies between datasets and DAGs.

```

2022-09-19 10:42 UTC, jwitz commented on guides/cross-dag-dependencies.md
> +- A DAG should only run after one or more datasets have been updated by tasks in other DAGs.
Move this point towards the end of the list because it's a little more complex of a use case?

2022-09-19 11:22 UTC, jwitz approved these changes
Looks good @TJaniF ! Just a few wording/ styling suggestions.

2022-09-19 11:58 UTC, TJaniF reviewed
Thank you @jwitz ! :)

2022-09-19 11:58 UTC, TJaniF commented on guides/cross-dag-dependencies.md
> +- A DAG should only run after one or more datasets have been updated by tasks in other DAGs.
I... can't figure out what you mean I'm sorry 😅 The PR you linked are fixed to the Astro Azure docs page 🤔

2022-09-19 11:58 UTC, TJaniF commented on guides/cross-dag-dependencies.md
> +The `TriggerDagRunOperator` is an easy way to implement cross-DAG dependencies from within the upstream DAG. This operator allows you to have a task in one DAG that triggers another DAG in the same A
o7

2022-09-19 14:47 UTC, merged